### ISSUE TITLE
Actionable Empty States Master Issue Thread

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#10120]
NOTE: Many AES changes were made with NoResultsView improvements project (https://github.com/wordpress-mobile/WordPress-iOS/issues/9504), mainly text and images. This issue contains the remaining tasks for AES.

- [x] Update UI elements to match design (text colors, fonts, spacing, etc.) (#10126)
- [x] Activity Log > no activity: update text (#10130)
- [x] Reader > My Likes: add 'Go to Following' action. (#10136)
- [x] Reader > Manage sites > no followed sites: add 'Discover Sites' action. (#10136)
- [x] Site Tags search: add 'no tags matching your search' view. (#10143)
- [x] Theme search: update no results view (#10156)
- [x] Site Pages and Blog Posts searches: update no results view (#10172)
- [x] Media searches: update no results view (#10178, https://github.com/wordpress-mobile/MediaPicker-iOS/pull/309)
- [x] Remove navigation bar button when empty view has an action button (#10182)
- [ ] Move `NoResultsViewController` and `NoResults.storyboard` to Shared pod.
- [ ] Nix `WPNoResultsView` in Shared pod.

**Comment by ScoutHarris** [comment]
I've removed this task as it's currently being developed on:

> Move `NoResultsViewController` and `NoResults.storyboard` to Shared pod.

It can be moved to Shared when/if needed.
