### ISSUE TITLE
Revisions/History Master Issue

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#10304]
### Revisions/History
This is the master issue for History / Revisions
_(This list will probably be updated as we go)_ 😀 

## V1
- [x] WP iOS: Implement WordPressKit 1.4.3-beta.2
- [x] WP iOS: Update AbstractPost model and CoreData model adding new entities (Revision and Diff)
- [x] WP iOS: Update local service and map the value from the RemotePost to the AbstractPost
- [x] WordPressKit: update remote service to load the post diffs
- [x] WordPressKit: add Revision and Diff models to map the post diffs and revisions
- [x] WP iOS: Add Revision and Diff models 
- [x] WP iOS: Add *History* actionsheet button (into the post editor)
  - remember to keep it behind a feature flag until we ship
- [x] WP iOS: Add Revisions List Screen
- [x] WP iOS: Implement WordPressKit 1.4.3-beta.4
- [x] WP iOS: Update local service mapping the new model from the remote response
- [x] WP iOS: Work on Revisions List Screen + cell UI
- [x] WP iOS: Load blog authors in order to load the profile picture
- [x] WP iOS: Get authors informations and populate Revision cell
- [x] WP iOS: Empty state (first time loading)
- [x] WP iOS: Add Revision Detail Screen
- [x] WP iOS: Apply selected revision (I guess load post + apply as selected + update)

## V2
- [x] WP iOS: Improve _Notice_ implementation in order to display the Undo button
- [x] WP iOS: Add HTML render

## Analytics:
- [x] Create an initial plan for analytics events and share with Android team

## Design:
[![aztec-revisions-ios-i2-thumb](https://user-images.githubusercontent.com/517257/47390562-8ce09100-d6cc-11e8-9c64-50281d653961.jpg)](https://user-images.githubusercontent.com/517257/47390543-83efbf80-d6cc-11e8-8796-d6badec19bda.jpg)
