### ISSUE TITLE
Groundskeeping (iOS) Master Issue : November 5 - 9 

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#10402]
### Description

This is an umbrella issue for _ad hoc_ tasks that I take on during my _Groundskeeping_ rotation. 

#### (Groundskeeping) Project Issues

- [X] Corrected a word count [issue](https://github.com/wordpress-mobile/WordPress-iOS/pull/10401) observed in the Editor.
- [X] Investigated a refresh control [issue](
https://github.com/wordpress-mobile/WordPress-iOS/issues/1039) in the Reader.
- [X] Researched a Fabric [crash](
https://github.com/wordpress-mobile/WordPress-iOS/issues/10170) related to haptic feedback on iOS 11.
- [X] Researched a **new** [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10421) where data for a single day is missing from Statistics.
- [X] Merged an [improvement](https://github.com/wordpress-mobile/WordPress-iOS/pull/10431) integrating a filter bar into the People view.
- [X] Merged a [fix](https://github.com/wordpress-mobile/WordPress-iOS/pull/10435) for a visual defect evident after editing the list of visible sites in My Sites.
- [X] Researched a state [defect](
https://github.com/wordpress-mobile/WordPress-iOS/issues/6341) in Notifications. The solution evaded me.

#### CocoaPods Administrivia

- [X] Relaxed dependencies in conjunction with [this fix](https://github.com/wordpress-mobile/WordPress-iOS/pull/10401).
- [X] Absorb Swift 4.2 support : `Gifu` & `Starscream`. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10416))

#### Code Hygiene

- [X] Removed unused Swift playground from the project. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10409))
- [X] Remove obsolete `available` check. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10410))
- [X] Removed obsolete usage of `synchronize` in/on `UserDefaults`. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10411))
- [X] Removed obsolete calls to `removeObserver(_:)` via `NotificationCenter`. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10413))
- [X] Removed superfluous `nil` completion handlers. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10414))
- [X] Removed some commented out code. ([PR](
https://github.com/wordpress-mobile/WordPress-iOS/pull/10415))
- [X] Resolved a console warning message. ([PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10417))

#### Assorted PR Reviews...

**Comment by rachelmcr** [comment]
Thanks for all your groundskeeping this week!
