### ISSUE TITLE
Stats Refresh Master Issue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#10840]
---
**NOTE: All open issues have been added to the [v2 Master Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/11852), and can be tracked there.**

---
### Milestones

- [x] 12.6: Release v1

### Time Away

- _May 24, 27_ : Stephenie AFK
- _May 27_ : Steve, Daniele AFK
- _May 27 - 31_ : Stephenie - groundskeeping
- _May 31_ : Steve's last sprint on the project

---
#### Pre-release preparation
 - [x] Design review (**TEAM**) - marked as complete as @SylvesterWilmott has used the 12.5 release from HockeyApp to do the review.

#### Shared
  - [X] Add tracks & validate (#11730) (@stevebaranski)

#### Issues
- [x] Date bar now only shows the current day (PR #11756) (@ScoutHarris )
- [x] "simple" stat cards are empty when no data (PR #11748) (@ScoutHarris )
- [x] _Posting Activity_ view is blank when no data (PR #11766) (@ScoutHarris )
- [x] _Posting Activity_ data is no longer correct (PR #11765) (@ScoutHarris )
- [x] Period queries being cancelled (#11742) (@danielebogo )
- [x] Browsing back from View More shows the wrong set of data (#11815) (@danielebogo )
- [x] Data discrepancies for Period _Published_ (#11371) (@jklausa)
- [x] Investigate Period summary fetch time (#11657) (@jklausa)
- [x] Details view take a long time to load (#11360) (@ScoutHarris)
  - [x] Period _Referrers_ (PR #11741) 

#### Release preparation
 - [x] Activate feature flag for 12.6 release (PR #11826) (@ScoutHarris)

---
#### Shared
  - [ ] Hide navigation bar on scroll (#10851)
  - [ ] Add additional Tracks events (#11775)

#### DWMY
  - [ ] Countries: Add map (#11083) (@danielebogo)

#### Enhancements:
- [x] While loading icons a grey square should be used. (PR #11745) (@ScoutHarris )
- [x] Referrers: (#11080)
  - [x] When no icon is available then show `gridicons-globe`. (PR #11741) (@ScoutHarris )
  - [x] Replace the `Search Engines` magnifying glass icon with `gridicons-search`. (PR #11674) (@frosty  )

#### Issues
- [ ] Stats page showing error when user doesn't have permissions to view stats on jetpack sites (#11823)
- [ ] Insights _Comments_ details doesn't show all (#11713) (@ScoutHarris / @jklausa)
- [ ] Retrieve country flags from the server (_Unassigned_)
- [ ] Retain cycle with StatsTotalRows (https://github.com/wordpress-mobile/WordPress-iOS/pull/10743#pullrequestreview-189348264)
- [ ] Emojis in post titles here get messed up (https://github.com/wordpress-mobile/WordPress-iOS/pull/10831#pullrequestreview-193454300)
- [ ] New Stats section needs Dynamic Type review. (#10845)
- [ ] Verify that locale/timezone account for this [Groundskeeping issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10421) re: missing data
- [ ] As I user, if _Posts and Pages_ is selected when navigating from _Insights_ to _Comments_, I expect that it will be selected when I navigate back to the _Insights_ screen. (https://github.com/wordpress-mobile/WordPress-iOS/pull/11181#issuecomment-469671502)
- [ ] [This issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/7186) is a remnant from legacy stats, but a reminder that we should be conduct a VoiceOver validating pass of Stats.
- [ ] Expanding/hiding rows makes the other rows "jump". (https://github.com/wordpress-mobile/WordPress-iOS/pull/10944#issuecomment-461020984)
- [ ] Toggling expandable rows updates all chevrons (#11743) (@ScoutHarris )
- [ ] Date bar: In Hebrew (RTL), arrows in wrong direction. (#11767)
- [ ] Card titles not aligned correctly in Hebrew (RTL) (#11768)
- [ ] Post Stats: table extended in landscape (#11602)
- [ ] Post Stats: extra spacing in post title label (#11637)
- [x] Several cards missing lines (PR #11754) (@ScoutHarris )
- [x] Insights _Most Popular Time_ icons are the incorrect color (PR #11794) (@ScoutHarris )
- [x] Insights _All Time Stats_: _Best Views Ever_ subtitle should be 15pt (PR #11795) (@ScoutHarris )
- [x] Insights _Posting Activity_ detail: incorrect layout after rotation (PR #11801) (@ScoutHarris )
- [x] Extra space when 'No data for this period' shown (PR #11813) (@ScoutHarris )
- [ ] Extra separator line when row expanded (#11799)
- [x] Period _Authors_: expanded rows should be 44pt (PR #11825) (@ScoutHarris )
- [ ] Period _Authors_ details: expanded rows should be 44pt (#11824)

---
#### Post release:
 - [ ] Remove feature flag & obsolesced code (#10975)

**Comment by ScoutHarris** [comment]
Milestones:
- 11.7: All Insights cards added.
- 12.3: Complete

THIS IS A WORK IN PROGRESS.

**Comment by ScoutHarris** [comment]
UI estimates as of Jan 16:

UI:
- Shared:
  - Empty states (8)
  - List view (to display the View mores) (8)
  - Implement charting library (13)
  - Add track (5)
  - Hide nav bar on scroll (8)
- Insights:
  - Insights: Add Annual Site Stats card (8)
  - Tags and Categories: update to have drop-down rows (8)
  - Annual Site Stats: update to use real data once backend is ready (8)
  - Loading view (8)
  - Latest Post Summary: Post Stats (32)
  - Latest Post Summary: Chart (8)
  - Tags and Categories: View more list view (8)
  - Comments: View more list view (8)
  - Followers: View more list (8)
- DWMY:
  - Create structure (8)
  - Videos (8)
  - Published (8)
  - Search Terms (8)
  - Countries (8)
  - Authors (8)
  - Clicks (8)
  - Referrers (8)
  - Posts and Pages (8)
  - Graph (8)

**Comment by jklausa** [comment]
My estimates for data work are as follows:

* Insights / Shared
    * Latest Post — 13 (this includes work on general structure of the data)
    * All Times — 5
    * Followers — 5
    * Most Popular — 8
    * Tags and Categories — 3
    * Annual — 13
    * Comments — Authors — 2
    * Comments —  Pages — 3
    * Followers — WPCom — 2
    * Followers — Email — 2
    * Today's Stats — 5
    * Posting Activity — 5
    * Publicise — 3
    * Post Stats — months, and years — 5
    * Average Views Per day — 3
    * Recent Weeks — 3

* DWMY 
    * Referers — 2
    * Posts and Pages — 2
    * Clicks — 2
    * Authors — 3
    * Countries — 5
    * Search Terms — 2
    * Published — 2

* Vaguely "other"
  * Persistence — 13
  * Insights management (reordering, enabling) — 8 (punted to V2)
  

Not included:

* Distinguishing between pages/posts for datapoints returning stats for those
* Keep around old logic of grouping tags/categories
* Decide on approach to timezones (https://a8c.slack.com/archives/CDHKS7X4M/p1544572700003300)

**Comment by ScoutHarris** [comment]
UI estimates as of Jan 28:

- Shared:
  - Empty states (8)
  - Table footers (5)
  - List view (to display the View mores) (8)
  - Implement charting library (13)
  - Add tracks (5)
  - When scrolling hide both appbar/navigation bar and tabs, date chooser remains fixed to the top. (8)
  - Post Stats (32)
  - Table cell for stats with expanding rows (8)
- Insights:
  - Update card order to match Android. (1)
  - Loading view (8)
  - Tags and Categories: update to have drop-down rows (8)
  - Tags and Categories: View more list view (8)
  - Annual Site Stats: update to use real data once backend is ready (8)
  - Latest Post Summary: Chart (8)
  - Comments: Authors, Pages & Posts View more list views (8)
  - Followers: View more list (8)
- DWMY:
  - Loading view (8)
  - Countries (8)
  - Authors (8)
  - Clicks (8)
  - Referrers (8)
  - Chart (8)
  - Posts and Pages: update icon depending on type. (5)
  - Posts and Pages: View more list view (8)
  - Videos: View more list view (8)
  - Search Terms: View more list view (8)
  - Published: View more list view (8)


Enhancements stemming from [feedback post](https://nodeadendsmobile.wordpress.com/2019/01/22/stats-feedback-and-solutions/):

- Insights:
  - Latest Post Summary: (8)
    - Move “views” to top and use full number
    - Move “likes” and “comments” to bottom as table rows
  - New design for “Most popular day and hour” (8)
  - New design for “annual site stats” (8)
  - Remove data bars from: (1)
    - Comments - Authors and Pages & Posts
    - Publicize
- DWMY:
  - Add date bar (8)
- Shared:
  - Start shortening numbers after 9,999 (1)

**Comment by ScoutHarris** [comment]
UI estimates as of Feb 12:

- Shared:
  - Empty states (8)
  - List view (to display the View mores) (8)
  - Implement charting library (13)
  - Add tracks (5)
  - Hide appbar/navigation bar and tabs on scroll, date chooser remains fixed to the top. (8)
  - Post Stats (32)
- Insights:
  - Loading view (8)
  - Tags and Categories: View more list view (8)
  - Latest Post Summary: Chart (8)
  - Comments: Authors, Pages & Posts View more list views (8)
  - Followers: View more list view (8)
  - Latest Post Summary: (8)
    - Move “views” to top and use full number
    - Move “likes” and “comments” to bottom as table rows
- DWMY:
  - Loading view (8)
  - Countries (8)
  - Referrers (8)
  - Chart (8)
  - Posts and Pages: update icon depending on type. (1)
  - Posts and Pages: View more list view (8)
  - Videos: View more list view (8)
  - Search Terms: View more list view (8)
  - Published: View more list view (8)
  - Add date bar (8)  
  - Authors: View more list view (8)
  - Clicks: View more list view (8)

**Comment by jklausa** [comment]
Feb 13: status/estimates


* Insights / Shared
    * ~Latest Post — 13 (this includes work on general structure of the data)~ done
    * ~All Times — 5~ done 
    * ~Followers — 5~ done
    * ~Most Popular — 8~ done
    * ~Tags and Categories — 3~ done
    * ~Annual — 13~ done
    * ~Comments — Authors — 2~ done
    * ~Comments —  Pages — 3~ done
    * ~Followers — WPCom — 2~ done
    * ~Followers — Email — 2~ done
    * ~Today's Stats — 5~ done
    * ~Publicise — 3~ done
    * Post Stats — months, and years — 5
    * Average Views Per day — 3
    * Recent Weeks — 3
    * Posting Activity — 5

* DWMY 
    * Referers — 2
    * Posts and Pages — 2
    * Clicks — 2
    * Authors — 3
    * Countries — 5
    * Search Terms — 2
    * Published — 2

* Vaguely "other"
  * Persistence — 13
  * Insights management (reordering, enabling) — 8 (punted to V2)

**Comment by stevebaranski** [comment]
I have created 9 issues that fulfill the Charting functionality as currently conceived. Each is listed below, along with a relative estimate associated:

1. [Insights : Construct Chart for Latest Post Summary (LPS)](#11061) (13)
1. [Selected Post : Construct Chart for Selected Post Performance](#11062) (8)
1. [Days / Weeks / Months / Years : Construct Chart of Views for a Given Period](#11063) (8)
1. [Enhance DWMY Chart to Support More Dimensions](#11064) (8)
1. [Ensure proper accessibility support in Charts](#11065) (5)
1. [Implement Analytics (placeholder)](#11066) (5)
1. [Adapt Latest Post Chart to leverage persisted data](#11067) (8)
1. [Adapt Selected Post Chart to leverage persisted data](#11068) (5)
1. [Adapt DWMY Charts to leverage persisted data](#11069) (8)

**Comment by stevebaranski** [comment]
### Charts Estimate, updated Feb 25

#### Work Accomplished since last estimate
~1. [Insights : Construct Chart for Latest Post Summary (LPS)](#11061) (13)~

#### Previously Scoped Work - Still Outstanding

1. [Selected Post : Construct Chart for Selected Post Performance](#11062) (8)
1. [Days / Weeks / Months / Years : Construct Chart of Views for a Given Period](#11063) (8)
1. [Enhance DWMY Chart to Support More Dimensions](#11064) (8)
1. [Ensure proper accessibility support in Charts](#11065) (5)
1. [Implement Analytics (placeholder)](#11066) (5)
1. [Adapt Latest Post Chart to leverage persisted data](#11067) (8)
1. [Adapt Selected Post Chart to leverage persisted data](#11068) (5)
1. [Adapt DWMY Charts to leverage persisted data](#11069) (8)

#### Newly Identified Work

1. [Correct number formatting on Chart axes](#11143) (8)
1. [Round the bars in Charts](#11144) (~13*~ => 0)

63 points; <2.5 person-sprints

**Comment by jklausa** [comment]
Bumped my estimates above. I'm (apart from any inevitable bugs/small issue follow-ups) now done with the networking layer and what's left is, roughly:
* mapping the objects we get from Network into Core Data entities
* making the `Stores` aware of the Core Data entites
* making the `Stores` handle data for multiple sites at once 

in my head it's more-or-less all part of "Supporting Core Data", so I bumped that item up to 21 points in the estimates (and will break it down before actually digging into it). 

I think it's realistically a one full sprint of work, but given that I'm away for most of this one (AFK Wed-Fri and then meetup the whole next one), it's gonna be two sprints of time.

**Comment by ScoutHarris** [comment]
UI estimates as of Feb 25:

- Shared:
  - Empty states (8)
  - Hide appbar/navigation bar and tabs on scroll, date chooser remains fixed to the top. (8)
  - Post Stats (32)
- Insights:
  - Loading view (8)
  - Tags and Categories: View more list view (8)
  - Comments: Authors, Pages & Posts View more list views (8)
  - Followers: View more list view (8)
  - Latest Post Summary: (8)
    - Move “views” to top and use full number
    - Move “likes” and “comments” to bottom as table rows
- DWMY:
  - Loading view (8)
  - Countries:
    - map (13)
    - View more list view (8)
  - Posts and Pages: update icon depending on type. (1)
  - Posts and Pages: View more list view (8)
  - Videos: View more list view (8)
  - Search Terms: View more list view (8)
  - Published: View more list view (8)
  - Authors: View more list view (8)
  - Clicks: View more list view (8)
  - Referrers: View more list view (8)
  - Add date bar (8)
- New Enhancements:
  - Icons: (5)
  - While loading icons a grey square should be used.
  - While loading avatars, a grey circle with `gridicons-user` should be used.
  - Referrers: (5) 
    - When no icon is available then show `gridicons-globe`. 
    - Replace the `Search Engines` magnifying glass icon with `gridicons-search`.
  - Tabs: Update filter tab bar to be blue. (5)

**Comment by stevebaranski** [comment]
### Charts Estimate, updated March 11

#### Work Accomplished since last estimate
~1. [Insights : Construct Chart for Latest Post Summary (LPS)](#11061) (13)~
~1. [Selected Post : Construct Chart for Selected Post Performance](#11062) (8)~
~1. [Days / Weeks / Months / Years : Construct Chart of Views for a Given Period](#11063) (8)~

#### Previously Scoped Work - Still Outstanding
1. [Enhance DWMY Chart to Support More Dimensions](#11064) (8)
1. [Ensure proper accessibility support in Charts](#11065) (5)
1. [Implement Analytics (placeholder)](#11066) (5)
1. [Adapt Latest Post Chart to leverage persisted data](#11067) (8)
1. [Adapt Selected Post Chart to leverage persisted data](#11068) (5)
1. [Adapt DWMY Charts to leverage persisted data](#11069) (8)

#### Newly Added / Identified Work

1. [Improve styling of Period Chart when Views/Visitors are overlaid](#11230) (3)
1. [Correct number formatting on Chart axes](#11143) (8)
1. [Round the bars in Charts](#11144) (~13*~ => 0)

50 points; ~2 person-sprints

**Comment by ScoutHarris** [comment]
UI estimates as of March 12:

- Shared:
  - Empty states (8)
  - Hide appbar/navigation bar and tabs on scroll, date chooser remains fixed to the top. (8)
  - Post Stats (24)
  - Stats Detail lists: show loading view (8)
- Insights:
  - Loading view (8)
  - Latest Post Summary: (8)
    - Move “views” to top and use full number
    - Move “likes” and “comments” to bottom as table rows
- DWMY:
  - Loading view (8)
  - Countries:
    - map (13)
    - View more list view (8)
  - Posts and Pages: update icon depending on type. (1)
  - Posts and Pages: View more list view (8)
  - Videos: View more list view (8)
  - Search Terms: View more list view (8)
  - Published: View more list view (8)
  - Authors: View more list view (8)
  - Clicks: View more list view (8)
  - Referrers: View more list view (8)
  - Add date bar (8)
- Enhancements:
  - Icons: (5)
    - While loading icons a grey square should be used.
    - While loading avatars, a grey circle with `gridicons-user` should be used.
  - Referrers: (5) 
    - When no icon is available then show `gridicons-globe`. 
    - Replace the `Search Engines` magnifying glass icon with `gridicons-search`.

**Comment by stevebaranski** [comment]
### Charts Estimate, updated March 25

#### Work Accomplished since last estimate

1. ~[Improve styling of Period Chart when Views/Visitors are overlaid](https://github.com/wordpress-mobile/WordPress-iOS/issues/11230) (3)~
1. ~[Chart highlight bar overlaps the legend](https://github.com/wordpress-mobile/WordPress-iOS/issues/11266) (1)~

#### Previously Scoped Work - Still Outstanding

1. [Enhance DWMY Chart to Support More Dimensions](https://github.com/wordpress-mobile/WordPress-iOS/issues/11064) (8)
1. [Ensure proper accessibility support in Charts](https://github.com/wordpress-mobile/WordPress-iOS/issues/11065) (5)
1. [Implement Analytics (placeholder)](https://github.com/wordpress-mobile/WordPress-iOS/issues/11066) (5)
1. [Adapt Latest Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11067) (8)
1. [Adapt Selected Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11068) (5)
1. [Adapt DWMY Charts to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11069) (8)
1. [Correct number formatting on Chart axes](https://github.com/wordpress-mobile/WordPress-iOS/issues/11143) (8)
1. [Round the bars in Charts](https://github.com/wordpress-mobile/WordPress-iOS/issues/11144) (~13*~ => 0)

#### Newly Added / Identified Work

(None)

### Projection

47 points remaining (i.e., <2 person-sprints)

**Comment by ScoutHarris** [comment]
UI estimates as of March 26:

- Shared:
  - Empty states (8)
  - Hide appbar/navigation bar and tabs on scroll, date chooser remains fixed to the top. (8)
  - Post Stats (24)
  - Stats Detail lists: show loading view (8)
- Insights:
  - Loading view (8)
- DWMY:
  - Loading view (8)
  - Countries: add map (13)
  - Posts and Pages: update icon depending on type. (1)
  - Add date bar (13)
- Enhancements:
  - Icons: (5)
  - While loading icons a grey square should be used.
  - While loading avatars, a grey circle with `gridicons-user` should be used.
  - Referrers: (5) 
    - When no icon is available then show `gridicons-globe`. 
    - Replace the `Search Engines` magnifying glass icon with `gridicons-search`.
- Issues
  - Issues listed in description and any additional that may arise. (13)

**Comment by jklausa** [comment]
I'm hoping to wrap-up my part of the work by the end of the week!

**Comment by stevebaranski** [comment]
### Charts Estimate, updated April 9

#### Work Accomplished since last estimate

1. ~[Enhance DWMY Chart to Support More Dimensions](https://github.com/wordpress-mobile/WordPress-iOS/issues/11064) (8)~
1. ~[Implement Analytics (placeholder)](https://github.com/wordpress-mobile/WordPress-iOS/issues/11066) (5)~

#### Previously Scoped Work - Still Outstanding

1. [Ensure proper accessibility support in Charts](https://github.com/wordpress-mobile/WordPress-iOS/issues/11065) (5)
1. [Adapt Latest Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11067) (8)
1. [Adapt Selected Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11068) (5)
1. [Adapt DWMY Charts to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11069) (8)
1. [Improve number formatting on Chart axes](https://github.com/wordpress-mobile/WordPress-iOS/issues/11143) (8)

#### Newly Added / Identified Work

(None)

### Projection

34 points remaining (i.e., <2 person-sprints)

**Comment by ScoutHarris** [comment]
UI estimates as of April 15:

- Shared:
  - Add tracks (5)
  - Hide appbar/navigation bar and tabs on scroll, date chooser remains fixed to the top. (8)
  - Post Stats (24)
  - Stats Detail lists: show loading view (8)
  - Post Stats: tap post title opens post in webview (5)
- Insights:
  - Loading view (8)
- DWMY:
  - Loading view (8)
  - Restart queries when period or date changes (5)
  - Overview card: populate with actual data (5)
  - Countries: add map (13)
  - Posts and Pages: update icon depending on type. (1)
  - Date bar: Add to Post Stats view (8)
- Enhancements:
  - Icons: (5)
  - While loading icons a grey square should be used.
  - While loading avatars, a grey circle with `gridicons-user` should be used.
  - Referrers: (5) 
    - When no icon is available then show `gridicons-globe`. 
    - Replace the `Search Engines` magnifying glass icon with `gridicons-search`.
- Issues
  - Issues listed in description and any additional that may arise. (13)

**Comment by stevebaranski** [comment]
### Charts Estimate, updated April 23

#### Work Accomplished since last estimate

1. ~[Ensure proper accessibility support in Charts](https://github.com/wordpress-mobile/WordPress-iOS/issues/11065) (5)~

#### Previously Scoped Work - Still Outstanding (or In Progress)

1. [Adapt Latest Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11067) (5)
1. [Adapt Selected Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11068) (5)
1. [Adapt DWMY Charts to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11069) (5)
1. [Improve number formatting on Chart axes](https://github.com/wordpress-mobile/WordPress-iOS/issues/11143) (8)

#### Newly Added / Identified Work

(None)

### Projection

23 points remaining (i.e., ~1 person-sprint)

**Comment by stevebaranski** [comment]
### Charts Estimate, updated May 6

#### Work Accomplished since last estimate

1. ~[Adapt Latest Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11067) (5)~
1. ~[Adapt Selected Post Chart to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11068) (5)~
1. ~[Improve number formatting on Chart axes](https://github.com/wordpress-mobile/WordPress-iOS/issues/11143) (8)~

#### Previously Scoped Work - Still Outstanding (or In Progress)

1. [Adapt DWMY Charts to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11069) (5)

#### Newly Added / Identified Work

1. Overview chart: when a bar is selected, update overview data accordingly; when the view first appears, auto select the most recent day; when the date changes via the date chooser, auto select corresponding bar. (8)

### Projection

13 points remaining

**Comment by ScoutHarris** [comment]
UI estimates as of May 7:

- Shared:
  - Add tracks (5)
  - Hide appbar/navigation bar and tabs on scroll, date chooser remains fixed to the top. (8)
  - Post Stats: show loading view (8)
  - Stats Detail lists: show loading view (8)
- Insights:
  - Properly display cached data with no network connection (5)
- DWMY:
  - Loading view (8)
  - Countries: add map (13)
- Enhancements:
- Icons: (5)
  - While loading icons a grey square should be used.
  - While loading avatars,  a grey circle with `gridicons-user` should be used.
- Referrers: (5)
    - When no icon is available then show `gridicons-globe`. 
    - Replace the `Search Engines` magnifying glass icon with `gridicons-search`.
- Issues
  - Period summary query takes a long time to return data. (8)
  - Period data not refreshing correctly when queries finish. (5)
  - Details view take a long time to load (13)
  - Other issues listed in description and any additional that may arise. (13)

**Comment by danielebogo** [comment]
## Estimation - May 8
#### Insights
• Properly display cached data with no network connection (5)
#### DWMY
• Loading view and error message (8)
• Countries: add map (13)

**Remaining:** 26 points

**Comment by stevebaranski** [comment]
### Charts Estimate, updated May 20

#### Work Accomplished since last estimate

1. ~[Adapt DWMY Charts to leverage persisted data](https://github.com/wordpress-mobile/WordPress-iOS/issues/11069) (5)~
1. ~Overview chart: when a bar is selected, update overview data accordingly; when the view first appears, auto select the most recent day; when the date changes via the date chooser, auto select corresponding bar. (8)~

#### Previously Scoped Work - Still Outstanding (or In Progress)

N/A

#### Newly Added / Identified Work

N/A

### Projection

0 points remaining

**Comment by danielebogo** [comment]
## Estimation - May 21
#### Insights
• ~Properly display cached data with no network connection (5)~
• ~Loading view on Stats detail~
#### DWMY
• ~Loading view and error message (8)~
• ~Loading view on Stats detail~
• Countries: add map (13)

**Comment by ScoutHarris** [comment]
[v2 Master Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/11852) created, which includes all outstanding issues from v1. Closing this.
