### ISSUE TITLE
Master Issue: Quick Start v2

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#10860]
This is the master issue for tracking Quick Start v2.

### Tasks
- [x] Notice for users that quick start has changed
- [x] Add a new section within blog details screen with 2 rows: Customize Your Site and Grow Your Audience
- [x] Customize new section
- [x] Add new tours
- [x] Present the checklist view controller instead of pushing
- [x] Update the logic if all tours are completed
- [x] iPad: Select always Stats as first row and remove selection behaviour for QS rows. 
- [x] Update logic for present notice: only trigger notices if the user first completes a task manually
- [x] Update QS tasks list separating the completed list from the to do list
- [x] QS Checklist: add skip on a single row
- [x] QS Checklist: add congratulation background
- [x] Updated analytics events
- [x] Local push notification 48 hours after app last opened (#11022)
- [x] Ellipsis `…` menu to remove `Next Steps` section (#11028)

### Bugs
- [x] #11041 - Header's gap is too big
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/10835
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/10446
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/10297
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/10282

**Comment by sirisak1985** [comment]
#10860
