### ISSUE TITLE
Improve offline messaging on WPiOS

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11005]
### [SCOPE]
For this issue, when thinking about how we want to notify the user on lack of connectivity when the
**user is trying to view or get more information on a given screen.**

### [CURRENT STATE]
**Currently, we display a connectivity issue message in 2 ways:**

_Full page messages_
For screens where there is no local data stored and the app is unable to fetch the data required to render the screen views — we display a full page message letting the user know that the screen cannot be displayed due to connectivity issues.

_Alerts_
For the case when there is local data displayed, and the user is requesting more data (think pull to refresh) we display a temporary notice letting the user know that more data can’t be displayed due to the connection.

### _Full page messages_
![ios-full-page-4](https://user-images.githubusercontent.com/1335657/52743103-238fd100-2f8e-11e9-8bb9-d56acb3c29b4.png)

- [x] Update copy of all full screens to one of the 2 options  #11030 
    1    1    No internet connection / Unable to load this page right now.
    2    Unable to load this page right now. / Check your connection and try again.

- [x]  update the illustration on full page messages  #11031 

- [x] Verify we consistently display full page messages when local data is unavailable #11032 

### _Alerts_
![ios-snackbar-unable-to-load-2](https://user-images.githubusercontent.com/1335657/52743120-2a1e4880-2f8e-11e9-91c6-62a6210cbc9a.png)
- [x] Implement a snack bar notice according to design  #11033 

- [x] Configure snackbar message according to state and location: #11034 
- "No internet connection. Some posts may be unavailable while offline."
- ” Some pages may be unavailable while offline. 
- ” Some media may be unavailable while offline. 
- ” Some comments may be unavailable while offline. 
- ” Some settings may be unavailable while offline. 
- ” Some content/information/data may be unavailable while offline. (for generic use)

- [x] Replace occurrence of pop up alerts with  the new snack bar implementation #11035

**Comment by kwonye** [comment]
This is great, @yaelirub! Thanks for the write up.

For the sake of the project, can you split out the individual checklist items (or any other split you find makes sense) into individual issues please? This way we can move items every few days instead of one large PR.

**Comment by yaelirub** [comment]
Definitely, @kwonye !

**Comment by shiki** [comment]
@yaelirub Should we move this to _Done_ since we have separate tickets for the remaining issues?
