### ISSUE TITLE
Testing: Implement UI tests for critical user flows

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11013]
We want to make sure that these critical user flows are covered with UI tests:

- [x] Signup with email
- [x] ~Signup with Google (if possible)~
- [x] Login to self-hosted site
- [x] Login to WordPress.com with email & magic link
- [x] Login to WordPress.com with email & password
- [x] ~Login to WordPress.com with Google (if possible)~
- [x] Publish a basic post

With our existing UI tests as a starting point, we need to also do the following:

- [x] Fix the existing login tests (#10987)
- [x] Fix the existing editor tests (#11021)
- [x] Remove the shell script from the test setup flow (#11055)
- [x] Move the test credentials into a mobile secrets file for consistency (#11055)

**Comment by rachelmcr** [comment]
As noted in the review for #11021:

> in the future we could have the data for editor tests outside of the code to have the option to dynamically test varying content

This change can be implemented when we work on the critical user flow for publishing a basic post. (We could perhaps leave `testSimplePublish` and add a new test that includes all of the steps we want to cover in a full post publishing flow.)

**Comment by rachelmcr** [comment]
Also, for reference, here are the flows we mapped out to cover with this set of UI tests:

**Login**

![image](https://user-images.githubusercontent.com/8658164/53054344-01b9b100-349c-11e9-8f07-adfcbeaff974.png)

**Signup**

![image](https://user-images.githubusercontent.com/8658164/53054363-0d0cdc80-349c-11e9-94c2-0f984aa37cb6.png)

**Publish a post**

![image](https://user-images.githubusercontent.com/8658164/53054376-14cc8100-349c-11e9-9996-4f6ab9a1b476.png)

**Comment by rachelmcr** [comment]
Adding some of my notes here, since some of them also came up in the review for https://github.com/wordpress-mobile/WordPress-iOS/pull/11093 and should be documented.

When adding the new test for a basic publishing flow, consider the following editor test improvements:

* Add a data helper for random post content (rather than arbitrary static content in the test).
* Improve the publish step so it checks for either the "Publish with Confidence" fancy alert (seen the first time you publish a post) OR the regular publish confirmation sheet/alert.
* Improve the `isIphone` extension for consistency with the `isIpad` extension.

I'd also like to look at general improvements before we fully launch these tests:

* Improving our accessibility identifiers (ensuring they are all unique and adding some to elements and components that currently don't have them).
* Extending the fancy alert component object so each fancy alert is initialized on a unique value (to ensure the correct alert is shown).
* Investigate improvements to the test output to ensure that test failures are as clear as possible.

**Comment by rachelmcr** [comment]
I'm closing this issue as all of the initial tests have been completed and necessary improvements are being tracked in separate issues. We can continue to make general improvements as needed, as we move forward using these tests.
