### ISSUE TITLE
Groundskeeping Master Issue - 2018-03-03 to 2018-030-08

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#11197]
### Description

Tasks that I take on during my _Groundskeeping_ rotation. 

#### (Groundskeeping) Project Issues

- [x] Investigated a tag [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10735/)
- [x] Sorted a crash on remove self-hosted sites reported [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/11094)
- [x] Worked on sorting out a security issue on the WP iOS app. We found that the user token was sent to all image URLs on a private site even when not referring to WP.com site. 
- [x] Worked on improving error messages when  changing account details #11214 

#### Pull Requests

 - https://github.com/wordpress-mobile/WordPress-iOS/pull/11212
 - https://github.com/wordpress-mobile/WordPressKit-iOS/pull/116
 - https://github.com/wordpress-mobile/WordPress-iOS/pull/11211#pullrequestreview-212214687
 - https://github.com/wordpress-mobile/WordPress-iOS/pull/11229
