### ISSUE TITLE
Post List Revamp Master Issue

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#11646]
This is a master issue to track the post list revamp on iOS.

# Changes

* View toggle to switch between card/list view
* Updated card designs

# Blueprint

![post_list_blueprint](https://user-images.githubusercontent.com/7040243/57258653-6ca66d00-7033-11e9-83e3-51f01f179cba.png)

# Subtasks

- [x] Replace the "More" behavior to show options in an Action Sheet #11661
- [x] Update card designs and do not display author name when "Me" is selected https://github.com/wordpress-mobile/WordPress-iOS/pull/11705
- [x] Display "skeleton post card" when loading posts #11789
- [x] Adapt cards so it can be displayed in a compact way #11816
- [x] Change search to always happen in a list view #11830
- [x] Enable the list view option #11816
- [x] Improvements and polishes #11974
- [ ] Merge with `develop` and integrate

**Comment by leandroalonso** [comment]
Note: action sheets are inverted for `scheduled` and `trashed` posts in the blueprint. "View" option only appears when showing the compact mode.
