### ISSUE TITLE
Webviews: tapping `tel:` or `mailto:` protocol links in a webview results in an "unsupported URL" error

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11645]
Steps to reproduce:

1. Create some links in a post or sidebar widget with the `tel:` and `mailto:` link protocols.<br><sup>You can use the sample content below.</sup>
1. Save and publish the post.
1. Tap "View" in the snack bar that shows after the post is published to open a Preview.<br>Or you can tap "View" on the post in the Posts List.
1. Note that the links work in a Preview.
1. Go to Reader > Followed Sites and find the post.
1. Tap on the post to open the Reader view and try the links.
1. Tap the More menu at top right and select "Visit" to open a Webview and try the links.
1. Go to My Sites > View Site, find the post, and try the links.

<strong>Result:</strong> tapping on `tel:` or `mailto:` links from a Webview results in an "unsupported URL" error, but those same links work normally in Previews and from a mobile browser such as Safari. ([2m17s](https://cloudup.com/c6gz8rho0mE))

<strong>Sample content:</strong> 

```
<a href="tel:(415) 555 1212">Call (415) 555 1212</a>

<a href="mailto:someone@example.com">Send Email</a> 
```

<img src="https://user-images.githubusercontent.com/1119271/57255683-d9107480-7011-11e9-9fa8-757486003e50.png" width="270" alt="protocol-links-sample-content"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57255682-d9107480-7011-11e9-820b-f5e12335bb86.png" width="270" alt="error-unsupported-url">
<p style="clear:both;"><sup>Tested with WP Internal 12.3.0.20190422 on iPhone 6S iOS 12.2 on `design5279.wordpress.com`.</sup></p>

<sub>(internal reference: p4a5px-2of-p2 and 1999324-zen)</sub>

**Comment by designsimply** [comment]
Noting some possibly useful Apple and StackOverflow links:

* [Apple URL Scheme Reference](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007899-CH1-SW1)
* [How to make phone call in iOS 10 using Swift?](https://stackoverflow.com/a/40079079/1100719)

**Comment by designsimply** [comment]
Added to the `Groundskeeping` project because we've been working recently to improve `Webviews` interactions.

**Comment by brookewp** [comment]
I just ran into this issue with a user who has a Contact Info Widget added to their site and the telephone field filled out. I was able to replicate as well. 

cc @designsimply

**Comment by reginabally** [comment]
Another report in 3385201-zen on version 15.7.

![Screen Shot on 2020-10-08 at 11:08:58](https://user-images.githubusercontent.com/40906847/95410530-d298d180-0956-11eb-92e8-ebb304dbef63.png)

The link in the notification is `mailto:`

**Comment by mindgraffiti** [comment]
Relevant Stack Overflow: https://stackoverflow.com/a/52174457. iOS 13 and below will need special links (`tel:` `mailto:` `facetime:`) handled.

~Interestingly, it works in iOS 14, WPiOS 16.1, with no changes.~ (only in certain places).

**Comment by momo-ozawa** [comment]
Another report in 3479618-zen on version 16.0 / iOS 14.1 for a `mailto:` link.

**Comment by mindgraffiti** [comment]
These are probably 3 separate classes. 

- [ ] Support common link protocols in Reader posts (`ReaderDetailViewController`) #15307 
- [ ] Reader > {post} > {more} > Visit (webview) #15310 
- [ ] Notifications > tap a link > (webview) #15310

**Comment by mindgraffiti** [comment]
Part 3. Rough outline of steps to reproduce:

0. Make sure your test site sends notifications for new followers on your blog.
1. Have a test site with a Personal Plan (at minimum). 
2. Create a new page and add the Payments block.
3. Log in with a test account to be the subscriber.
4. Subscribe to the test site and pay (use a dev testing account).
5. Go to the app > Notifications and open the subscriber notification.
6. Tap the "Contact <subscriber>" link in the notification detail view.

**Comment by mindgraffiti** [comment]
Part 3.  Notifications > tap a link > (webview) uses the same universal coordinator as Part 2. So the fix is already in place for Part 3.

**Comment by mindgraffiti** [comment]
Timeboxed an attempt to test the payments notification. I couldn't successfully receive a masterbar notification using a testing environment. Once this bug is closed, it would be good to follow up with 3385201-zen to see if the link works.
