### ISSUE TITLE
2019 Color Palette Update Master Issue

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#11683]
## Goals
- Update the app to use the new Classic Bright color palette, just as [Android has](https://github.com/wordpress-mobile/WordPress-Android/pull/9495)

## Tasks
- [x] Update project to iOS 11+
- [x] Add iOS format to the [Automattic color studio](https://github.com/automattic/color-studio) (thanks @porada)
- [x] New color API (#11946)
- [x] Replace colors throughout app
  - [x] Tab bar
  - [x] Navigation bar
  - [x] Table views
  - [x] Existing code colors to new API
  - [x] Login/Signup flow

## For iteration 2 or dark mode
- [ ] Make tab bar translucent
  - Also make sure views go below the tab bar. For example, reader currently doesn't.

## Smaller issues
**Note**: Use the semantic colors whenever possible. That means `primary` for Blue, `neutral` for gray, `text` for text/default text, `textSubtle` when text is `neutral-50`, etc. When unsure, check the values in `extension UIColor` in `UIColor+MurielColor` (or the ObjC file when necessary). 

- [x] Update colors in new blog post list once that is merged #12087
- [x] Background color of custom table views #12007
- [x] Notification selection color #2589
- [x] Ensure media picker doesn't revert navigation bar colors
- [x] Reader buttons are a bit off
- [x] Tab bar unselected state should be neutral-200
- [x] Yellow "private" text should be gray, preceded by a •
- [x] Register domain yellow icon should be yellow-20
- [x] The border below this header should be neutral-5 (#12167)
- [x] The “Comment on…” text should be neutral-50  (#12167)
- [x] The “Weekly hangout” text can be the default text color  (#12167)
- [x] Number of likes button text in Reader comments is still orange (#12167)
- [x] Likes star color in Reader comments view should match reader post list (#12167)
- [x] No results view: lighter than the table view background
---
- [x] On the manage plugins screen, we can use the same green-40 and yellow-40 for Active/Needs Update icons. For the text, we can use green-50 and yellow-50.
- [ ] For the plugins search field, default `text` color in place of the current dark gray; neutral-50 in place of the lighter gray text.
- [ ] Change the default plugin icon from that shade of blue to neutral-50
---
- [ ] backgrounds: Activity Log has a blue background
	- [ ] Themes is also blue and Menus is too dark
	- [ ] media background also wrong
- [ ] Animation box needs new assets from @mattmiklic 
- [x] Post-post screen uses old colors

---
**Login/Signup**
- [x] Login/Signup still has some [old blue](https://github.com/wordpress-mobile/WordPress-iOS/pull/12029#pullrequestreview-255968787)
- [x] Log in to…” and “Alternatively” text should be `neutral`
- [x] Separators are an old gray, should be `neutral` 10
- [x] The icon next to “log in by” should be `neutral` 30
- [x] We’ll email you…” text is an old gray, should be `text` color.
- [x] Enter your password instead” is gray, should be `primary`

## Analytics
There are no analytics events for this project.

**Comment by koke** [comment]
The buttons on the prompt when you have push notifications disabled have the old colors:

![IMG_8F1F681DD906-1](https://user-images.githubusercontent.com/8739/60424762-5101b200-9bf1-11e9-9beb-2b3497002fa3.jpeg)

**Comment by koke** [comment]
The headers for Me and BlogDetails are different. Comparing to the section header color they might both be wrong, but I think at least one of them is:

![colors](https://user-images.githubusercontent.com/8739/60426108-4268ca00-9bf4-11e9-983e-ec64f9cc978e.png)

**Comment by koke** [comment]
> Reader buttons are a bit off

I would add that cell borders are also off, the gear icon for the "Manage" cell at the top, the "Fecthing posts..." animation looks blue-ish...


![Screen Shot 2019-07-01 at 11 38 23](https://user-images.githubusercontent.com/8739/60427649-6a0d6180-9bf7-11e9-88bf-4a391fe9b2bf.png)
![Screen Shot 2019-07-01 at 11 38 36](https://user-images.githubusercontent.com/8739/60427651-6a0d6180-9bf7-11e9-996a-4e1637139dc5.png)

**Comment by koke** [comment]
Another one, I found some discrepancies between the blog list styles in "My Sites" vs "Reader > Manage"

![reader-manage-following](https://user-images.githubusercontent.com/8739/60427993-3121bc80-9bf8-11e9-8f8c-76f0de2c0aa7.png)

**Comment by koke** [comment]
Me > Support > WordPress Help Center has the wrong colors on the search bar:

![Screen Shot 2019-07-01 at 12 04 36](https://user-images.githubusercontent.com/8739/60428131-79d97580-9bf8-11e9-87b7-38bc3c5565d0.png)

**Comment by frosty** [comment]
When sharing from the WordPress app using our share extension the nav bar button text is white, so the buttons are almost invisible:

![IMG_455C6AE5EB47-1](https://user-images.githubusercontent.com/4780/61406826-8c300080-a8d4-11e9-9f84-b15361cf464e.jpeg)

**Comment by mattmiklic** [comment]
![Simulator Screen Shot - iPhone Xs Max - 2019-07-26 at 15 15 46](https://user-images.githubusercontent.com/1396552/61976037-b494ba80-afb8-11e9-9a9b-8003c1f59b48.png)

Icons in the Sharing section are too light, should be Gray 30 to match icons on the My Site screen.

**Comment by mattmiklic** [comment]
In addition to the blue backgrounds in the Activity Log (reported above), grouped table view headers are also blue. They should be Gray 50.

![IMG_F84C9509D00D-1](https://user-images.githubusercontent.com/1396552/61976225-3553b680-afb9-11e9-90d2-16e76c298d81.jpeg)

**Comment by SylvesterWilmott** [comment]
Odd colouration of Quick Start section header
![IMG_3420](https://user-images.githubusercontent.com/36532468/62299150-4d6d7f00-b46c-11e9-8cd1-596b3171c0ed.PNG)


Background of site creation is too dark
![IMG_3421](https://user-images.githubusercontent.com/36532468/62299165-5bbb9b00-b46c-11e9-949d-95868ffef405.PNG)
