### ISSUE TITLE
Stats Refresh v2 Master Issue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11852]
#### Shared
- [ ] Hide navigation bar on scroll (#10851)
- [ ] Add additional Tracks events (#11775)
- [ ] Update Widget - awaiting input from Sly.

#### Insights
- [ ] Insights Management
  - [ ] Initially, display these stats in this order: _Posting Activity_, _Today_, _All-Time_, _Most Popular Time_, _Comments_
  - [ ] Add an `Edit` button at the bottom of the Insights table to access the `Manage Insights` page.
  - [ ] Manage Insights:
    - [ ] Add to Insights.
    - [ ] Remove from Insights.
    - [ ] Reorder displayed Insights.
  - [ ] Ellipsis button on card headers has options to:
    - [ ] Move up
    - [ ] Move down
    - [ ] Remove from Insights
  - [ ] If all Insights removed, show empty state with `Manage Insights` button.
  - [ ] `News` card: announce IM and scrolls down to the Edit button.
- [ ] Insights _Comments_ details: change to a single non-filtered list (#11713)
  - [ ] Implement support for `/sites/$site/stats/comment-followers` query.
  - [ ] Update details view to show results from `comment-followers`, remove `FilterTabBar`.
- [ ] Two column block type:
  - [ ] _Today_ (renamed from Today's Stats)
  - [ ] _All-time_ (renamed from All Time Stats)
  - [ ] _This Year_ (renamed from Annual Site Stats)
  - [ ] _Most Popular Time_
  - [ ] _Follower Totals_
- [ ] Add `View more` details for _This Year_ (after convert to new block type).

#### DWMY
- [ ] _Countries_: Add map (#11083) (@danielebogo)
- [ ] Remove _Published_? - awaiting input from Sly.

#### Issues
- [ ] Stats page showing error when user doesn't have permissions to view stats on jetpack sites (#11823)
- [ ] Retrieve country flags from the server
- [ ] Retain cycle with StatsTotalRows (https://github.com/wordpress-mobile/WordPress-iOS/pull/10743#pullrequestreview-189348264)
- [ ] Emojis in post titles here get messed up (https://github.com/wordpress-mobile/WordPress-iOS/pull/10831#pullrequestreview-193454300)
- [ ] New Stats section needs Dynamic Type review. (#10845)
- [ ] Verify that locale/timezone account for this [Groundskeeping issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10421) re: missing data
- [ ] As I user, if _Posts and Pages_ is selected when navigating from _Insights_ to _Comments_, I expect that it will be selected when I navigate back to the _Insights_ screen. (https://github.com/wordpress-mobile/WordPress-iOS/pull/11181#issuecomment-469671502)
- [ ] [This issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/7186) is a remnant from legacy stats, but a reminder that we should be conduct a VoiceOver validating pass of Stats.
- [ ] Expanding/hiding rows makes the other rows "jump". (https://github.com/wordpress-mobile/WordPress-iOS/pull/10944#issuecomment-461020984)
- [ ] Toggling expandable rows updates all chevrons (#11743) (@ScoutHarris )
- [ ] Date bar: In Hebrew (RTL), arrows in wrong direction. (#11767)
- [ ] Card titles not aligned correctly in Hebrew (RTL) (#11768)
- [ ] Post Stats: table extended in landscape (#11602)
- [ ] Post Stats: extra spacing in post title label (#11637)
- [ ] Extra separator line when row expanded (#11799)
- [ ] Period _Authors_ details: expanded rows should be 44pt (#11824)

#### Cleanup:
 - [ ] Remove feature flag & obsolesced code (#10975)

**Comment by ScoutHarris** [comment]
Note - removed these as they will be separate projects:
- Update Widgets - pending designs.
- Insights Management (Master Issue #12243)

**Comment by ScoutHarris** [comment]
Moved `Remove feature flag & obsolesced code` to [Stats Widgets Master Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/12702) as it's being tracked there.

**Comment by staskus** [comment]
@guarani I propose we close this and all [Stats Refresh] related tickets to clean the Stats issue bucket. Too many things have changed, even if some issues may be partially still valid. I would've closed it immediately, but I saw that you edited labels recently.

**Comment by guarani** [comment]
Good idea! I only changed the labels as part of a bulk change to remove old project labels, so I'll go ahead and close this as complete.
