### ISSUE TITLE
Draft changes are not saved when updating it offline

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#11905]
## Expected behavior

Draft changes are saved. 

## Actual behavior

The changes are shown initially but disappear as soon as the _Retry_ button is clicked. The Editor is also cleared when you click on _Update_. 

### Steps to reproduce the behavior

1. While online, create a draft. Make sure the draft is uploaded to the server. 
2. Stay on the Post List and go offline. 
3. Edit the draft. Make some changes.
4. Click on the _Update_ button. Notice the contents and title will disappear and you will receive an error message. 
5. Exit the Editor by pressing the ✖️ button. 
6. Go online. Notice the Post List will show your recent offline changes. 
7. Click on the _Retry_ button. 

After clicking the _Retry_ button, the contents are immediately reverted to the contents before the offline editing. 

![2019-06-12 17 04 37 2019-06-12 17_14_19](https://user-images.githubusercontent.com/198826/59392627-87a48500-8d35-11e9-9e7b-284106fde0a8.gif)

Tested on iPhone XS, iOS 12.2, WPiOS `develop` (2899e8a5695ae4bf2a739315e843bb32cde207bd).

## Tasks 

- [x] #11924 Fix the Editor clearing the contents
- [x] #11920 Revert and reopen https://github.com/wordpress-mobile/WordPress-iOS/pull/11736. This caused the Editor to clear the contents 
- [x] ~~Figure out why https://github.com/wordpress-mobile/WordPress-iOS/pull/11736 is not enough~~. This will be handled again in #11435.  
- [x] #11924 Fix upload discarding the changes. This seemed to happen between 12.6 and `develop`.

**Comment by yaelirub** [comment]
@shiki , please take a look at this: https://github.com/wordpress-mobile/WordPress-iOS/pull/11898

**Comment by shiki** [comment]
Closing this since this was mostly about reversing the fix for https://github.com/wordpress-mobile/WordPress-iOS/issues/11435. We will continue the work again on that issue.
