### ISSUE TITLE
iOS 13 Fixes Master Issue

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#12211]
This is a master issue to track any issues that need to be addressed when building with the iOS 13 SDK.

### Visual Issues

- [x] We should set the window background color to black, otherwise the new modal style looks odd:

![ios-13-modal](https://user-images.githubusercontent.com/4780/61955965-0e46b600-afb4-11e9-8f04-109c1097c439.png)

- [x] The login screen is now displayed as a dismissable modal, which we don't want :)
- [x] The font for filter bar tabs is larger than the default on <= iOS 12:

![image](https://user-images.githubusercontent.com/4780/61956212-8b722b00-afb4-11e9-8e2f-881b113c5482.png)

- [ ] In Menus, the link editing screen is a dismissable modal but it doesn't handle it very well
- [x] There's some very strange artifacting going on behind images in Reader detail views:

![Simulator Screen Shot - iPhone Xs - 2019-07-26 at 14 09 03](https://user-images.githubusercontent.com/4780/61956323-cb391280-afb4-11e9-9f06-28b62201d9bd.png)

- [x] On iPad, split view detail navigation bars are just grey:

![Simulator Screen Shot - iPad Pro (11-inch) - 2019-07-26 at 16 13 17](https://user-images.githubusercontent.com/4780/61962035-8f0baf00-afc0-11e9-917a-bbdefc9d58cb.png)

### Crashes

- [x] Crash when accessing notifications:

```
**2019-07-26 14:17:22.975387+0100 WordPress[425:22327] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/frosty/src/WordPress-iOS/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift, line 1315**
```

- [x] Crash dismissing the notification permission fancy alert (main thread checker):

```
**sSo25BlogDetailsViewControllerC9WordPressE27showNotificationPrimerAlert33_56328A7BA85AC7396CCA3209E34AC98CLLyyFySo21UNAuthorizationStatusVcfU_y0eF2UI05FancyjcD0CcfU_yycfU_**
```

**Comment by frosty** [comment]
There are some issues with the author popover (mainly content inset): https://github.com/wordpress-mobile/WordPress-iOS/issues/12330
