### ISSUE TITLE
Insights Management Master Issue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#12243]
Allow users to customize what stats are displayed in Insights. ([#](https://wp.me/paCL20-dU-p2))

---
#### 13.6:
- [x] Remove feature flag (#12815)

#### 13.5:
- [x] Add `Add New Stats Card` functionality (#12246)
- [x] Save Insights settings (#12249)
- [x] Stats already displayed are greyed out and disabled. (#12633)
- [x] Add ability to organize cards (#12247)
- [x] Show empty view (#12248)
- [x] Update when the Customize card is hidden (#12685)
- [x] Add Accessibility support for Add Insight view (#12651)
- [x] Add Accessibility support for Manage Insight (#12647)
- [x] Add Analytics tracking (#12723)
- [x] Subtitles not sized correctly after adding stat (#12709)
- [x] Update views for Dark Mode (#12660)
- [x] Update Customize card image (#12726)
- [x] Enable feature flag & add to Release Notes (#12728)

#### 13.1:
- [x] Add feature flag.
- [x] Add `Customize your insights` card. (#12244)
- [x] Add `Add new stats card` card (#12245)
- [x] Add new tracks (#12269)
- [x] Add 'Add New Stats Card' view (#12281)

---
![stats_insights_management_ios](https://user-images.githubusercontent.com/1816888/62237872-08274f80-b38f-11e9-8efa-ee6c095008c0.png)
