### ISSUE TITLE
[Auto-upload Published] Full publishing and cancellation flow

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12240]
This covers the following part of #12227: 

<img width="1243" alt="60972121-8ad36680-a31d-11e9-930b-e5d3f3fd79fc jpg (1320×3178) 2019-07-30 16-14-40" src="https://user-images.githubusercontent.com/198826/62169329-2e90b080-b2e5-11e9-9ca4-203eaeab6e71.png">

### Drafts

 Test Case | Status 
---|----
| <p>Post stays in Drafts and SnackBar appears</p><p>Status: Android and iOS show different messages.</p> |  |
| Local drafts are automatically uploaded **as drafts** | ✔️ #11839 #12215 | 
 Drafts with un-confirmed changes are remote-auto-saved | 
 Drafts with confirmed changes are automatically uploaded | 

### Publishing

 Test Case | Status 
---|----
 When offline:<ul><li> Post stays in Drafts or previous remote status<li> SnackBar appears: "Post will be published next time your device is online"</ul> | 
 Post List:<ul><li>Status message: "Post will be published next time your device is online"" <li>Cancel button is shown" </li> | 
 Cancellation<ul><li>Post stays in Drafts or previous remote status<li>SnackBar: "Changes will not be published"</ul> | 
 Published posts with confirmed changes are automatically uploaded. |  |
 Published posts with UN-confirmed changes are remote-auto-saved | 
 Cancelled posts are remote-auto-saved not auto-uploaded. | 
 It should be possible to revert a published post to a draft. | 
When a draft is uploaded, pressing on the notice's _Publish_ button should auto-upload the post as published | 
Tapping on _Publish_ in the Post List should auto-upload the post | 

### Additional scenarios

- A post with a failed media upload

## Plan

It looks like all parts have to be there in order to merge these to `develop`. We will create multiple PRs but target a master branch instead. 

Most of the work has been done by @diegoreymendez in PR #12178. We're going to take it apart into smaller chunks. And then we're going to need to test everything before merging to `develop`.

Targeting the `PUBLISHED` is deliberate to decrease the risks of regressions. If everything works great, we can apply the same to other statuses. 

## Known Tasks 

- [x] @shiki Update Post List to show failed published posts in Drafts. Done in #12252.
- [x] @shiki Auto-uploading PUBLISHED posts. Done in #12252.
- [ ] #12136 Safety for auto-uploading. 
- [x] @shiki Update Snackbar and Post List messages. Done in #12278. 
- [x] @shiki Modifies notice views so that they can show 2 line titles. This can probably be isolated. See #12178 for the code. Done in #12278. 
- [x] @shiki Modifies post cards so that they can show 2 line messages. This can probably be isolated. See #12178 for the code. Done in #12278. 
- [x] @shiki Cancellation flow #12317 
- [x] #12284 Bug: When exiting the editor after publishing, the Post List automatically shows the Published list instead of Drafts.
- [x] #12322 Automatically upload or remote auto-save published Posts that already exist in the remote. 
- [x] @shiki Review places where we set the `PostStatus` to `published`. Did we cover all of them? Do they affect the auto-uploading functionality?
- [x] Make sure all TODOs and stubs are done
- [x] Decide on what to do with Pages, e.g. #12280. Should we take it out of the scope? #12586

**Comment by shiki** [comment]
@osullivanchris I'm sorry if this has already been answered somewhere. For the requirement, "Post stays in drafts". If the post was **previously published**, should it still show in Drafts?

**Comment by osullivanchris** [comment]
@shiki no I think that would imply that it has been 'unpublished'. I'm not sure if we previously addressed it so its good to call out. I think it would be in published, and a message saying "Post will be updated next time your device is online" would make it clear what to expect. WDYT?

**Comment by shiki** [comment]
@osullivanchris That sounds great! Thank you.

**Comment by shiki** [comment]
Closing this since we're very close to finishing and we're now targeting #12227.
