### ISSUE TITLE
Dark Mode Master Issue

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#12320]
## Goals
- Add support for iOS 13's [dark mode](https://www.apple.com/ios/ios-13-preview/)

![dark-mode-i2](https://user-images.githubusercontent.com/517257/63059004-0dae8a80-bea3-11e9-8118-c7856b242dfa.png)

### Global

- [x] Add `XCODE11` build flag to support parallel development between Xcode 10 & 11 (#12120)
- [x] Create initial set of preview screenshots
- [x] First-pass at dark mode support on main tab bar screens
- [x] Dark mode versions for badged state of tab bar images
- [x] Fancy alerts have white backgrounds
- [x] Revisions section has white backgrounds
- [x] QuickStart has some white background
- [x] Add new site flow has some white background
- [ ] Update fancy button border style (https://github.com/wordpress-mobile/WordPress-iOS/issues/12320#issuecomment-527646730) #12592
- [x] Change `textPlaceholder` Muriel color to use `tertiaryLabel` on iOS 13.
- [x] Register domain has white backgrounds
- [x] Edit comment is white text on white background.
- [x] Pending comments have a white background.
- [x] Gravatar cropping screen has a white background

### Regressions

- [x] Reader tag area shows visible side gradients: https://github.com/wordpress-mobile/WordPress-iOS/issues/12457
- [x] Web preview has blue toolbar on iOS 12

### NUX
- [x] Dark mode for NUX
- [x] Login NUX button has black spinner while signing in
- [x] Header text on sign up bottom sheet isn't readable
- [x] Header and footer on signup epilogue are white and should be listForeground
- [ ] New account epilogue has a different color behind 'new account' which shouldn't be there https://github.com/wordpress-mobile/WordPress-iOS/issues/12593
- [ ] Modal HUD shown after hitting Continue on New Account screen should use system grey background. https://github.com/wordpress-mobile/WordPress-iOS/issues/12595
- [ ] Activity indicator on secondary NUX buttons appears white-on-white in light mode. [#140](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/140)

### Editor
- [x] Dark mode for editor 
- [x] Dark text on dark background in Aztec HTML mode
- [ ] Post Settings: Tags screen has white to the left and right of the tags field https://github.com/wordpress-mobile/WordPress-iOS/issues/12596
- [ ] Post Settings: After setting a featured image, tapping on the featured image (e.g. to remove it) shows a white background https://github.com/wordpress-mobile/WordPress-iOS/issues/12597
- [ ] Block editor: Bullet overlaps placeholder when adding a new list block (dark mode only) [#1391 Gutenberg](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1391)

### Stats
- [x] Some areas in Stats Insights still have white backgrounds
- [x] Dark countries map can be too dark to read

### My Sites
- [x] Posts cells (expanded view) have white backgrounds for some labels
- [x] Post / pages tab bar style should match Stats
- [x] Themes support icon isn't being tinted correctly
- [x] Ghost view in posts / pages has a white background
- [x] Activity logs (in help and support) have white text on white background
- [x] Plans are still light colored
- [x] Activity screen is still light colored
- [x] Reverse text and textSubtle colors in Activity Log list.
- [x] Remove divider below 'free plan' footer in Activity Log list
- [x] Plans list 'Best for...' text should use textSubtle
- [x] Menus: Down arrows and reorder handles should use `textTertiary` (via `textPlaceholder`?) Page icon beside 'new item' should use `listIcon` color.
- [x] Menus: When editing a menu name, use `tertiarySystemBackground` / `gray80` for the background color. Text should be `text` and X icon should be `listIcon`.
- [x] Sharing > Sharing Buttons / Manage > Edit sharing buttons – icons should use `listIcon`. "share this" and "official buttons" should use textSubtle.
- [ ] Posts list: After trashing a post, the "undo" cell has a white background https://github.com/wordpress-mobile/WordPress-iOS/issues/12598
- [ ] Settings: Time Zone & Tags screens have a white background when you pull to refresh https://github.com/wordpress-mobile/WordPress-iOS/issues/12599
- [ ] Settings: Pickers have white text on white background (Posts per page & Discussion settings: Close commenting, Paging, Links in comments) https://github.com/wordpress-mobile/WordPress-iOS/issues/12600

### Reader
- [ ] Tapping "Reply" on a reader comment shows a white background around the comment https://github.com/wordpress-mobile/WordPress-iOS/issues/12601
- [ ] Followed Sites: Tapping Manage and then back leaves the "Manage" cell highlighted (white background) https://github.com/wordpress-mobile/WordPress-iOS/issues/12602
- [ ] When liking a post, the star icon has a black background during the animation https://github.com/wordpress-mobile/WordPress-iOS/issues/12603

### Extensions
- [x] Update widget
- [x] Update share extension
- [x] Update notifications rich content extension

## V2
- [ ] Make tab bar translucent

**Switching between dark and light mode** #12441 
- [ ] Reader Detail
- [ ] Fancy button
- [ ] SearchBar strokes

## Notifications
- [x] Comment moderation has incorrect background on the comment cell, screenshot added to the thread.

## Analytics
There are no analytics events for this project.

## Related issues
This will finally close #6373 🎉

**Comment by mattmiklic** [comment]
Let's swap the gray being used for the bottom tab bar to the default system gray color used for tabs. I'm not sure if the color has a name but it's #757575 in dark mode, #999999 in light mode. That will make the tab bar match what's seen in the mockups above.

**Comment by frosty** [comment]
MeViewController outstanding:

- [ ] Post / pages tab bar style should match Stats
- [ ] Themes support icon isn't being tinted correctly
- [ ] Ghost view in posts / pages has a white background

**Comment by designsimply** [comment]
> Ghost view in posts / pages has a white background

Ghosts are the loading placeholders? Here's what I'm seeing (expanded and compact mode) and I think it's the ghost item that's already on the checklist:

<img src="https://user-images.githubusercontent.com/1119271/63977080-0c1ebe00-ca70-11e9-8f13-a50a15aadfd7.png" width="270" alt="wpios-13 2-beta-dark-mode-posts-list-loading-placeholders-are-light"> <img src="https://user-images.githubusercontent.com/1119271/63977071-07f2a080-ca70-11e9-9596-de29af7c4b2d.PNG" width="270" alt="IMG_2992"> 
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
Heading on the New Account screen seen during signup has a white background with very light gray text and the button at the bottom also has a light background:

<img src="https://user-images.githubusercontent.com/1119271/63977210-6a4ba100-ca70-11e9-96a5-bc6652af2afc.png" width="270" alt="new-account-email-unreadable-in-siwa-dark-mode-ios-13 1-beta1-wpios-13 2-beta1">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode—seen during Sign In With Apple testing.</sup>

**Comment by designsimply** [comment]
> Posts cells (expanded view) have white backgrounds for some labels

Spotted a couple examples of this: 
- Content shared from Bear
- Space after the date field (only for the Me filter, in the Everyone filter the author name is shown there instead)
- "Uploading post…" notice
- "Upload failed" notice


<img src="https://user-images.githubusercontent.com/1119271/63978239-25753980-ca73-11e9-91e5-14bb2c8c46fd.png" width="270" alt="wpios-13 2-beta-dark-mode-posts-list-me-filter"> <img src="https://user-images.githubusercontent.com/1119271/63978299-476ebc00-ca73-11e9-93e5-35a2a2d47363.png" width="270" alt="wpios-13 2-beta-dark-mode-uploading-post-notice-has-white-bg"> 
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
App logs are displayed with white text on a white background.

<img src="https://user-images.githubusercontent.com/1119271/63978464-a2a0ae80-ca73-11e9-9cf5-15644dda1655.png" width="270" alt="wpios-13 2-beta-dark-mode-white-text-on-white-bg-for-app-logs">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
Plans descriptions are still light colored.

<img src="https://user-images.githubusercontent.com/1119271/63978931-db8d5300-ca74-11e9-9eea-a9eb39be54c1.PNG" width="270" alt="IMG_2994">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
Activity screen is still light colored.

<img src="https://user-images.githubusercontent.com/1119271/63979474-33788980-ca76-11e9-99fa-5bcbfabd6f37.png" width="270" alt="wpios-13 2-beta-dark-mode-activity-screen-still-light"> <img src="https://user-images.githubusercontent.com/1119271/63979473-32dff300-ca76-11e9-9e12-76c8eb800b00.png" width="270" alt="wpios-13 2-beta-dark-mode-individual-activity-screen-still-light">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
The countries map in stats is too dark for me to read.

<img src="https://user-images.githubusercontent.com/1119271/63979654-a3870f80-ca76-11e9-8088-db49aff68c85.png" width="270" alt="wpios-13 2-beta-dark-mode-stats-countries-map-is-too-dark-to-be-readable">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
Terms of Service link on the "Sign up for WordPress.com" page is too dark to read.

<img src="https://user-images.githubusercontent.com/1119271/64007237-02797280-cad1-11e9-91e4-208d046cb3c2.PNG" width="270" alt="IMG_3005">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by designsimply** [comment]
Text is black with a black background in Aztec HTML Mode.

<img src="https://user-images.githubusercontent.com/1119271/64049282-8b27fb00-cb31-11e9-8edb-bc3cf8c7c5da.PNG" width="270" alt="IMG_3018">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1 in Dark Mode.</sup>

**Comment by mattmiklic** [comment]
Adding this here because I haven't seen it in GitHub and want to be sure it's being tracked. Here are the specs for the button changes (in Prologue, Fancy Dialogs) we should make alongside Dark Mode.

![buttons](https://user-images.githubusercontent.com/1396552/64209878-b4b58f00-ce6f-11e9-80ed-1f1b9ff8e152.png)

**Comment by frosty** [comment]
Thanks @mattmiklic - button colours should be updated already, it’s just the border style and possibly font choice we need to update now.

**Comment by iamthomasbishop** [comment]
Just noticed that the Post Titles on the Site Pages view are dim. I believe they should be white to match the Blog Posts view.

![IMG_0572](https://user-images.githubusercontent.com/1200432/64370639-7db4ba00-cfe4-11e9-9b2f-a92c3e64bd48.jpeg)

**Comment by mattmiklic** [comment]
Good catch @iamthomasbishop. The titles should use the `text` color and the dates should use `textSubtle`.

**Comment by mattmiklic** [comment]
I just noticed a few wrong background colors in Plugins:

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 12 13](https://user-images.githubusercontent.com/1396552/64372152-3af8df00-cff0-11e9-9646-a3ae5f958232.png)

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 13 03](https://user-images.githubusercontent.com/1396552/64372156-3d5b3900-cff0-11e9-9c42-ef4c53cdc928.png)

In this one, there's a black backgound behind the text that shouldn't be there:

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 13 10](https://user-images.githubusercontent.com/1396552/64372163-40562980-cff0-11e9-8bfa-db175d10fbe5.png)

**Comment by mattmiklic** [comment]
In the activity log, the `text` and `textSubtle` colors should be reversed. In this screenshot the "About / Local draft / Draft / Draft page" text should be `text` and the "Page draft modified" etc text should be `textSubtle`.

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 21 04](https://user-images.githubusercontent.com/1396552/64373951-c83c3380-cff0-11e9-958a-f3edc8721f5c.png)

**Comment by mattmiklic** [comment]
On the Plans screen, the "Best for..." text should use the `textSubtle` color.

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 24 12](https://user-images.githubusercontent.com/1396552/64374167-413b8b00-cff1-11e9-9b44-8013bda9d29b.png)

**Comment by mattmiklic** [comment]
According to the semantic color names spreadsheet, `textPlaceholder` uses muriel gray 30 on iOS 13. We should switch that to use the system `tertiaryLabel` color for iOS 13 as that's the color Apple says is intended for placeholders.

**Comment by mattmiklic** [comment]
On the Menus screen:

- The chevron-down icon and the icon that's used to drag and reorder items in the menu should both use the `textTertiary` color. The Page icon (beside "New item") and the pencil icon (beside "Default Menu") should use the `listIcon` color.

 ![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 27 35](https://user-images.githubusercontent.com/1396552/64374942-dab76c80-cff2-11e9-808c-b17dd5cc6439.png)

**Comment by mattmiklic** [comment]
Also in Menus, when editing a menu name in dark mode the background color is too light. For iOS 13 we should use `tertiarySystemBackground` and for iOS 12 and below we can use muriel Gray 80.

The text should be `text` color and the (X) icon should be `listIcon`.

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 27 16](https://user-images.githubusercontent.com/1396552/64375668-4cdc8100-cff4-11e9-9f3e-e0521e848497.png)

**Comment by danielebogo** [comment]
Thanks @mattmiklic for these feedback! I already fixed some (even the page in Pages @iamthomasbishop )

**Comment by mattmiklic** [comment]
Under Sharing > Sharing Buttons / Manage > Edit sharing buttons, the icons in the list should use `listIcon`.

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 50 14](https://user-images.githubusercontent.com/1396552/64375891-ef94ff80-cff4-11e9-9157-afc6dacaac95.png)

**Comment by mattmiklic** [comment]
Also in Menus, the "Share this" and "Official buttons" text should use whatever we're using elsewhere in this kind of view. I think it's `textSubtle` but am not sure.

![Simulator Screen Shot - iPhone Xs - 2019-09-05 at 15 51 11](https://user-images.githubusercontent.com/1396552/64375971-28cd6f80-cff5-11e9-94fe-fbd84e03e96d.png)

**Comment by mattmiklic** [comment]
This is testing 13.2.1.0 from Testflight:

On the New Account created screen, the background color behind the status bar is different from the color behind the rest of the page. The color behind the status bar is the one that's incorrect.

![IMG_1142](https://user-images.githubusercontent.com/1396552/64465818-9dc7a480-d0dc-11e9-998a-48e42e9530d7.PNG)

The modal progress indicator that appears after hitting Continue on the New Account screen looks off; this should use a regular material background but not sure if that is time consuming; maybe just using a system gray in the interim would help so it responds to dark mode.

![IMG_1143](https://user-images.githubusercontent.com/1396552/64465852-c059bd80-d0dc-11e9-964e-66827188fd7a.PNG)

There's a layout bug on Notifications the first time the screen is loaded. If the user hasn't already allowed notifications it causes the tab bar to be cut off.

![IMG_1146](https://user-images.githubusercontent.com/1396552/64465905-f1d28900-d0dc-11e9-8799-559ac54731a3.PNG)

If the user has dismissed the push notification prompt, there's just a bunch of extra space above the first notification in the list.

![IMG_8DEB8F00F29C-1](https://user-images.githubusercontent.com/1396552/64465965-33633400-d0dd-11e9-9adb-95461dbef1b3.jpeg)

This isn't specific to dark mode but it is new as of 13.2.

**Comment by frosty** [comment]
I've added all the open reports in here to the task list at the top of this issue.

**Comment by rachelmcr** [comment]
@frosty I've added the additional issues I saw to the task list (under My Sites, Editor, Reader). If anything is unclear please let me know and I can clarify with screenshots, etc.

**Comment by danielebogo** [comment]
Thanks @rachelmcr !

**Comment by elibud** [comment]
Comment moderation has incorrect background on the comment cell.

![File (2)](https://user-images.githubusercontent.com/5558824/65286464-10417700-db16-11e9-93ae-08eca9d963f6.jpg)

**Comment by melindahelt** [comment]
#2364138-zen

Reported: I have a bug in Wordpress iOS night mode. In my iOS 13.1 beta in paragraph and order text is white and background is white to! I hope you will update to fix this.

![B01502C2-20E9-4568-AD13-16A538B3264C_L0_001](https://user-images.githubusercontent.com/8306136/65355007-eee89580-dbbe-11e9-99b3-53ff9b19160b.png)
![D2BC9489-D2F7-43F2-9A8B-AAC6741EDCC3_L0_001](https://user-images.githubusercontent.com/8306136/65355008-eee89580-dbbe-11e9-8075-08b839dd7561.png)

**Comment by elibud** [comment]
Pinging @etoledom for that last one.

**Comment by iamthomasbishop** [comment]
@melindahelt @elibud that's on Aztec so I think @frosty might also be able to assist with that issue

**Comment by designsimply** [comment]
Profile > Help & Support > My Tickets screen is still light colored:

<img src="https://user-images.githubusercontent.com/1119271/65921511-a9d31900-e39f-11e9-8518-97cae36a6d2c.PNG" width="270" alt="IMG_3107">
<sup>Tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1 beta 4.</sup>

**Comment by etoledom** [comment]
> @melindahelt @elibud that's on Aztec so I think @frosty might also be able to assist with that issue

I can take it during the week unless someone is already taking care of it. @frosty, @danielebogo ?

**Comment by frosty** [comment]
This issue closed because tracking of these issues has now moved over to a Github Project: https://github.com/orgs/wordpress-mobile/projects/45
