### ISSUE TITLE
Groundskeeping Master Issue: Aug 26 - 30

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#12392]
These two are potentially related:
- [ ] Crash when updating or installing the version 13.0 on certain devices https://github.com/wordpress-mobile/WordPress-iOS/issues/12338
- [ ] Unresolved Core Data save error https://github.com/wordpress-mobile/WordPress-iOS/issues/12028

Reader related
- [x] WPTableViewHandler controllerDidChangeContent Crash  https://github.com/wordpress-mobile/WordPress-iOS/issues/11384
- [x] Fatal Exception: NSRangeException in WPRichContentView deinit https://github.com/wordpress-mobile/WordPress-iOS/issues/11398
- [x] ReaderPostServiceRemote fetchPostsFromEndpoint Crash  https://github.com/wordpress-mobile/WordPress-iOS/issues/11389

Performance
- [ ] Fetching posts blocks the main thread https://github.com/wordpress-mobile/WordPress-iOS/issues/12161

Review before closing: 
- [x] Editor: User can't upload media to Jetpack site, receives null API error response  https://github.com/wordpress-mobile/WordPress-iOS/issues/10949

Resolved with Jetpack sync improvements? 
- [x] Permanently deleted post is still displayed in the app https://github.com/wordpress-mobile/WordPress-iOS/issues/8459
- [x] User sees deleted comments in the app https://github.com/wordpress-mobile/WordPress-iOS/issues/9567

Duplicate Site Related PRs:
Bug 2 (1): https://github.com/wordpress-mobile/WordPress-iOS/pull/12412
Bug 3 (4): https://github.com/wordpress-mobile/WordPress-iOS/pull/12400
Bug 5 (7): https://github.com/wordpress-mobile/WordPress-iOS/pull/12409

**Comment by aerych** [comment]
I didn't quite get to #12161. 
#12338 and #12028 proved to be impossible for me to reproduce locally which pretty much nixed any chance of squashing them. I did spend some time reviewing the changes between 12.9 and 13.0 hoping to find something probative but no joy. :(
