### ISSUE TITLE
Groundskeeping (iOS) Master Issue : September 23–27

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#12538]
This is an umbrella issue for ad hoc tasks that I take on during my Groundskeeping rotation.

**(Groundskeeping) Project Issues**

- [x] #12520 Crash: threading violation on iOS 13 [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12537)
- [x] #11384 Fix Core Data threading issues [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12539)
- [ ] ~#12554 Crash when putting reader in the background~ Dupe of #12519, crash fixed in #12540. @danielebogo taking over fixing the remaining bug.
- [ ] #12338 Further investigate crash on launch. Added more details to the issue, and extra logging in #12569, but still don't know what the cause is or how to fix it.
- [ ] #7886 Duplicate entries. I think @aerych might have done already everything it could be done until we get more feedback from those changes, https://github.com/wordpress-mobile/WordPress-iOS/issues/7886#issuecomment-535975481.
