### ISSUE TITLE
Post Scheduling Enhancements Master Issue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#12686]
Expand options when creating a scheduled post ([#](https://wp.me/paCL20-ac-p2)).

- [ ] Add feature flag for local notification option.
- [ ] Add ability to set up local notification.
- [ ] Add feature flag for 'Add to calendar' option.
- [ ] Add ability to add to calendar.
- [ ] Ensure views are correct for Dark Mode.
- [ ] Add Accessibility support. (_Some work done in #12959_)
- [ ] Add Tracks.
- [ ] Enable feature flags for internal.
- [ ] Enable feature flags for all.
- [ ] Remove feature flags.

---
#### 14.0:
- [x] Post Scheduling: post date doesn't match messaging (#12992)
- [x] Post Scheduling: Calendar allows vertical scrolling while changing months (#13113)
- [x] Enable Feature Flag for Post Scheduling Calendar Picker (#13133)
- [x] Posts List uses device timezone while Post Settings uses site timezone (#13258)

#### 13.7:
- [x] Add feature flag for publish date/time. (https://github.com/wordpress-mobile/WordPress-iOS/pull/12820)
- [x] Add new 'Publish' flow to select publish date and time. (https://github.com/wordpress-mobile/WordPress-iOS/pull/12820)

---
![post_scheduling_ios](https://user-images.githubusercontent.com/1816888/66790758-6784fe00-eeae-11e9-8c8b-91bb84afb2dd.jpg)

**Comment by ScoutHarris** [comment]
@osullivanchris @frosty @bjtitus

It occurred to me that the three main parts of this project can stand alone as independent features:
- [ ] Add new 'Publish' flow to select publish date and time.
- [ ] Add ability to set up local notification.
- [ ] Add ability to add to calendar.

Is there any reason we can't feature flag them separately, so each can be released as they're complete (after the trial)?
- @bjtitus already added a `postScheduling` flag to show the new 'Publish' view with the date and time selectors.
- Another flag for the notification option.
- Another flag for the calendar option.

@bjtitus is making great progress, but just in case, I didn't see why any incomplete part(s) should hold up the others.

Thoughts?

**Comment by bjtitus** [comment]
I think that makes sense. The only thing that could be a blocker for notifications and calendar is the new screen. Right now the flag controls the screen appearing at all, so turning ok Notifications or Calendar Event would necessitate turning the new Publish flow on as well.

I could add the old date picker to the new screen and put the calendar behind the feature flag instead.

**Comment by frosty** [comment]
@ScoutHarris Thanks for raising that – I agree that these three parts could be released independently!

**Comment by osullivanchris** [comment]
Thumbs up from me as well. As @bjtitus mentioned there might be a little bit of double work if the calendar/notification are done first.

If that's true and I understand correctly " Add new 'Publish' flow to select publish date and time." is going to be done first anyway. So that might not matter.

So they can be 3 separate pieces I definitely agree, but item 2 and 3 might be dependent on releasing item 1.

**Comment by ScoutHarris** [comment]
> I could add the old date picker to the new screen and put the calendar behind the feature flag instead.

I don't think that's necessary. I was thinking what @osullivanchris said:

> " Add new 'Publish' flow to select publish date and time." is going to be done first anyway. So that might not matter.

I think it's ok to leave the current feature flag as-is (to show the 'Publish' view) and let notifications and calendar be dependent on that.

**Comment by kean** [comment]
Scheduling was re-implemented in 24.9 – closing as obsolete.
