### ISSUE TITLE
Stats Widgets Master Issue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#12702]
Add new Stats Widgets ([#](https://wp.me/paCL20-ee-p2)).

---
#### 14.2:
- [x] Stats: when viewed in a modal, there is a grey bar at the bottom of the view (#13301)
- [x] Update Tracks (#13272)
- [x] Stats Widgets: Update only if data has changed. (#13331)
- [x] Stats Widgets: show failed loading view (#13333)

#### 14.1:
- [x] Stats Widgets: reload table when stats are updated. (#13232)
- [x] Add new _Views This Week_ stat widget. (#13044)
- [x] Stats Widgets: fix site url UI issues (#13243)
- [x] Stats Widgets: localize display names (#13247)
- [x] Stats Widgets: clear stored data when site is changed (#13254)
- [x] Stats Widgets: show no connection view. (#13271)

#### 14.0:
- [x] Stats Widgets: incorrect stats displayed after modal dismissed (#13194)
- [x] Stats Widgets: Abbreviate large values (#13196)
- [x] Stats Widgets: update separator line color (#13207)
- [x] Stats: add accessibility label for abbreviated stats (#13214)

#### 13.9:
- [x] Change nav bar button from `Today` to `Widgets`. (included in #13036)
- [x] Add new _All Time_ stat widget. (#13030)

#### 13.7:
- [x] [Stats] Remove old WPKit stats code (#12848)
- [x] [Stats Refresh] Remove feature flag & legacy code (#10975)
- [x] Update Today widget to new design (#12849)

#### 13.6:
- [x] Update current Today widget to use new Stats. (#12756)
- [x] [Stats Refresh] Remove feature flag (#12771)
- [x] [Stats] remove old code from WPiOS (#12794)

---
![all_widgets_states_ios-2](https://user-images.githubusercontent.com/1816888/66867636-ef274700-ef58-11e9-9bb0-d2c9bd5736be.png)

**Comment by ScoutHarris** [comment]
Hey @osullivanchris .

Can we revisit the designs for these? Specifically, the grey background.

In iOS13, the widgets are even more transparent. Which makes the new grey background _very obvious_. 

<img width="400" alt="new_ios13_light" src="https://user-images.githubusercontent.com/1816888/68259735-e83fa180-fff7-11e9-8baa-1dadbfb6a274.png">

<img width="400" alt="new_ios13_dark" src="https://user-images.githubusercontent.com/1816888/68259736-e83fa180-fff7-11e9-91dd-1a0a9709be43.png">

The current stats widget has a transparent background, blending in nicely.

![current_ios13_light](https://user-images.githubusercontent.com/1816888/68259828-2c32a680-fff8-11e9-9fd0-056569d406da.jpeg)

![current_ios13_dark](https://user-images.githubusercontent.com/1816888/68259833-2f2d9700-fff8-11e9-8acc-37b3f54a50e3.jpeg)

I've not seen other widgets change their background color, and I haven't found a way to change the widget header background color (which is why it's still transparent).

Can we revert to using a transparent background?

**Comment by ScoutHarris** [comment]
Via Slack, @osullivanchris confirmed I misunderstood the design. It is meant to be transparent, it just looks grey in Zeplin.
