### ISSUE TITLE
Post Preview Enhancements Master Issue

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13197]
Master Thread: https://wp.me/paCL20-dF-p2
Design: https://wp.me/paCL20-aw

![device_previews_ios-1](https://user-images.githubusercontent.com/3250/71990909-794a1900-31f1-11ea-9a1d-cc315574888d.png)

- [x] Add feature flag. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13206)
- [x] Add new post preview UI.
  - [x] Replace UIWebView with WKWebView (existing: https://github.com/wordpress-mobile/WordPress-iOS/issues/13180) (https://github.com/wordpress-mobile/WordPress-iOS/pull/13206)
  - [x] Add new toolbar with controls. (#13245)
  - [x] Add Desktop / Mobile preview options (#13245)
- [x] Verify redirect behavior (`wpios_redirect` after logging in) matches previous implementation.
- [x] Ensure views are correct for Dark Mode.
- [x] Add Accessibility support. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13292)
- [x] Add Tracks. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13281)
- [x] Enable feature flag for all. (#13334)
- [x] Remove feature flag. (#13587)

**Comment by bjtitus** [comment]
Here's a summary explaining some of the [logging issues](https://github.com/wordpress-mobile/WordPress-iOS/pull/13226#pullrequestreview-342757084) @ScoutHarris noticed with some of these changes that have since been mitigated or are otherwise accounted for:

> 1. This appears in the console:

```
WordPress.PreviewWebKitViewController Error Loading [Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x600001e39e40>, NSErrorFailingURLStringKey=https://wordpress.com/?wpios_redirect=https://thescoutharris.wordpress.com/2019/12/17/comments-and-collatz-conundrum-2/, NSErrorFailingURLKey=https://wordpress.com/?wpios_redirect=https://thescoutharris.wordpress.com/2019/12/17/comments-and-collatz-conundrum-2/, NSLocalizedDescription=Frame load interrupted}]
```

This message should be mostly gone thanks to the [cookie fixes](https://github.com/wordpress-mobile/WordPress-iOS/pull/13236). The redirect was happening because no cookies were found to perform the authentication. This message would be expected any time we intercept a call to handle authentication, though and doesn't necessarily indicate anything is wrong.

> 2. I didn't see this in simulators, but on a real device there's a slew of these messages: [Process] kill() returned unexpected error 1

This is a WebKit bug which was supposed to be fixed back in September but seems to be unreleased on iOS:
https://bugs.webkit.org/show_bug.cgi?id=202173

There's another recent thread pointing to a fix Apple was preparing as of December 18, 2019:
https://forums.developer.apple.com/thread/126930
