### ISSUE TITLE
Release builds Master Issue

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#13470]
**Goal**: the goal of this project is to run beta and final release builds on CI with automatic upload to the stores.

**Steps**:
- [x] Update the release tooling to properly handle the release finalization -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13478.
- [x] Update the release tooling to create the GitHub release -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13503
- [x] Run the build for beta releases on CI. -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13658
- [x] Run the build for the final release on CI. -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13658
