### ISSUE TITLE
Tenor Implementation Master Issue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#13803]
Implement Tenor to replace Giphy for third-party gif import.

Refs:
- Giphy [removal PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/12769).
- Tenor [documentation](https://tenor.com/gifapi/documentation#quickstart).

Tasks:
- [x] Add Feature Flag. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13829)
- [x] Implement Tenor support.
  - [x] Tenor API credentials support (https://github.com/wordpress-mobile/WordPress-iOS/pull/13842)
  - [x] Implement Tenor client api (https://github.com/wordpress-mobile/WordPress-iOS/pull/13843)
  - [x] Tenor picker (https://github.com/wordpress-mobile/WordPress-iOS/pull/13861)
- [x] Add Tenor to Media Library options. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13907)
- [x] Add Tenor to Aztec editor media options. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13908)
- [x] Add Tenor to block editor media options. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13910)
- [x] Add accessibility support. (no changes required)
- [x] Add Tracks. [Related P2](https://iosp2.wordpress.com/2020/03/16/adding-tracks-forget-wordpress-shared/) on the new way of doing this. (https://github.com/wordpress-mobile/WordPress-iOS/pull/13923)
- [x] Animating GIFs in Tenor Picker (https://github.com/wordpress-mobile/WordPress-iOS/pull/13941)
- [x] Enable feature, add to release notes. (https://github.com/wordpress-mobile/WordPress-iOS/pull/14297) (Released in 15.1)
- [x] Mobile Guild P2 post. (https://wp.me/p7cLQ7-Ze)
- [x] Remove any remaining Giphy support/files. (https://github.com/wordpress-mobile/WordPress-iOS/pull/14302)
- [ ] Remove Feature Flag.

**Comment by frosty** [comment]
Some remaining issues I observed while testing the main PR:

* Issue in the block editor where I saw search results appear briefly and then vanish. For some reason it happens for me every time with the search term 'blathers'.
* There's no animation or indication of a gif in the block editor – the classic editor shows a GIF badge in the top left of an image.
* Editing an image of course breaks the gif and turns it into a static image (it actually didn't even correctly replace the image for me in the classic editor when I tested it). I think we should probably disable image editing for gifs, or at the very least show a prompt when tapped saying that the image won't be animated any more.
  * We need to update to use the new media picker cell overlay `prepareForReuse` functionality to clear out the overlay contents between each use.

**Comment by ScoutHarris** [comment]
Hey @frosty . Regarding this issue:

> There's no animation or indication of a gif in the block editor

I'm seeing the GIFs animate in the block editor. Is there a step I'm missing or something? I simply started a new post with the block editor and added a gif to an image block.

![block_editor](https://user-images.githubusercontent.com/1816888/84083561-20003480-a99f-11ea-8998-66479163bcc0.gif)

**Comment by ScoutHarris** [comment]
Hey @frosty .

> We need to update to use the new media picker cell overlay prepareForReuse functionality to clear out the overlay contents between each use.

I'm not quite getting this one. Can you elaborate please?

**Comment by frosty** [comment]
> I'm seeing the GIFs animate in the block editor.

Interesting! I just followed the same steps as you, but it doesn't animate 🤔 I've tried it with several, with the latest `develop` build, and they're all just static.

**Comment by frosty** [comment]
> I'm not quite getting this one. Can you elaborate please?

@SergioEstevao recently added a `prepareForReuse` method to `ReusableOverlayView`: https://github.com/wordpress-mobile/MediaPicker-iOS/pull/351/files

We should implement that in `TenorPicker.swift` to clear out the overlay views (`CachedAnimatedImageView`) before they're reused, to ensure they don't show old content.
