### ISSUE TITLE
Homepage Settings Master Issue

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#14167]
Implement a settings screen to allow the user to configure their Homepage settings via the app. This will currently only support WordPress.com and Jetpack websites, due to limitations in the XMLRPC API.

![blueprint_ios](https://user-images.githubusercontent.com/4780/82658550-15b00d80-9c1f-11ea-8edf-e4825e8d3c89.png)

- [x] Add a new row to the Site Settings screen, showing the value of the current setting. This should only be visible for wpcom and Jetpack sites, and only to admin users.
- [x] Add a new Homepage Settings view controller, which includes:
- [x] Rows to toggle between posts and page homepage types
- [x] When page homepage type is selected, shows rows which display the current Home and Posts page selections.
- [x] When those rows are tapped, show a list of all pages and allow the user to select which one should be used for the Home / Posts page.
- [x] Also requires integration with the wpcom `/sites/:/homepage` endpoint to set these values.

**Comment by jkmassel** [comment]
Howdy friends – we're freezing `15.0` today, so I'm bumping this PR forward to `15.1`. If it needs to land in the `15.0` series, please merge it to `release/15.0` and DM me – I'll be happy to create a new beta release!

**Comment by frosty** [comment]
@jkmassel All of the PRs for this issue were merged in time for 15.0, but we neglected to update the issue itself. I switched the milestone back and I'm marking as closed.

**Comment by ceyhun** [comment]
> This will currently only support WordPress.com and Jetpack websites, due to limitations in the XMLRPC API.

Hey there @bjtitus @frosty 👋 Do you think it will ever be possible to add Homepage settings to non-jetpack self-hosted sites somehow?

cc @chipsnyder
