### ISSUE TITLE
Reader Improvements: Phase 2 - Project Issue

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#14395]
This is the main project issue for Phase 2 of the Reader Improvements Project

### Tasks
- [x] Create a feature flag for the project: https://github.com/wordpress-mobile/WordPress-iOS/pull/14406
- [x] Add a new Select Interests screen: https://github.com/wordpress-mobile/WordPress-iOS/issues/14396
- [x] ~Add a new loading view that is displayed to the user while the posts are loading:~ N/A this is being done in https://github.com/wordpress-mobile/WordPress-iOS/issues/14396
- [x] Add a new Discover feed that displays a list of posts for the selected interests: https://github.com/wordpress-mobile/WordPress-iOS/issues/14399
- [x] Update Reader Card to display a list of recommended interests: #14500
- [x] Update Reader Card to display a list of tags for the posts in the Discover feed: https://github.com/wordpress-mobile/WordPress-iOS/pull/14645
- [x] Final Design Review: https://github.com/wordpress-mobile/WordPress-iOS/issues/14745
