### ISSUE TITLE
Reader Improvements: Display posts by interests — Main Issue

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#14399]
Parent Issue: #14395

<img width="597" alt="Screen Shot 2020-06-30 at 10 09 43" src="https://user-images.githubusercontent.com/7040243/86129969-db594c00-bab9-11ea-882b-e46acb6f5729.png">

### Goal

Based on the Interests the user has selected from #14396 present them as specified in the image above.

# Tasks

* [x] Extract model logics from `ReaderPostServiceRemote` — https://github.com/wordpress-mobile/WordPressKit-iOS/pull/255
* [x] Map the Cards API response to a plain object — https://github.com/wordpress-mobile/WordPressKit-iOS/pull/256
* [x] Extract ReaderPost logic to the model — https://github.com/wordpress-mobile/WordPress-iOS/pull/14421
* [x] Connect the call with the WPiOS — https://github.com/wordpress-mobile/WordPress-iOS/pull/14438
* [x] Persist and present the returned data — https://github.com/wordpress-mobile/WordPress-iOS/pull/14462
* [x] Add welcome banner — https://github.com/wordpress-mobile/WordPress-iOS/pull/14467
* [x] Ghost cells (when loading) — https://github.com/wordpress-mobile/WordPress-iOS/pull/14485
* [x] Retrieve the selected interests and give it to the API — https://github.com/wordpress-mobile/WordPress-iOS/pull/14486
* [x] Check performance — probably fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/14532
* [x] Integration with the real API — https://github.com/wordpress-mobile/WordPress-iOS/pull/14532
* [x] Do small refactorings after #14487 is merged
* [x] Check to make sure quick start is working correctly: https://github.com/wordpress-mobile/WordPress-iOS/pull/14642
