### ISSUE TITLE
Implement click tracking for Google unified Sign In. 

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#14592]
Ref: pbArwn-I6-p2

Implement click trackign for Google unified Sign In.

## Relevant events:

- [x] signup_with_google
- [x] login_with_google
- [x] submit
- [x] continue
- [x] dismiss
- [x] terms_of_service_clicked
- [x] show_help
- [x] forgotten_password
- [x] send_code_with_text
- [x] submit_2fa_code
- [x] create_new_site
- [x] create_account – when the user clicks on “Create account” on the signup confirmation screen
- [x] add_self_hosted_site
- [x] connect_site
- [x] select_avatar
- [x] edit_username
