### ISSUE TITLE
Reader P2 follow conversations: hook up subscription endpoints

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#14624]
### Parent Issue
https://github.com/wordpress-mobile/WordPress-iOS/issues/14574

### Tasks
- [x] Call the [get the current subscription state](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post/subscribers/mine/) endpoint and update the follow/following conversation button to reflect the current state.
- [x] Tapping on the button toggles between `Follow conversation` and `Following conversation`.
- [x] When following a conversation, call the [subscribe to a post comments stream](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post/subscribers/new/) endpoint. 
- [x] Similarly, when unfollowing a conversation, call the [unsubscribe from comments stream](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post/subscribers/mine/delete/) endpoint.
