### ISSUE TITLE
Reader Improvements: Phase 3 - Project Issue

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#14768]
This is the main project issue for Phase 3 of the Reader Improvements Project:

### Deferred
- [x] Discover: Sorting Posts: https://github.com/wordpress-mobile/WordPress-iOS/issues/14765

### Done
- [x] Sites/Blogs you might like: https://github.com/wordpress-mobile/WordPress-iOS/issues/14766
- [x] Remove Feature Flag: https://github.com/wordpress-mobile/WordPress-iOS/pull/14842
- [x] Change copy from "tags" to "topics" on the manage screen: https://github.com/wordpress-mobile/WordPress-iOS/issues/14837
- [x] Change copy from "tags" to "topics" on Add Tag screen: https://github.com/wordpress-mobile/WordPress-iOS/issues/14838
- [x] Request bigger size for site icon in Reader Site Header: [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/15045) - [Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/14856)
- [x] Reader Detail Updates: https://github.com/wordpress-mobile/WordPress-iOS/issues/14767
- [x] Reader Detail Design Review: https://github.com/wordpress-mobile/WordPress-iOS/issues/15052
- [x] Move settings icon from following tab to reader app nav bar: https://github.com/wordpress-mobile/WordPress-iOS/issues/14835
