### ISSUE TITLE
Big Titles, White Headers Project Issue

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#14774]
This is the main project issue for "Big Titles, White Headers". The goal of this project is to switch the navigation bars to use system materials, serif fonts for titles, and large titles for key sections:

![big-titles-white-headers-ios](https://user-images.githubusercontent.com/4780/91452761-dffe6e80-e876-11ea-93fb-461972308f80.png)

- [x] Add feature flag (currently disabled) for the feature (#14797)
- [x] Don't apply current navigation bar background styling when feature flag is active (#14797)
- [x] Use system serif font for navigation bar titles (#14803)
- [ ] Use large title style for top level of My Site, Reader, and Notifications
- [ ] Integrate search bars with navigation bars (this may need to be split out into its own issue)
- [ ] When top tab bars or search bars are present, divider should appear below them
- [ ] Adopt new style site switcher (again, this will probably be a separate issue)
- [ ] Fix status bar color in theme browser and close this [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/15714) 
- [x] Ensure Media Picker has correct appearance
- [x] Ensure editor has correct appearance
- [ ] Ensure Theme picker webview nav bar and titles look as expected 
- [ ] Ensure All web views look as expected
