### ISSUE TITLE
Prologue Carousel - Project Issue

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15056]
A project ticket to track prologue carousel changes. 
Authenticator project ticket: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/494
Feature branch: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/tree/feature/unified-prologue-carousel

### Tasks
- [ ] Remove feature flag
- [x] Remove Lottie

### In Progress
- [ ] Implement parallaxed background
- [ ] Scale text depending on device size

### Done
- [x] Create feature flag #15062
- [x] Update headlines #15064 
- [x] Extend background behind the button view #15073
- [x] Move carousel dots to the bottom of the container
- [x] Add placeholder views for each slide, and reposition header text
- [x] Create individual views for each slide, use real text that can be localized instead of images as text
- [x] Check dark mode support
- [x] Check iPad support

### Designs
![i5-ios-1](https://user-images.githubusercontent.com/1062444/95364944-14624300-0897-11eb-844e-aa5f2dc63401.png)
![i5-ios-dark](https://user-images.githubusercontent.com/1062444/95364953-175d3380-0897-11eb-9247-7d311e9ff3f1.png)

**Comment by kean** [comment]
This screen was removed during the Jetpack migration but is now making a comeback on iPad:

<img width="800" alt="Screenshot 2024-09-11 at 2 16 56 PM" src="https://github.com/user-attachments/assets/5424c912-b112-4b4a-9e5c-00455d58a48b">
