### ISSUE TITLE
Jetpack Section: Scan

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#15190]
Project: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193

Add ability to start scans, see status, and manage threats. 

<img width="1785" alt="Screen Shot 2020-10-29 at 4 48 36 PM" src="https://user-images.githubusercontent.com/793774/97630930-7a9d3a00-19ed-11eb-85e7-86bd7df7acb5.png">

#### Network
- [x] Create a new remote service for the scanning APIs: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Start a new scan: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Get the scanning status: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Get the scan results: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Get the scan history: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Fix / Ignore Threats: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Create model for Threat: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Create model for Scan Status: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
 
#### My Site View
- [x] Update with approved editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193
- [x] Add logic to determine if the site has access to scanning: https://github.com/wordpress-mobile/WordPress-iOS/pull/15427
- [x] Add a new menu item for scan: https://github.com/wordpress-mobile/WordPress-iOS/pull/15427
- [x] Add action to push to the new Scan view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
 
#### Scan View
- [x] Update with approved editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193
- [x] Create new view controller: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Add Ghost cells to display while loading the data from the network: https://github.com/wordpress-mobile/WordPress-iOS/pull/15726
- [x] Pull current scan status from the network: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
 
#### Style the Scanning State view
- [x] Pull status from scan API every X seconds: https://github.com/wordpress-mobile/WordPress-iOS/pull/15641
- [x] Display progress bar for current status: https://github.com/wordpress-mobile/WordPress-iOS/pull/15641
- [x] When scan completes switch to current state view below: https://github.com/wordpress-mobile/WordPress-iOS/pull/15641
 
#### Style No Threats State View
- [x] Update with approved editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193
- [x] Add button for manual scan: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Add action to call scan start API: https://github.com/wordpress-mobile/WordPress-iOS/pull/15641
- [x] Switch to scanning state view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Style Threat Detected State View: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Style Threat Detected View: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Show / Hide the fix all button: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Call the Fix API call: https://github.com/wordpress-mobile/WordPress-iOS/pull/15661
- [x] Add button for manual scan: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Add action to call scan start API: https://github.com/wordpress-mobile/WordPress-iOS/pull/15641
- [x] Switch to scanning state view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15606
- [x] Style the threat table cell: https://github.com/wordpress-mobile/WordPress-iOS/pull/15677
- [x] Add action to push to threat details view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15720
 
#### Threat List View
- [x] Add sections for sorting by date: https://github.com/wordpress-mobile/WordPress-iOS/pull/15773

#### Threat Details View
- [x] Update with approved editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193
- [x] Display warning prior to fixing/ignoring a threat https://github.com/wordpress-mobile/WordPress-iOS/pull/15740
- [x] Add API calls to change the state of the threat https://github.com/wordpress-mobile/WordPress-iOS/pull/15740
- [x] Update UI to reflect new state after fixing/ignoring a threat: https://github.com/wordpress-mobile/WordPress-iOS/pull/15780
- [x] Style the view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15720
- [x] Add logic to determine if we can fix a threat: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/304
- [x] Add buttons to fix / ignore threat: https://github.com/wordpress-mobile/WordPress-iOS/pull/15720
 
#### History List View
- [x] Update with approved editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193
- [x] Add action to push to threat details view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15781
- [x] Add filter tab bar: https://github.com/wordpress-mobile/WordPress-iOS/pull/15696
- [x] ~Pull paginated threat history from API for selected filter~ API doesn't support it
- [x] ~Add table pagination~
- [x] Parse API data into sections based on date: https://github.com/wordpress-mobile/WordPress-iOS/pull/15696
 
#### Notifications Tab
- [x] Update with approved editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15193
- [x] Override the existing views in notifications tab to deep link to the threat details view: https://github.com/wordpress-mobile/WordPress-iOS/pull/15779
 
#### Tracks
- [x] Add tracking: https://github.com/wordpress-mobile/WordPress-iOS/pull/15788 and https://github.com/wordpress-mobile/WordPress-iOS/pull/15792

#### Finishing Touches
- [x] Check dark mode
- [x] Check Accessibility: https://github.com/wordpress-mobile/WordPress-iOS/pull/15816
- [x] Check iPad: https://github.com/wordpress-mobile/WordPress-iOS/pull/15798
- [x] Check Small Devices
- [x] Check RTL languages: https://github.com/wordpress-mobile/WordPress-iOS/pull/15810
- [x] Design Review

**Comment by emilylaguna** [comment]
Closing as this as all the tasks are complete and this will be released in the next version: https://github.com/wordpress-mobile/WordPress-iOS/pull/15813
