### ISSUE TITLE
Jetpack Section: Project Issue

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#15193]
This is the main project issue for the Jetpack Section project

### Tasks
- [x] Jetpack My Site Menu Improvements: https://github.com/wordpress-mobile/WordPress-iOS/issues/15275
- [x] Activity Log Filters: https://github.com/wordpress-mobile/WordPress-iOS/issues/15192
- [x] Download Backup/Restore: https://github.com/wordpress-mobile/WordPress-iOS/issues/15191
- [x] Scan: https://github.com/wordpress-mobile/WordPress-iOS/issues/15190
- [x] Update with latest editorial text: https://github.com/wordpress-mobile/WordPress-iOS/issues/15741
- [x] Final Design Review

### Deferred Tasks
- [ ] ~Server Credentials: https://github.com/wordpress-mobile/WordPress-iOS/issues/15505~

**Comment by emilylaguna** [comment]
Closing as this as all the tasks are complete and this will be released in the next version: https://github.com/wordpress-mobile/WordPress-iOS/pull/15813
