### ISSUE TITLE
Jetpack Section: My Site Menu Improvements

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#15275]
Project: #15193

### Tasks
- [x] Add a new value to `BlogDetailsSectionCategory` enum
- [x] Create a new `BlogDetailsSection` object for the Jetpack section grouping
- [x] Create a new `BlogDetailsRow` object for the new Jetpack `Settings` action
- [x] Add action to the row that creates and pushes to a new settings screen with 2 rows : Security and Manage connection 
- [x] Check if this change effects Quick Start
- [x] Add tracking event for Jetpack settings
