### ISSUE TITLE
Reader: Mark posts as seen / unseen

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15355]
As a user on mobile, I would like the app to mark a post as seen when I visit it in Reader. I would also like to mark a post as seen / unseen at will, in the "more" menu.

Calypso alignment: Do not release until 16.4 or later.

Tasks:
- [x] Add ability to mark posts seen/unseen. [wordpress-mobile/WordPressKit-iOS/pull/327, wordpress-mobile/WordPressKit-iOS/pull/336, wordpress-mobile/WordPressKit-iOS/pull/341]
- [x] Add seen/unseen menu option.
  - [x] Post details. [#15638, #15718, #15745]
  - [x] Reader card. [#15645, #15718, #15745]
- [x] ~~Only [posts from followed feeds](https://github.com/Automattic/wp-calypso/pull/49028) should have the mark as seen option. [#15670]~~ (negated by #15745)
- [x] Mark post as seen when viewed in the Reader. [#15676, #15718]
- [x] Add Tracks. [#15671]
- [x] Error handling. [#15681]
- [x] Enable `unseenPosts` feature flag. [#15753]

---
Example from the web:

<img width="667" alt="Screen Shot 2020-11-20 at 9 03 16 AM" src="https://user-images.githubusercontent.com/1062444/99815358-c8e6ba00-2b0f-11eb-8a9a-97a1af6e83cd.png">

More menu in Reader > post:

<a href="https://user-images.githubusercontent.com/1062444/99820186-08b0a000-2b16-11eb-990e-da56a412ed90.PNG"><img src="https://user-images.githubusercontent.com/1062444/99820186-08b0a000-2b16-11eb-990e-da56a412ed90.PNG" width="350" /></a>

Design:

<img width="1237" alt="Screen Shot 2021-01-12 at 3 40 50 PM" src="https://user-images.githubusercontent.com/1816888/104383173-a5773480-54ec-11eb-9dbc-b37a9fdd5c24.png">

**Comment by ScoutHarris** [comment]
From Slack convo: Mark Seen/Unseen -> works as described in [this](https://wp.me/pbArwn-ZE-p2#comment-1910) comment.
