### ISSUE TITLE
P2: Add invite links

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15356]
Ref. pbArwn-1uy-p2

As a P2 user, I want the ability to invite others to my P2. 

**Accessibility notes**
Don't forget to test the textfields with VoiceOver enabled. Placeholder text can sometimes cause issues with VO.

(Include People Management refactor here.)

### Tasks

Changes to current view:
- [x] View title: change to 'Invite People'. [PR  #15512]
- [x] Role: Add 'Learn more about roles' link to show https://wordpress.com/support/user-roles/. [PR #15530]
- [x] Message: Add placeholder text to message field. [PR  #15512]
- [x] Message: Change helper text for message field. [PR  #15512]
- [x] Message: Limit message to 500 characters. [PR #15538]
- [x] Message: make field scrollable (to fix #10795).
- [x] Improve VoiceOver.
- [x] Update to use dynamic text.

New 'Invite Link' section:
- [x] 'Generate new link' row.
- [x] 'Share invite link' row.
- [x] 'Role' selector.
- [x] 'Expires on' row.
- [x] 'Disable invite link' row.
- [x] Helper text at the bottom.
- [x] Tracks.
- [x] Accessibility.
- [x] Mobile Guild post. (p7cLQ7-1oZ-p2)

### Rest API endpoints

Invite Link Generation endpoints are publicly available (but not documented)

**Fetch all invites:**
- `GET` v1/sites/$site/invites

**Automatically generate a set of links if none are found:**
- `POST` wpcom/v2/sites/$site/invites/links/generate

**And for deleting:**
- `POST` wpcom/v2/sites/$site/invites/links/disable

### Mobile designs
![invite-links-ios](https://user-images.githubusercontent.com/1062444/102109951-38dc1d80-3dfa-11eb-8db0-486f6e636dfc.png)

### On the web
<img width="394" alt="Screen Shot 2020-11-20 at 9 55 36 AM" src="https://user-images.githubusercontent.com/1062444/99820757-d2bfeb80-2b16-11eb-93f1-a5c3d0ee3f1e.png">

<img width="736" alt="Screen Shot 2020-11-20 at 9 55 20 AM" src="https://user-images.githubusercontent.com/1062444/99820772-d81d3600-2b16-11eb-8a86-a7ed8a7dc9ce.png">

**Comment by ScoutHarris** [comment]
Just leaving this here as something to consider. 

#10795 - Invite people: message field doesn't show entire message

Maybe we can address that with the refactor.
