### ISSUE TITLE
Add a subscription_count property to the reader_* events

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#15431]
We'd like to be able to slice the Reader usage by how many sites the user follows. 
[equivalent PR on Calypso ](https://github.com/Automattic/wp-calypso/pull/47818)

## Todo
- [x] add new tracking method to include `subcription_count` for `reader_*` events/stats (https://github.com/wordpress-mobile/WordPress-iOS/pull/15444)
- [x] migrate `reader_*` events (https://github.com/wordpress-mobile/WordPress-iOS/pull/15471)
- [x] migrate `reader_*` stats (https://github.com/wordpress-mobile/WordPress-iOS/pull/15472)

**Comment by momo-ozawa** [comment]
Closed this by accident.
Note that https://github.com/wordpress-mobile/WordPress-iOS/pull/15444 only partially fixes this issue.
