### ISSUE TITLE
Like notifications: show all likes when notification tapped

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15662]
When tapping a Like notification, the app currently show a max of 10 users. Let's show them all.

---
Tasks:
- [x] Add feature flag (`newLikeNotifications`). [#16007]
- [x] Add endpoint support to fetch all post likes. [wordpress-mobile/WordPressKit-iOS/pull/347]
- [x] Add endpoint support to fetch all comment likes. [wordpress-mobile/WordPressKit-iOS/pull/351]
- [x] Add service support to fetch post likes. [#15977]
- [x] Add service support to fetch comment likes. [#15994]
- [x] Show all likes for posts. [#16007]
- [x] Show all likes for comments. [#16007]
- [x] Update WPKit to use v1.2 endpoints to get `preferred_blog`. [#16353, wordpress-mobile/WordPressKit-iOS/pull/389]
- [x] Store like information in Core Data. [#16361, #16383, #16394, #16398, #16399, #16409]
- [x] Update likes list and user profile sheet to use info from Core Data. [#16410]
- [x] Order the likes list newest to oldest. [#16409]
- [x] ~~Show liker's blog title if available, and display blog when cell tapped.~~ (Ref: wordpress-mobile/WordPressKit-iOS/pull/361) (Replaced by #16249)
- [x] Show error when fetching fails. [#16495]
- [x] Add/verify Tracks. [#16327, #16452]

---
The current view:

![limited_likes](https://user-images.githubusercontent.com/1816888/104964778-5cb2f600-599a-11eb-95db-f279ecc1abcf.png)

---
Endpoints:

Currently, we are using the `/notifications` endpoint to get Notifications. Each notification contains a `body` property that contains the content displayed in notification details. This content is limited. To get full lists, we'll probably need to refactor the notification details to use these endpoints:

- Get likes for a post: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post_ID/likes/
- Get likes for a comment: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/%24comment_ID/likes/

These endpoints are not implemented, so they'll need to be added to https://github.com/wordpress-mobile/WordPressKit-iOS.
