### ISSUE TITLE
Reader: align options menus on post card and post details

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15761]
Currently, the options menu on the Reader post cards and in post details are created and handled separately, with much of the code being duplicated, but also not quite the same. This has led to:
- Options being different
- Success messages being different
- Error messages being different

We should align the two so that they use the same code and have the same functionality.

- [x] Show both menus using the same code. [#15778]
- [x] Both menus have the same options. [#15778]
- [x] Verify both menus use the same code for all actions.
- [x] Show success messages for all applicable actions.
  - [x] Follow/unfollow a site. [#15784, #15786, #15800, #15819]
  - [x] Mark as seen/unseen. [#15793]
  - [x] Turn on/off notifications. [#15796]
  - [x] Block site [#15846]
- [x] Show error messages for all applicable actions.
  - [x]  Follow/unfollow a site. [#15800]
  - [x] Turn on/off notifications. [#15796]
  - [x] Block site [#15846]
- [x] Update Discover stream when site is blocked from Discover > post details. [#15845]
- [x] Dismiss post details when site is blocked. [#15845]
- [x] Remove `ReaderPostMenu.swift`. [#15892]

| Post Card | Post Details |
|--------|-------|
| ![card](https://user-images.githubusercontent.com/1816888/106651738-ceba3c00-6551-11eb-9396-a7302b27e184.png) | ![details](https://user-images.githubusercontent.com/1816888/106651793-dd085800-6551-11eb-8817-a3ee81b7fd71.png) |
