### ISSUE TITLE
Comments: filter by status

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15955]
Add the ability to filter Comments by status.

Tasks:
- [x] Add `FilterTabBar` to `CommentsViewController`. [#15966]
- [x] Fetch comments for each filter. [wordpress-mobile/WordPressKit-iOS/pull/357, #15972]
- [x] Update UI to display all Comments correctly for each filter. [ #15998]
- [x] Add state restoration. [#16001]
- [x] Show offline NRV. [#16105]
- [x] Save selected filter. [#16108]
- [x] Track filter selection. [#16108]
- [x] Enable feature flag, add release note. [#16130]

Design: (V1 pbArwn-1EF)

![comment_enhancements](https://user-images.githubusercontent.com/1816888/108762951-f7f53900-750d-11eb-9e2b-a55e494f9869.png)
