### ISSUE TITLE
Jetpack App (Emphasis)

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#16338]
## Description
This is the parent issue for Emphasis, the second phase of the Jetpack App project.

## Project References
- Jetpack App i5: Emphasis (pcdRpT-iP-p2)
- Jetpack App i5 final wrap up comment (pcdRpT-iP-p2#comment-311)
- Removing Quick Actions (p1619069690172700-slack-C0180B5PRJ4)
- Keeping the Jetpack section header (https://github.com/wordpress-mobile/WordPress-iOS/pull/16363#pullrequestreview-643098727)

## Tasks
- [x] Hide Reader (PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16339)
- [x] Remove FAB from My Site (PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16340)
- [x] Remove Quick Actions (PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16363)
- [x] ~Remove Jetpack list heading (PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16346)~ 
- [x] Update Notification Settings (PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16559)
- [x] Update App Store screenshots (Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/16395)
- [x] Update App Store description, including Editorial and i18n
