### ISSUE TITLE
Create new {{fnow}} custom extension to handle locale agonstic dates in UI tests

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#16660]
## Description

Extend WireMock to to handle locale agonstic dates in UI tests by adding a custom `{{fnow}}` tag

## Context

We previously had issues with dates being localized by the `{{now}}` tag. On Android, this was resolved by introducing a custom `{{fnow}}` tag. We should also handle this on iOS by adding a custom `{{fnow}}` tag in WordPressMocks.

Discussion: https://github.com/wordpress-mobile/WordPressMocks/pull/31#discussion_r645485210
> I think you should use our custom `{{fnow}}` tag instead of `{{now}}` to avoid the issues we had in the past with dates being localized by the now tag – see pbMoDN-13F-p2 and wordpress-mobile/WordPress-Android#12831

## Tasks
 
- [ ] Add a new `UnlocalizedDateHelper.java` file  in `src/main/java/org/wordpress/ios/mocks` and copy the code from [here](https://github.com/AliSoftware/WordPress-Android/blob/5449f314d077dc43dc4eb78dd1eb9e3ad61eae47/WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java#L110-L173)
- [ ] Register the custom extension in [scripts/start.sh](https://github.com/wordpress-mobile/WordPressMocks/blob/97068093636de1fe6b8378c5b64640806c591da8/scripts/start.sh#L20-L23) by specifiying `--extensions org.wordpress.ios.mocks.UnlocalizedDateHelper` (Ref: http://wiremock.org/docs/running-standalone/)
- [ ] Replace existing `{{now}}` tags with the locale agnostic `{{fnow}}` tag

**Comment by AliSoftware** [comment]
It would be rad if, as part of working on this, we could also introduce linting of the mocks to ensure there are no accidental usage of `{{now …}}` anymore once `{{fnow …}}` becomes available.

One simple way to do that would be to leverage the linting we already do via the `lint` rake task [here](https://github.com/wordpress-mobile/WordPressMocks/blob/develop/rakefile#L36-L37), adapting the lint code to scan for `{{now` or `{{ now` too. Since [we already have logic to scan the files for accidental use of hardcoded `public-api` base url](https://github.com/wordpress-mobile/WordPressMocks/blob/develop/rakefile#L55-L57), we could probably adjust those lines to also scan for `{{now` with something like this (not tested, only to give the general idea, will probably requires some testing and adjustments to make it work):

```diff
- if File.open(file).each_line.any?{ |line| line.include?('public-api.wordpress.com') }
- 	append_error(file, file_errors, "Contains references to `https://public-api.wordpress.com`. Replace them with `{{request.requestLine.baseUrl}}`.")
- end
+ (api_used, now_used) = File.each_line(file).reduce([false, false]) do |(api, now), line|
+   [api || line.include?('public-api.wordpress.com'), now || line ~= /{{ *now/]
+ end
+ append_error(file, file_errors, "Contains references to `https://public-api.wordpress.com`. Replace them with `{{request.requestLine.baseUrl}}`.") if api_used
+ append_error(file, file_errors, "Contains usage of `{{now …}}`. Replace them with `{{fnow …}}` so that the generated date is locale-agnostic.") if now_used
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jkmassel** [comment]
We're not going to further invest in wiremock, instead we'll use object-level mocks like Woo does. wprs makes this pretty easy.
