### ISSUE TITLE
Site Comments: show Comments for Author and Contributor

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#16685]
Ref p5T066-2lo#comment-8597

Currently, when a user has a role that cannot moderate comments on a site (Author, Contributor), My Site > Comments does not show any comments. We should match the web behavior:
- Show all comments.
- Disable comment moderation options on comment details. (Authors & Contributors can only Like or Reply)

Tasks:
- [x] WPKit: `CommentServiceRemoteRest.getCommentsWithMaximumCount`, remove or update the `context` parameter. The `edit` context is what's causing no Comments to be returned. [#16768]
- [x] WPKit: parse the `can_moderate` flag for each comment and add to `RemoteComment`. [#16768]
- [x] WPiOS: add `can_moderate` to `Comment` entity and used when creating `Comment`s in `CommentService`. [#16769]
- [x] WPiOS: use `can_moderate` to enable/disable moderation options in Comment details. [#16783]
