### ISSUE TITLE
Stats - Referrers card / details view redesign

### ISSUE THREAD

**Issue by nikola-milicevic** [wordpress-mobile/WordPress-iOS#16710]
### Goal

Under stats screen, referrers card view and list view (when tapped on 'View more') should be redesigned to use flat lists, instead of collapse / expand functionality. Also, a referrer details screen needs to be added which will display a list of child referrers (if any) and 'Mark / Unmark as spam' button (if applicable).

### Proposed design

![Referrers - List copy](https://user-images.githubusercontent.com/12729242/122752995-e6405a00-d291-11eb-9b73-59fcc93d699e.png)

### Tasks

- [x] Flatten referrers card view and list view: [#16714](https://github.com/wordpress-mobile/WordPress-iOS/pull/16714)
- [x] Add referrer details scene: [#16715](https://github.com/wordpress-mobile/WordPress-iOS/pull/16715)
- [x] Move referrer logic from stats scene to details scene: [#16716](https://github.com/wordpress-mobile/WordPress-iOS/pull/16716)
- [x] Add unit tests: [#16730](https://github.com/wordpress-mobile/WordPress-iOS/pull/16730)

### Fine tuning
- [x] Check iPhone landscape
- [x] Check iPad
- [x] Check dark mode
- [x] Check small devices
- [x] Check RTL languages
- [x] Check Accessibility: [#16727](https://github.com/wordpress-mobile/WordPress-iOS/pull/16727)
