### ISSUE TITLE
Comment/Notification lists: update table cell

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#16741]
Create new common table cell, and use in both Comments and Notifications lists.

- [x] Create new view matching the design. (#16843)
- [x] Customizable to show pending indicator or unread indicator. (#16843)
- [x] Customizable to show API's Notification title or custom Comment title. (#16843)
- [x] #16852
- [x] #16851

Research notes:
- Should be able to copy and modify `CommentsTableViewCell` for both purposes.
- Remove `WPTableViewCell` inheritance.
- Consider using WKWebView to render content (HTML).

**Comment by aerych** [comment]
> Consider using WKWebView to render content (HTML).

This actually refers to the cells used in the threaded list and the view in the comment detail screen, not the "summary" cells used by the comment lists.
