### ISSUE TITLE
Reader 4.1 Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1689]
- [x] #1682 Reader: Follow/unfollow is broken for non wpcom sites
- [x] #309 Reader: Improve syncing to fill gaps in time between syncs *
- [x] #36 Improve reblog form *
- [x] #1380 Reblogging seems stuck loading the blog list after signing in *
- [x] #1486 Reblog lets you back out to Reader *
- [x] #458 Reader images missing due to photon not scaling *
- [x] #1620 Animated gifs show up as a blue dot in the reader -
- [x] #1664 WPAvatarSource should support identicions
- [x] #841 Improve layout of reader comment cells
- [x] #990 Update reader comments to include @hugobaeta’s suggestions
- [x] #1636 Reader: Drop shadow looks wrong for some posts.
- [x] #1043 Reader: content cut-off after device rotation *
- [x] #1028 Reader: missing like and comment counts

~~#1681 Add/remove topics/tags~~
