### ISSUE TITLE
Updating tracking properties in Reader

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#16961]
## Description

Add missing and update ambiguous properties as per the "Required code changes" column in a spreadsheet shared on p9xfpQ-1eg-p2.

This has already been implemented on the Android side by @ParaskP7 

Android Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/14069
Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/14283

## Notes

Before we start tackling these changes, it would be good to break this task down into smaller subtasks. Doing so will give us a better picture of the scope / size of this issue.

## Tasks

- [x] Update current events with missing properties (excluding source) / remove duplicates / fix triggers for events [#17213](https://github.com/wordpress-mobile/WordPress-iOS/pull/17213)
- [x] Add logic for event properties calculation [#17219](https://github.com/wordpress-mobile/WordPress-iOS/pull/17219)
- [ ] Add source property to all events

**Comment by ParaskP7** [comment]
👋 @momo-ozawa , @nikola-milicevic !

Thanks for the write-up! 🙏 

> Before we start tackling these changes, it would be good to break this task down into smaller subtasks. Doing so will give us a better picture of the scope / size of this issue.

I agree on that to 💯 .

On Android, we didn't do that and the PR ended up being too big. To be honest, some time constraints didn't help with that and thus I decided to create a single monster PR, just so that it can get merged after all, but you don't need to fall into that trap as well.

PS: On Android, we were also having a lot of legacy code that needed refactoring beforehand. Maybe the same applies to iOS, so be careful of that.
PSS: I was trying to add that comment yesterday but GitHub was down... 🤷 😅
