### ISSUE TITLE
Empty Stats: Standalone view

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17123]
## Description

Build the standalone empty stats view

Design ref: pbArwn-2Js-p2

## Tasks

- [x] Add Grow Audience card
- [x] Add Grow Audience ghost card for loading
- [x] Hook up dismiss button
- [x] Add presentation logic
  - [x] Show before Customize card
  - [x] Change the card dismissal to per site (currently dismissing the card will dismiss it for _all_ sites)
  - [x] Show if views are below a certain threshold
  - [x] Hide if views go above a certain threshold

**Comment by momo-ozawa** [comment]
Removing the Add tracks / events task from this card, since I've added them to the individual nudge tasks:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/17125
- https://github.com/wordpress-mobile/WordPress-iOS/issues/17124
- https://github.com/wordpress-mobile/WordPress-iOS/issues/17126

FYI @leandroalonso @nikola-milicevic
