### ISSUE TITLE
Onboarding Improvements: Quick Start prompt

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17386]
## Description

Update the Quick Start prompt UI.

Ref: pbArwn-32R-p2

<img width="642" alt="Screen Shot 2021-10-28 at 16 42 09" src="https://user-images.githubusercontent.com/6711616/139289875-399e8ae1-a8d7-4c68-8a9a-2e03f85189ff.png">

## Tasks
- [x] Update UI [#17426](https://github.com/wordpress-mobile/WordPress-iOS/pull/17426)
- [x] CTA: Show me around -> dismiss then present Quick Start checklist [#17426](https://github.com/wordpress-mobile/WordPress-iOS/pull/17426)
- [x] CTA: No thanks -> dismiss and prevent Quick Start prompt from showing in the future for that blog [#17426](https://github.com/wordpress-mobile/WordPress-iOS/pull/17426)
- [x] Fine tune design [per feedback ](https://github.com/wordpress-mobile/WordPress-iOS/pull/17449#pullrequestreview-804802387) from @osullivanchris [#17485](https://github.com/wordpress-mobile/WordPress-iOS/pull/17485)
