### ISSUE TITLE
Onboarding Improvements: Epilogue screen

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17385]
## Description 

Update the Epilogue screen UI.

Ref: pbArwn-32R-p2

<img width="643" alt="Screen Shot 2021-10-28 at 16 34 18" src="https://user-images.githubusercontent.com/6711616/139288589-5caab18c-8d75-4ff1-b523-91d8e630c82a.png">

![variations-1-site-multiple-site](https://user-images.githubusercontent.com/6711616/139288756-626c2870-07af-4407-a6cb-bc39ea1d2edc.png)

## Tasks
- [x] Update UI [#17389](https://github.com/wordpress-mobile/WordPress-iOS/pull/17389)
- [x] Variations [#17389](https://github.com/wordpress-mobile/WordPress-iOS/pull/17389)
  - [x] On the epilogue, If there is 1-3 sites, the `Create a new site` button is in the main view, connected to the list
  - [x] If there are more than 3 sites, the `Create a new site` button becomes fixed
- [x] Dark mode support [#17389](https://github.com/wordpress-mobile/WordPress-iOS/pull/17389)
- [x] Make sites clickable [#17411](https://github.com/wordpress-mobile/WordPress-iOS/pull/17411)
- [x] CTA: Create new site (only for WordPress) [#17449](https://github.com/wordpress-mobile/WordPress-iOS/pull/17449)
- [x] Fine tune design [per feedback](https://github.com/wordpress-mobile/WordPress-iOS/pull/17426#pullrequestreview-797982292) from @osullivanchris [#17345](https://github.com/wordpress-mobile/WordPress-iOS/pull/17345)
