### ISSUE TITLE
Onboarding Improvements: Project Issue

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17383]
## Description 

This is the parent project issue for Onboarding Improvements. We'll be using this issue to keep track of the project's progress.

Ref: pbArwn-35A-p2

## Tasks
- #17385 
- #17386 
- #17387 
- #17390
- #17500 

## Pre-release Tasks

- [x] A11y (https://github.com/wordpress-mobile/WordPress-iOS/pull/17540)
- [x] Event tracking (https://github.com/wordpress-mobile/WordPress-iOS/pull/17537)
- [x] Release Notes (https://github.com/wordpress-mobile/WordPress-iOS/pull/17565)
