### ISSUE TITLE
Reader Comments: Reuse the new comment content cell

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#17476]
Refs #17475, `pbArwn-2ks-p2#comment-4358`, and `pbArwn-38X-p2`

Reuse the content cell from `CommentDetailViewController`, reuse logic where possible, and customize as needed. Here's a list of expected changes to the content cell:

Description | Design
--|--
Author badge | <img width="357" alt="Screen Shot 2021-11-16 at 18 12 55" src="https://user-images.githubusercontent.com/1299411/141975350-d82a7f9f-9cb6-412c-89fc-d97044d6daab.png">
Highlighted comment[^1] | <img width="376" alt="Screen Shot 2021-11-16 at 18 14 32" src="https://user-images.githubusercontent.com/1299411/141975576-3abbe18f-df47-48df-b144-deb7871b64b9.png">
Top-level only separators | <img width="373" alt="Screen Shot 2021-11-16 at 18 16 11" src="https://user-images.githubusercontent.com/1299411/141975758-afdc03d1-28eb-4fad-9188-7dde0cdc7f5c.png">
Pending comments | <img width="370" alt="Screen Shot 2021-11-16 at 18 15 09" src="https://user-images.githubusercontent.com/1299411/141975630-56453de2-f7d0-4c70-9d9a-cdd7e0189345.png">
Reply button active state | <img width="299" alt="Screen Shot 2021-11-16 at 18 17 37" src="https://user-images.githubusercontent.com/1299411/141975968-ca78e40b-1251-49d6-a2a7-35b94cf598a4.png">

## Tasks

- [x] #17532
- [x] #17535
- [x] #17557
- [x] #17549
- [x] #17551
- [x] Parse comment author's ID from API: 
  - [x] https://github.com/wordpress-mobile/WordPressKit-iOS/pull/469
  - [x] #17566
- [x] Show author badge:
  - [x] Update WordPressKit to populate `authorID` in `RemoteReaderPost`. Addressed in https://github.com/wordpress-mobile/WordPressKit-iOS/pull/469.
  - [x] Parse `authorID` in `ReaderPost`. Addressed in #17566
  - [x] #17589
- [x] Implement logic for when the Reply and Like buttons are tapped. Addressed in #17600.
- [x] Handle when links in the comment body are tapped. Addressed in #17600.
- [x] Update the Reply button state when the reply text view is "targeting" the comment. Addressed in #17656.
- [x] Implement the cell highlight animation when navigating to a specific comment. Addressed in #17656.

### Display comments using the previous mechanism
- [x] #17634
- [x] #17635

### Issues
- [ ] The header cell sometimes goes missing after scrolling a lot of rows.

### Postponed

- Show pending comments from self. See: `pbArwn-2ks-p2#comment-4417`
- Optimize table view performance. We'll revert to the previous rendering mechanism for now.

[^1]: `pbArwn-2ks-p2#comment-3375` – when navigating to a specific comment in the thread, the comment should be highlighted for a second.
