### ISSUE TITLE
Update Reader Comments with the new design

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#17475]
Refs `pbArwn-2ks-p2`

Reuse the existing components and logic in `CommentDetailViewController` for the new designs in `ReaderCommentsViewController`, particularly the header cell, content cell, and the moderation logic.

Designs from Zeplin:

![comment-threads-4](https://user-images.githubusercontent.com/1299411/141793520-e7483a42-a281-4065-b4bc-76f272156168.png)

## Tasks 🎯 

- [x] Add feature flag for the updates on Reader Comments. Addressed in #17480
- [x] Comment header cell
  - [x] Update the header cell so it can show/hide disclosure indicator. Addressed in #17480
  - [x] #17487
  - [x] #17517
- [x] #17476
- [x] Show an overflow dropdown menu for administrator roles.
  - [x] Implement the overflow dropdown menu. Addressed in #17601.
  - [x] #17622
  - [x] Present a share sheet when the Share menu is tapped. Addressed in #17601.
  - [x] #17623
  - [x] #17629
- [x] Review accessibility.
- [x] #17658
- [x] #17659
