### ISSUE TITLE
My Site Dashboard (Phase 1)

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17681]
## Description

:star: **Goal**: Refactor the underlying My Site screen in preparation for the dashboard. The My Site screen should look and function the same way it does now (with the feature flag disabled).

Parent issue for phase 2 of the My Site Dashboard project.

Ref: pbArwn-3mP-p2

## Tasks

- [x] Add a feature flag (#17690)
- [x] Update site menu list style to inset grouped (#17812)
- [x] Refactor My Site screen
    - [x] Initial structure (#17737)
    - [x] Extract blog detail header view to SitePickerViewController (#17783)
    - [x] Delete old blog detail header view (#17792)
    - [x] Convert MySiteViewController root view to scroll view (#17820)
    - [x] Hide segmented control for self-hosted sites (#17892)
    - [x] Add pull-to-refresh for site menu (#17823)
    - [x] Add FAB / handle Quick Start tour auto-scroll (#17847)
    - [x] Remove table header view from BlogDetailsViewController (#17863)
