### ISSUE TITLE
My Site Dashboard: Posts Card content

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#17697]
This task groups all the steps necessary to create the content of the Posts Card (which can be embedded inside other views). The aim is to create the part that shows the posts/opens the editor, not the actual card frame.

<img src="https://user-images.githubusercontent.com/7040243/146988566-0e0199c7-785e-49f1-8694-931a2bdaf6a9.png" width="300">

- [x] Create the ViewController and return a list of 3 posts (draft or scheduled) - #17738
- [x] Handle the FRC sync between the card and the post list (more on this below) - #17738
- [x] Display ghost cells when loading posts for the first time - #17750
- [x] Handle the sync with the server - #17750
- [x] Update the `PostListEditorPresenter` to accept any UIViewController - #17757
- [x] Update the cells to match designs - #17767
- [x] Embed the card in the dashboard - #17787
- [x] Display error when posts fail to fetch and there are no posts at all - #17839
- [x] Double-check and update events
- [x] Display only posts created by the author (not all posts)

Known issues:

- [ ] When creating a new post and discarding it, one of the previous posts shown disappear #18165
- [x] You can see the post list adjusting its height when first appearing (fixed in #17787)

Removed from this issue:

* ~Update content when blog switches~
* ~Add logics for additional syncs (after last sync was 1h ago, for example)~

Both should be tackled as part of the whole dashboard updating.

### Additional info: Posts List screen and the card

One of the biggest issues I found while working on the POC was that the `NSFetchedResultsController` basically doesn't respect the `fetchLimit`. In some cases, you'll be able to see 2 or 4 posts — which is not a big deal. However, if you go to the post list screen and go back to the main screen, all the posts seen on the Posts List will be displayed on the card. I managed to do a workaround on the POC branch that seems to work fine, but more testing will be necessary.

### POC

My explorations/POC can be [found here](https://github.com/wordpress-mobile/WordPress-iOS/tree/exploration/posts_card).

**Comment by leandroalonso** [comment]
Closing the issue since the overall work is done. Bugs will be tracked in their own issues.
