### ISSUE TITLE
Project Thread: iOS Jetpack Install Onboarding Prompt

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#17721]
## Description
Ask self hosted users if they’d like to install Jetpack (if they don’t already have it) during the sign in process.

## Tasks

- [Phase 1: Jetpack Onboarding Install Prompt](#user-content-project-phase-1)
- [Phase 2: Self hosted Jetpack Install Prompt](#user-content-project-phase-2)
- [Phase 3: Improvements](#user-content-project-phase-3)

### Login Epilogue
- [x] Create a new screen that asks if they want to install Jetpack on their site: https://github.com/wordpress-mobile/WordPress-iOS/pull/17723
- [x] Create a way to present the Jetpack install flow after the user taps yes: https://github.com/wordpress-mobile/WordPress-iOS/pull/17723
- [x] Add logic to dismiss the prompt if the user selects no thanks
- [x] Add logic to determine if we should show the install prompt: https://github.com/wordpress-mobile/WordPress-iOS/pull/17723

### Jetpack Login
- [x] Update the Jetpack connect URL to remove the locale from the URL path: https://github.com/wordpress-mobile/WordPress-iOS/pull/17722

### Final Touches
- [ ] Add tracking
- [ ] Test Jetpack App
- [ ] Write and update UI Tests
- [ ] Add feature flag
- [ ] Add RTL support
- [ ] Add accessibility
- [ ] Test iPad

### Login Prompt
- [ ] Look into adding this prompt into the initial steps of authentication
- [ ] Jetpack app already does a check if the user has a valid install, we can reuse that
- [ ] Reuse existing Jetpack prompt and update with new copy and buttons
- [ ] Add action that pushes to the WP.com login when the user taps the confirm button
- [ ] Add action that pushes to the username / password login when the user taps no thanks

### Final Touches
- [ ] Add tracking
- [ ] Test Jetpack App
- [ ] Write and update UI Tests
- [ ] Add feature flag
- [ ] Add RTL support
- [ ] Add accessibility
- [ ] Test iPad

## <a name="project-phase-3">Phase 3: Improvements</a>
- [ ] After installing Jetpack and logging into WPcom display a message informing the user we're enabling the features. This prevents the blog details from being silently updated and confusing for the user, especially on slower connections
- [ ] Sometimes there can be a blank screen displayed after displaying the connect webview: https://github.com/wordpress-mobile/WordPress-iOS/pull/17722#pullrequestreview-846499849
- [ ] If a user logs into blog using a site address that Jetpack installed and connected, we should inform them they have Jetpack installed and ask them if they want to sign in with their WPcom account
- [ ] If you tap on Install Jetpack from the stats view and go through the install and connection process you are then brought to a screen requiring you to log into your WP.com for a second time.
- [ ] The login epilogue can be displayed during the connection process, we should prevent it from displaying
- [ ] When authorizing in Jetpack connect the first time always fails

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 19.2 today and I can see a number of unchecked items in the Phase 1 block description.

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 19.3 today and I can see a number of unchecked items in the Phase 1 block description, even though they're all "Final Touches" except for one.

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 19.4 today and I can see a number of unchecked items in the Phase 1 block description, even though they're all "Final Touches" except for one.

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 19.5 today and I can see a number of unchecked items in the Phase 1 block description, even though they're all "Final Touches" except for one.

**Comment by emilylaguna** [comment]
Closing this issue as @staskus will be taking over the project.
