### ISSUE TITLE
My Site Dashboard: My Site screen container view prep

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17740]
## Description

Prep work to embed a new dashboard collection view controller in `MySiteViewController`

## Tasks

- [x] Create .xib for `MySiteViewController` and add a segmented control and a container view for child view controllers (#17737) 
- [x] Add a dashboard collection view controller to be embedded in the container view (#17737) 
- [x] Hide `NewBlogDetailViewHeader` in tableview / add `NewBlogDetailViewHeader` to `MySiteViewController` (#17783)
- [x] Delete old `BlogDetailViewHeader` (#17792)
