### ISSUE TITLE
My Site Dashboard: Add pull to refresh on My Site

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17784]
## Description
Pulling to refresh My Site should update the header view (site picker vc) AND the child vc (blog details vc).

Note: Updating the blog dashboard vc will be handled in phase 2 of the My Site Dashboard project.

## Tasks
- [x] Add a refresh control to My site
- [x] Refresh site picker vc
- [x] Refresh blog details vc (site menu)
