### ISSUE TITLE
My Site Dashboard: Refine scrolling behavior for My Site

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17786]
## Description 

Currently the My Site screen only scrolls on the child vc container. However, the entire screen should scroll.

## Tasks

- [x] Scroll the entire screen (Contain stackview in a scrollview, and may need to convert the BlogDetailsVC tableview into an IntrinsicTableView) #17820
- [x] Make sure the BlogDetailsVC scrolls to the correct element during the Quick Start tours #17847
- [x] Make sure the FAB appears on the My Site screen #17847

**Comment by leandroalonso** [comment]
There's a hint here how we can be able to achieve that without using `IntrinsincTableView`: https://stackoverflow.com/questions/35876003/expand-uitableview-to-show-all-cells-in-stack-view

Not sure if it works tho, we'd need to test.
