### ISSUE TITLE
My Site Dashboard (Phase 2): Quick Start

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17877]
## Description

Add a Quick Start card to the dashboard.

Ref: pbArwn-3mP-p2
Design ref: pbArwn-3fp-p2

## Tasks

- [x] Create initial Quick Start card UI #18015
- [x] Trigger Quick Start from the dashboard #18015
- [x] Display site menu waypoint if the tour is initiated from the dashboard view #18015
- [x] Refine Quick Start card UI #18044 
- [x] A11y #18044 
- [x] Reuse new Quick Start UI on Site Menu https://github.com/wordpress-mobile/WordPress-iOS/pull/18095
- [x] Show Quick Start on Site Menu or Dashboard (one or the other, not both) https://github.com/wordpress-mobile/WordPress-iOS/pull/18095
- [x] Add UserDefaults key to specify display location for A/B testing (see: [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18095#pullrequestreview-901914448)) #18101 
- [x] Allow users to remove Quick Start card from dashboard #18160
- [x] Investigate Quick Start notice showing after switching to site menu (see: [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18095#pullrequestreview-902496174)) #18170
- [x] [Track tap events](https://github.com/wordpress-mobile/WordPress-iOS/issues/18173) #18183
