### ISSUE TITLE
My Site Dashboard (Phase 2): iPad Info Architecture

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17878]
## Description

Add a new menu item in the site menu that displays the dashboard on iPads

Ref: pbArwn-3mP-p2
Design ref: pbArwn-3fp-p2

## Tasks

- [x] Add new Home menu item in BlogDetailsViewController #17957
- [x] Hide Home menu item for self-hosted sites w/o Jetpack #17957
- [x] Show BlogDashboardViewController in the details view controller when the Home menu item is selected #17957
- [x] Refine design #17987

**Comment by leandroalonso** [comment]
@momo-ozawa what are "Track tap events" here?

**Comment by momo-ozawa** [comment]
@leandroalonso I was thinking we should track when the user taps the "Home" row on iPad. I added a comment on the MSD tracks doc about using the `my_site_switch_screen` event to track this, lmk what you think

**Comment by momo-ozawa** [comment]
@leandroalonso I removed the "Track tap events" subtask since we now have a dedicated [issue for MSD event tracking](https://github.com/wordpress-mobile/WordPress-iOS/issues/18150#issuecomment-1069424133)
