### ISSUE TITLE
My Site Dashboard (Phase 2): Posts

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17875]
## Description

Refine the Posts card shown on the dashboard.

Ref: pbArwn-2Fh-p2

## Tasks

- [x] Handle different card types and user states #17977
    - [x] Draft posts card (single vs multiple posts) #17977
    - [x] Scheduled posts card (single vs multiple posts) #17977
    - [x] Create your first / next post card #17977
    - [x] Events #18005
    - [x] Improvements #18014
    - [x] Fix switching between sites with published posts and no published posts (as per [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18014#issuecomment-1050702592)) #18034

## Constraints and warnings

There are some cases in which constraints are breaking and/or there's a warning output.

#### TableView warning

```
WordPress[19738:323718] [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <_TtC9WordPressP33_802B839C3C12DC08AA85FBE243B5267217PostCardTableView: 0x139093000; baseClass = UITableView; frame = (0 0; 350 132); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x1382e7cd0>; layer = <CALayer: 0x1382b8a50>; contentOffset: {0, 0}; contentSize: {350, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: (null)>
```

This happens because we call `collectionView.layoutIfNeeded()` inside `BlogDashboardViewController.viewDidLoad`, the tableView is not added to any window yet.

#### Broken constraints

We have warnings about constraints in two different cases:

1. When presenting the "write your next post prompt"
2. When presenting drafts **and** scheduled at the same time

**Comment by leandroalonso** [comment]
Added a section about warnings.

I'm not going to tackle those now given there are no layout issues and we still have some Dashboard-related pending tasks. I'm gonna focus on these ones. If we have time at the end of the project I plan to tackle these.
