### ISSUE TITLE
My Site Dashboard (Phase 2): Stats

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17876]
## Description

Add a Today's Stats card to the dashboard.

Ref: pbArwn-3mP-p2
Design ref: pbArwn-3pp-p2

## Tasks

- [x] Create Stats card UI (Display Views / Visitors / Likes for both iPhone and iPad) #18075
- [x] Show data for Today's Stats #18133
- [x] Track tap events #18134
- [x] A11y #18134

**Comment by leandroalonso** [comment]
@hassaanelgarem one small comment: stats should appear before posts (cc @osullivanchris). In order to do that you can simply move it up on `DashboardCard` :)

**Comment by hassaanelgarem** [comment]
@leandroalonso Just applied that change in #18134 👍
