### ISSUE TITLE
Reader 4.2 Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1821]
### Clean up
- [x] #1778 - ReaderTopics not deleted when account changes 
- [x] #1776 - ReaderPostServiceRemote fetch called after logout -
### View Hierarchy Improvements
- [x] #1729 - Refactor layout logic
- [x] #1715 - WPContentView is unwieldy
#### Topics Mgt
- [x] #1681 - Add / remove topics from within app -
- [x] #1377 - Don’t show topics list as popover -
#### Image Related
- [x] #1761 - Reader images do not appear to load (for private sites) -
- [x] #1368 - Reader: Featured image missing or different in some case -
#### Misc Visual
- [x] #1622 - Tweak blockquote margins 
- [x] #1293 - Reader button active states need to be consistent -
### Performance
- [x] #1657 - Move away from EGO Refresh
### Other Improvements
- [x] #1782 - Disallow reblogging for private blogs 
- [x] #1570 - Replace uppercaseString with localized version 
- [x] #769 - Review how controllers are being presented in the Reader -
- [x] #596 - Reader: Feedback for attempting to like a post while not logged in
