### ISSUE TITLE
QuickStart for Existing Users V2: Create New Tour

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18388]
## Description

We need to create a new tour consisting of some old tasks and some new tasks.
Tour tasks:
- Stats (Existing)
- Notifications (New)
- Preview Site (Existing)
- Add Media (New)
- Reader (Existing)

New tasks need to be created. And the new tour should be only assigned to new existing users.

New Tour title: "Get to know the WordPress app"

Ref: pbArwn-40S-p2
Design Ref: pbArwn-4kz-p2

## Tasks

- [x] Refactor UI data source
    - #18395 
- [x] Create New Tour
    - This will initially be comprised of the three existing tasks
    - Two below tasks should be added to the tour once created
    - #18412
- [x] Assign new tour to existing users
    - On login, if the user is an existing user and accepts help then assign the new tour, if they're a new user then assign old tours.
    - This logic should be hidden behind a feature flag
    - #18412
- [x] Create Notifications task
    - Add steps as per the design
    - Make sure to add the task complete notice
    - #18443
- [x] Create Media task
    - Point to quick action in dashboard or item in the site menu, depending on where the user is
    - Make sure to autoscroll in both cases
    - #18471
