### ISSUE TITLE
QuickStart for Existing Users V2: Update existing tasks

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18387]
## Description

We are reusing some old tasks in the new tour for existing users. Some of these tasks will require some tweaks.

Ref: pbArwn-40S-p2
Design Ref: pbArwn-4kz-p2

## Tasks

- [x] Update Stats task #18413 
    - Point to quick action in dashboard or item in site menu, depending on where the user is
    - Step that points from dashboard to site menu should be removed
    - Make sure to autoscroll in both cases
    - Add task complete notice
- [x] Update Preview Site task #18393 
    - Point to url in site header instead of the item on the site menu
- [x] Update Reader task #18450 
    - Switch to the Discover tab if needed
    - Modify the last step to point to settings instead of search
- [x] Clean up additional insets for Quick Start tasks (ref: [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18413#discussion_r857541372)) #18460
- [x] Delete Edit Your Homepage task (ref: p1650465006026059/1650367281.046699-slack-C027K4MNPGQ) #18469
