### ISSUE TITLE
Blogging Prompts: connect functionality and UI

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#18429]
Items that need addressing when Blogging Prompts endpoints are available.

- [x] Scheduling view: hook up `Include prompt` toggle. (Ref: [#18316](https://github.com/wordpress-mobile/WordPress-iOS/issues/18316))
- [x] Blogging Prompts Settings (Ref: [#18549](https://github.com/wordpress-mobile/WordPress-iOS/issues/18549))
  - [x] Prepopulate the reminder schedule if a remote schedule exists. (ref: p1652112794189519-slack-C0339PBMQ92) [#18753](https://github.com/wordpress-mobile/WordPress-iOS/pull/18753)
- [x] Compact Prompt Card: (Ref: [#18402](https://github.com/wordpress-mobile/WordPress-iOS/issues/18402))
  - [x] Check for cached prompt before fetching. ([#18658](https://github.com/wordpress-mobile/WordPress-iOS/pull/18658))
  - [x] Update answered state ([#18572](https://github.com/wordpress-mobile/WordPress-iOS/pull/18572))
  - [x] Show new post when Answer tapped. ([#18599](https://github.com/wordpress-mobile/WordPress-iOS/pull/18599))
  - [x] ~~Show share sheet when Share tapped.~~ Remove for V1. ([#18670](https://github.com/wordpress-mobile/WordPress-iOS/pull/18670))
  - [x] Hide for self-hosted sites ([#18819](https://github.com/wordpress-mobile/WordPress-iOS/pull/18819))
  - [x] Add a help button similar to the one on the blogging reminders settings screen
- [x] Prompt Card: (Ref: [#18250](https://github.com/wordpress-mobile/WordPress-iOS/issues/18250))
  - [x] Show/hide depending on `is_potential_blogging_site` field ("we can use the prompts_card_opted_in setting that in the backend is currently (diff under review) equals the is_potential_blogging_site field judged on the backend")
  - [x] Check for cached prompt before fetching. ([#18642](https://github.com/wordpress-mobile/WordPress-iOS/pull/18642))
  - [x] Update train of avatars ([#18534](https://github.com/wordpress-mobile/WordPress-iOS/pull/18534))
  - [x] Update number of answers ([#18534](https://github.com/wordpress-mobile/WordPress-iOS/pull/18534))
  - [x] Update answered state ([#18534](https://github.com/wordpress-mobile/WordPress-iOS/pull/18534))
  - [x] Show new post when Answer tapped. ([#18599](https://github.com/wordpress-mobile/WordPress-iOS/pull/18599))
  - [x] ~~Show share sheet when Share tapped.~~ Remove for V1. ([#18670](https://github.com/wordpress-mobile/WordPress-iOS/pull/18670))
  - [x] Overflow menu:
    - [x] View more prompts: show prompts list ([#18505](https://github.com/wordpress-mobile/WordPress-iOS/pull/18505))
    - [x] Skip this prompt: remove the current card from the dashboard. ([#18642](https://github.com/wordpress-mobile/WordPress-iOS/pull/18642))
    - [x] ~~Remove from dashboard: permanently remove prompt cards from dashboard.~~ The menu item is removed for V1.  ([#18627](https://github.com/wordpress-mobile/WordPress-iOS/pull/18627)) 
  - [x] Update display logic to `(prompts_reminders_opted_in || (!prompts_reminders_opted_in && is_potential_blogging_site)` ([#18816](https://github.com/wordpress-mobile/WordPress-iOS/pull/18816))
- [x] Feature Introduction:
  - [x] Ensure that the feature introduction modal doesn't clash with other modals shown during app launch, e.g. feature announcement, new Stats. Refs p1654007734556469-slack-C0339PBMQ92 ([#18820](https://github.com/wordpress-mobile/WordPress-iOS/pull/18820))
  - [x] Remove showing feature introduction on app launch. ([#18820](https://github.com/wordpress-mobile/WordPress-iOS/pull/18820))
    - [x] `WordPressAppDelegate` - `WPTabBarController.sharedInstance().showBloggingPromptsFeatureIntroduction()`
    - [x] `WPTabBarController` - `showBloggingPromptsFeatureIntroduction()`
  - [x] Try it now: populate post content with prompt content. ([#18597](https://github.com/wordpress-mobile/WordPress-iOS/pull/18597))  
  - [x] Filter out self-hosted sites when tapping on 'Try it now' ([#18829](https://github.com/wordpress-mobile/WordPress-iOS/pull/18829))
- [x] Post creation (Ref: [#18473](https://github.com/wordpress-mobile/WordPress-iOS/issues/18473))
  - [x] When creating an answer prompt post, pass the prompt's metadata with it. (See  [#18717](https://github.com/wordpress-mobile/WordPress-iOS/issues/18717), [#18808](https://github.com/wordpress-mobile/WordPress-iOS/pull/18808)) (ref: D80516-code)
`  "metadata": [
    {
    	"key": "_jetpack_blogging_prompt_key",
      	"value": 235,
      	"operation": "update"
    }
  ]`
  - [x] Add a `dailyprompt` tag to posts which answer the prompt ([#18851](https://github.com/wordpress-mobile/WordPress-iOS/pull/18851))
- [x] Prompts List: check for cached prompt before fetching. ([#18658](https://github.com/wordpress-mobile/WordPress-iOS/pull/18658))
  - [x] Fetch today's prompt where appropriate ([#18842](https://github.com/wordpress-mobile/WordPress-iOS/pull/18842))
- [x] #18761
