### ISSUE TITLE
Feature tooltip container view

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18466]
Refs pbArwn-4oo-p2

![](https://cldup.com/CGvjrQv1zh.png)

Create the feature tooltip UI along with some display logic.

## Tasks

- [ ] Create the tooltip container
  - [ ] Header component with the sparkle image. Note that while SFSymbols provide a "sparkles" symbol, the one that's used seems to be from the emoji.
  - [ ] Body component.
  - [ ] Dismiss action button.
- [ ] Provide optional secondary action buttons.
- [ ] Create the pointer view.
- [ ] Create the pulsing target indicator view. (note that the design post mentions this view as optional).
- [ ] Add logic to position the tooltip view and pointer view based on available space.
- [ ] Review accessibility.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
