### ISSUE TITLE
Tooltip anchor view

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18467]
Refs: pbArwn-4oo-p2

![](https://cldup.com/9vN1WQ2N1n.png)

Create the anchor view and add some display logic that shows the component when the tooltip is being shown and out of the viewport.

## Tasks

- [ ] Create the anchor view. 
  - The sparkle icon should match the one in Feature Tooltip.
- [ ] Add logic that shows/hides the anchor view based on the tooltip view's visibility on the viewport.
- [ ] Add logic that scrolls to the feature tooltip when tapped. (discussion: pbArwn-4oo-p2#comment-5656)
- [ ] Review accessibility.
