### ISSUE TITLE
Feature tooltip entry point

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18468]
Refs pbArwn-4lQ-p2

Create the entry-point component so it's convenient to show the feature tooltip. There may also be some logic involved to ensure that the tooltip experience is great.

## Tasks

- [ ] Create that entry-point component.
- [ ] Ensure that only one tooltip is shown at any given time. Dscussion: pbArwn-4oo-p2#comment-5607
- [ ] Add logic that automatically dismisses the tooltip for good after 2-3 views. Discussion: pbArwn-4lQ-p2#comment-5508

**Comment by kean** [comment]
We're now using TipKit.
