### ISSUE TITLE
Blogging Prompts: Answer prompt flow

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#18473]
## Description
<img width="303" alt="Screen Shot 2022-04-28 at 3 10 37 PM" src="https://user-images.githubusercontent.com/2454408/165828363-ec9ae731-2727-4099-9400-7d2e46d2909b.png">

Show the new post view with the correct content populated.

## Tasks

- [x] Populate the new post view
  - #18481
- [x] Present from the feature introduction 
  - #18503
- [x] Present from the dashboard card
  - #18504
- [x] Present from bottom sheet view
  - #18535
- [x] #18544
