### ISSUE TITLE
Blogging Prompts: Tracks

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#18472]
## Description

Add tracking to any missed issues in blogging prompts and align the keys/properties with Android.

## Tasks
- [x] Tracking for 'Add New' bottom sheet [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - Issue ref: #18402
  - [x] 'Answer Prompt' tap [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] Verify it matches Android [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
- [x] Tracking for Feature Introduction buttons (#18176) [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] `Try it now` [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] `Remind me` [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] `Got it` [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
- [x] Tracking for dashboard prompt card (#18250) [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] Answer [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] View more prompts [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] Skip this prompt [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
  - [x] Remove from dashboard [#18751](https://github.com/wordpress-mobile/WordPress-iOS/pull/18751)
- [x] Update reminders analytics to match Android [#18777](https://github.com/wordpress-mobile/WordPress-iOS/pull/18777)
- [x] Add analytics for `entry_point` when opening the editor from tapping on 'Answer Prompt' [#18828](https://github.com/wordpress-mobile/WordPress-iOS/pull/18828)
