### ISSUE TITLE
[iOS] Stats:  New Totals Card

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#18500]
As part of the Stats revamp, we'll add a new Totals card, which is used for Comment, Like, and Follower counts:

![Image](https://user-images.githubusercontent.com/4780/166483879-a813bb21-c30e-4e91-be22-23bc09a25c07.png)

Note: The Followers card requires a few changes from the design above:

- Follower Totals should be named "Total Followers" to match the other cards
- It no longer includes a comparison label as we don't currently have access to that data
- "This week" on the Follower Totals card should be changed to "All-time"

**Subtasks**

- [x] Split out new card types for Likes, Comments, Followers
- [x] Check error / no data states
- [x] Hook up to live data (this was dependent on changes from the Views and Visitors graph in Insights)

**Comment by frosty** [comment]
Refs #18911
