### ISSUE TITLE
Blogging Prompts settings sync

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18549]
Refs p1651275029253999-slack-C01CW1VMLAF

The blogging prompts settings object is used for two-way communication between the client and the remote server; there will be a `GET` endpoint to fetch the settings, and a `POST` endpoint to update the settings. Here's an example payload:

```json
{
	"prompts_card_opted_in": false,
	"prompts_reminders_opted_in": false,
	"reminders_days": {
		"monday": false,
		"tuesday": false,
		"wednesday": false,
		"thursday": false,
		"friday": false,
		"saturday": false,
		"sunday": false
	},
	"reminders_time": "10.00 UTC"
}
```

- `prompts_card_opted_in` is used to track whether or not the prompt card is shown in the user's dashboard. When the user removes the card from the dashboard, this field should be updated.
- `prompts_reminders_opted_in` simply tracks whether the Blogging Prompts switch in the reminders sheet is enabled or not. Initially, it should always be `false` — and the client should report any changes to the remote whenever this value changes (i.e., after the user toggles the Blogging Prompts switch).
- `reminders_days` and `reminders_time` are used to track the schedules that the user has set to receive prompt notifications. Currently, any changes to the reminders schedule are only reported if the Blogging Prompts switch is enabled.

NOTE: There's ongoing work to add `is_potential_blogging_site` which determines whether the Feature Introduction sheet for Blogging Prompts should be shown. This should be a read-only field.

## Tasks

- [x] https://github.com/wordpress-mobile/WordPressKit-iOS/pull/504
- [x] Map the sync requests to WordPress-iOS. [#18695](https://github.com/wordpress-mobile/WordPress-iOS/pull/18695)
  - [x] #18709
  - [x] #18719
- [x] Sync reminder settings to remote when the blogging prompts feature is enabled [#18723](https://github.com/wordpress-mobile/WordPress-iOS/pull/18723)
  - [x] Send the schedules to remote when a reminder schedule is set with blogging prompts enabled. [#18737](https://github.com/wordpress-mobile/WordPress-iOS/pull/18737)
- [x] Add `is_potential_blogging_site` to blogging prompts settings.
