### ISSUE TITLE
Quick Start: New visuals for checklist modal

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#18552]
## Description

Visual changes to the Quick Start checklist modal.

Design ref: pbArwn-4wS-p2

## Tasks

- [ ] Update Quick Start checklist modal 
    - [x] Remove success screen and completed list (#18649)
    - [ ] Update to new designs for both New Site / Existing Site (#18711)
    - [ ] Grey out completed task (#18711)
