### ISSUE TITLE
Project: iOS QRCode Login Support

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#18594]
## Description
Allow WP.com users to sign in to their browsers by scanning a QR Code in the WPMobile iOS App.

## Tasks:
- [x] Add a way to access the QRCode scanner via the Me tab: https://github.com/wordpress-mobile/WordPress-iOS/pull/18715

### Create a view controller for QR Code Scanning
- [x] Add camera capture: https://github.com/wordpress-mobile/WordPress-iOS/pull/18716
- [x] Add a square overlay to the camera: https://github.com/wordpress-mobile/WordPress-iOS/pull/18716
- [x] Add basic link validation: https://github.com/wordpress-mobile/WordPress-iOS/pull/18716
- [x] Add handling when a valid link is scanned: https://github.com/wordpress-mobile/WordPress-iOS/pull/18716
 
#### Design a basic view
- [x] Add a header label: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Add a label that displays the location of the browser: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
- [x] Add a label that displays the vendor of the browser: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
- [x] Add a button to "Accept": https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Add a button to "Reject": https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
#### Validate the incoming link with the server
- [x] Display a loading indicator: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Make call to validate endpoint: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
- [x] Push to the error view if request fails: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
- [x] Display main UI when request succeeds: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
#### Add button actions
- [x] Dismiss the "flow" when the "reject" button is tapped: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Add "Accept" button action: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Make call to the authorize endpoint: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
- [x] Display another loading UI: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Push to the error view if the request fails: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
- [x] Push to the "Authorized" view on success: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
 
#### Design a basic view
- [x] Add a header label: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Add a label that directs the user to go back to the browser: https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
- [x] Add a button to "Dismiss": https://github.com/wordpress-mobile/WordPress-iOS/pull/18752
 
#### Create the new QRLoginRemoteService in WPKit
  - [x] Add a validate link method: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/513
      - [x] Create a new Decodable struct for the success response
      - [x] Map success to new struct
iOS/pull/513
  - [x] Add an authorize method: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/513
      - [x] Create a new Decodable struct for the success response
      - [x] Map success to new struct
  - [x] Create a WPMobile QRLoginService: https://github.com/wordpress-mobile/WordPress-iOS/pull/18756
      - [x] Add a validate link method
      - [x] Add a authorize method

### Update Deep Linking
- [x] Add handling for the QRCode URL when scanned outside of the app: https://github.com/wordpress-mobile/WordPress-iOS/pull/18765

### Add Tracking
- [x] Add tracking to the QRCode scanning view: https://github.com/wordpress-mobile/WordPress-iOS/pull/18766
- [x] Add tracking to the Are you sure view: https://github.com/wordpress-mobile/WordPress-iOS/pull/18766
- [x] Add tracking to the Authorized view: https://github.com/wordpress-mobile/WordPress-iOS/pull/18766
- [x] Add tracking to the deep link handler: https://github.com/wordpress-mobile/WordPress-iOS/pull/18766

### Finishing Touches
- [x] Add unit tests: https://github.com/wordpress-mobile/WordPress-iOS/pull/18924
- [x] Fix iPad layout
