### ISSUE TITLE
Quick Start: New visuals for Quick Start card

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#18621]
## Description

Visual changes to the Quick Start card.

Design ref: pbArwn-4wS-p2

## Tasks

- [x] Update Quick Start card 
    - [x] Update to new designs for Existing Site only #18688
    - [x] Progress bar (states: in progress, complete) #18688
