### ISSUE TITLE
Blogging Prompts notification handling

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18739]
Refs #18542 

This covers the tasks related to local notification handling for Blogging Prompt. When a Blogging Prompt notification is shown, there are several cases that need to be handled. As stated in #18542, two kinds of notification are scheduled:

- Prompt notifications, where the prompt content is displayed and leads the user to the Post Editor when tapped.
- Static notifications, where a call-to-action is displayed and fetches today's prompts before showing the Post Editor.

## Tasks

- [x] When a prompt notification is tapped: open the Post Editor. 
- [x] When a static notification is tapped: show the My Site Dashboard with the prompt card visible.
- [x] For both notifications, when tapped, check if the prompt notification is for the current site, or switch to the correct site if needed.
