### ISSUE TITLE
Prompts reminder scheduling integration

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18761]
Refs #18429, #18542

This task covers the prompt scheduler integration to the UI.

## Tasks

- [x] Add a wrapper component to hide the implementation detail that decides whether to use Blogging Reminders mechanism or Blogging Prompts mechanism. (Addressed in [#18772](https://github.com/wordpress-mobile/WordPress-iOS/pull/18772))
- [x] Switch between Blogging Reminders and Blogging Prompts scheduling mechanism when "Notify Me" is pressed, based on the switch state. (Addressed in [#18772](https://github.com/wordpress-mobile/WordPress-iOS/pull/18772))
  - When switching, ensure that pending reminders from the previous mechanism are removed to prevent double notifications.
- [x] Remove pending notifications when the Blog is deleted, or when the user signed out. (Addressed in [#18774](https://github.com/wordpress-mobile/WordPress-iOS/pull/18774))
- [x] Reschedule notifications whenever the reminder schedule changes. (Addressed in [#18774](https://github.com/wordpress-mobile/WordPress-iOS/pull/18774))
- [x] Reschedule notifications after fetching new prompts. (Addressed in [#18776](https://github.com/wordpress-mobile/WordPress-iOS/pull/18776)).
  -  Some prompt notifications may already be expired by the time the user opens the app. With current settings, reschedule the local notifications so that the notification timeframe is updated.
