### ISSUE TITLE
Blogging Prompts: Undo notification when skipping

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#18899]
## Description

![Screen Shot 2022-06-16 at 2 10 57 PM](https://user-images.githubusercontent.com/2454408/174137787-b83e25b3-af45-4a68-9414-d50f108a1a4e.png)

Add an undo notification when a prompt is skipped that brings back the prompts dashboard card.

## Tasks

- [x] **Notification title:** Prompt skipped
- [x] **Button title:** Undo
- [x] **Button action:** Re-display the prompts dashboard card that is now hidden after user hit skip

**PR:** https://github.com/wordpress-mobile/WordPress-iOS/pull/18900
