### ISSUE TITLE
Update Jetpack app store screenshots

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#18960]
## Description

- Fix the UI tests for the JetpackScreenshotGeneration target -- part of the larger effort to fix screenshot automation for Jetpack (ref: paaHJt-3wL-p2, item i[1])
    - Currently all UI tests are failing (ref: paaHJt-3sE-p2)
- Update promo screenshots (design ref: pcdRpT-DL-p2)

### Raw screenshots 

- [x] Dismiss Feature Intro modal (https://github.com/wordpress-mobile/WordPress-iOS/pull/18965)
- [x] Fix switching sites (https://github.com/wordpress-mobile/WordPress-iOS/pull/18965, https://github.com/wordpress-mobile/WordPressMocks/pull/42)
- [x] Fix navigating to the Backup Options screen (https://github.com/wordpress-mobile/WordPress-iOS/pull/18965)
- [x] Update raw screenshots pcdRpT-z4-p2#comment-731 (#19093)
- [x] Fix notifications screenshot for iPad (#19126) 
- [ ] Fix stats graph not displaying (On hold, since Stats Revamp hasn't been released and this issue is [related to Stats Revamp](https://github.com/wordpress-mobile/WordPress-iOS/pull/19016#issue-1299165404))

### Promo screenshots

- [ ] Update promo screenshots lane (#19124 )

## Notes

- UITest sometimes fails on tearDown (ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/19093#issuecomment-1196637057)
