### ISSUE TITLE
Jetpack Focus: Missing features on the Jetpack app

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#19164]
## Description

There are a few features present in the WordPress app that aren't available on the Jetpack app.

To determine the missing features on Jetpack, I went through the WPiOS codebase and searched for `AppConfiguration` flags that were `false` for Jetpack but `true` for WordPress.

## Tasks

- [x] Recommend App
    - [x] Section in Me screen (#19174)
    - [x] Remove obsolete About screen (#19174)
- [x] Add option to add self-hosted site on the My Sites screen (#19194)
- [x] What Is New
    - [x] Modal shown on My Site, Notifications, Reader screens (#19176) 
    - [x] Section in App Settings (#19176)
    - [x] Backend work on MC (D85726-code) 
    - [x] Backend work on wpcom (D85737-code)
- [ ] App Icon section in App Settings screen (pending assets)
- [ ] AB Testing / ExPlat ([Jetpack is not available on ExPlat](https://github.com/wordpress-mobile/WordPress-iOS/pull/18380))

**Comment by enejb** [comment]
Just noting that we currently have 2 open prs to make the `What Is New` work on the backend. 

mc: D85726-code
wpcom: D85737-code

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
