### ISSUE TITLE
[Jetpack] Show Jetpack plugin install prompt during Jetpack app login process

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19213]
This is an issue to track tasks related to _"Jetpack install prompt during Jetpack app login process feature"_.

## Description

Ask self-hosted Jetpack app users if they'd like to install Jetpack during the login process.

## Parent Branch

feature/19213-jetpack-install-prompt

## Phase 1:  Prompt users to install Jetpack during the login process

- [x] Integrate previously started changes on the new branch: (feature/19213-jetpack-install-prompt)
- [x] Test previously created changes on different screen sizes and configurations
- [x] Show the prompt once per site
- [x]  https://github.com/wordpress-mobile/WordPress-iOS/pull/19225
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/19234
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/19240
- [x] Feature flag https://github.com/wordpress-mobile/WordPress-iOS/pull/19240 [last commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/19240/commits/abdde7c87f11cbb950c5342c3c455a9c11983bf7)
- [x] Accessibility https://github.com/wordpress-mobile/WordPress-iOS/pull/19250
- [x] RTL Support https://github.com/wordpress-mobile/WordPress-iOS/pull/19250
- [x] Write UI tests and update the current ones (testAddSelfHostedSiteAfterWPcomLogin, testSelfHostedLoginLogout, testWPcomLoginLogout are failing)
- [x] _Consider unifying prompt visibility logic for login and stats/notifications_
- [x] Issue on iPad, since Stats are already opened, we need to refresh Stats when installation is complete, if we don't, Stats continue showing "Install"  https://github.com/wordpress-mobile/WordPress-iOS/pull/19269
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/19302
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/19330
- [x] Consider Release Notes

**Comment by staskus** [comment]
Closing the issue as its tasks are completed.

All the changes are on the `feature/19213-jetpack-install-prompt` branch.

**Comment by guarani** [comment]
Awesome work, @staskus! 💯
