### ISSUE TITLE
Jetpack Focus: Add Jetpack banner for other features

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#19448]
## Description
We will be adding the following new banners:
* Starting from phase one:
    * Backups
    * Scan
* Starting from phase two (JP dependent features):
    * Menus
    * Themes
    * People

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

## Tasks
- [x] [Add Jetpack Banner to Menus](https://github.com/wordpress-mobile/WordPress-iOS/pull/19844) (Starting from phase 2)
- [x] [Add Jetpack Banner to Themes ](https://github.com/wordpress-mobile/WordPress-iOS/pull/19845)(Starting from phase 2)
- [x] [Add Jetpack Banner to People](https://github.com/wordpress-mobile/WordPress-iOS/pull/19797) (Starting from phase 2)
- [x] [Add Jetpack Banner to Backups](https://github.com/wordpress-mobile/WordPress-iOS/pull/19784) (Starting from phase 1)
- [x] [Add Jetpack Banner to Jetpack Scan](https://github.com/wordpress-mobile/WordPress-iOS/pull/19854) (Starting from phase 1)

**Comment by hassaanelgarem** [comment]
#### Note
`JetpackBrandingCoordinator.shouldShowBannerForJetpackDependentFeatures() -> Bool` can be used to determine when to show the banner for Menus, Themes, and People.
