### ISSUE TITLE
Jetpack Focus: Remove Jetpack features during phase 4

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#19452]
## Description

This applies to new users and to phase four users.

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

## Tasks

- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/19810
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/19811 
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/19812 
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/19813
