### ISSUE TITLE
Move synced database to single copy

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#19476]
## Description

Convert the shared database between WordPress and Jetpack to a single one way copy from WordPress to Jetpack.

## Tasks

- [x] Copy the database from WordPress to the shared directory
- [x] Copy from the shared directory to the local directory on Jetpack
- [x] Cleanup any remaining shared database code
