### ISSUE TITLE
Reader 4.3 Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1993]
### Features
- [x] #1976 - Implement adding a blog by URL
### Images and Media
- [x] #1910 - Reader detail and reblogging vas should fetch/cache images vs images being passed 
- [x] #1808 - Confirm photon supports https. Let https images be loaded via photon
- [x] #1812 - Do not upscale images that are too small 
- [x] #1695 - Reader image sometimes show pixelated on iPad 
- [x] #1317 - ReaderMediaView should be refactored to use one of the image queue classes 
- [x] #1765 - Blue dot failed images 
- [x] #1760 - Video preview image blank, tap play & done twice 
- [x] #1980 - Alter reader post list image loading to load a few posts in advance 
### Performance
- [x] #1650 - Taping share while scrolling causes the scroll to stutter
- [x] #1197 - Pull way too far for pull to refresh 
- [x] #1149 - Pull to refresh sometimes get stuck on the reader
- [x] #1981 - Don’t set image in cell used for height calculation 
### Misc
- [x] #1989 - Reader: Hungry VideoPress regex is eating too much of the copy 
- [x] #1884 - support likes enabled and sharing enabled
- [x] #1762 - Reblogging doesn’t watch response for success
- [x] #1663 - Reader animated paper issue 
- [x] #1045 - WPWebController: “Back” cut off when navigating to a web page 
- [x] #1979 - Make ReaderMediaQueue and ReaderMediaView (sub-)classes less reader-y
