### ISSUE TITLE
Add block user option in the Reader post menu

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#19982]
We want to add a new **Block user** action to the actions sheet appearing in reader post. This action will filter out content from a specific user based on the user id. The list of blocked users will be kept client side ( internal ref: p1669978053731249/1669929094.952189-slack-C02FMH4G8 )

| Followed Site | Unfollowed Site |
| - | - |
| ![Image](https://user-images.githubusercontent.com/9609223/214299127-528e85cd-73f8-4b20-8722-7276167e0aac.png) | ![Image](https://user-images.githubusercontent.com/9609223/214299240-f119faf5-f888-46b2-94fb-f32c1c550a32.png) |

## Task list
- [ ] [Add core functionality: A button to block users](https://github.com/wordpress-mobile/WordPress-iOS/pull/19997)
- [ ] Save blocked authors locally in Core Data
- [ ] Refresh Reader when author is blocked
- [ ] Send Tracks events?

**Comment by mokagio** [comment]
Changing the milestone to 21.8 because this is incomplete and I'm about to start the 21.7 code freeze. Feel free to revert if necessary.

**Comment by mokagio** [comment]
Changing the milestone to 21.9 because this is incomplete and I'm about to start the 21.8 code freeze. Feel free to revert if necessary.
