### ISSUE TITLE
Create the fullscreen modal

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20016]
Refs qk5s4q4mZsXknwhMWo2vIY-fi-8221%3A20788
Depends on #20015 

![Image](https://user-images.githubusercontent.com/1299411/215049827-1fc749d3-fc83-4e58-911c-4221bc89b605.png)

## Tasks

- [x] Create the fullscreen modal UI. (#20067)
- [x] Dismiss the modal and show My Sites when the Close button is tapped. #20132 
- [x] Show the Help screen when the Contact Support button is tapped. #20166
- [x] Add Tracks. #20132

### Unresolved issues

From #20067:
- [x] The t&c label collides with the body text in accessibility size. #20165 
- [x] Body text is not yet configured based on single or multiple individual plugins. #20166

From #20132:
- [x] Make the auto-dismiss behavior optional in the `JetpackFullscreenOverlayViewController` when the secondary button is tapped. We need this to show the Support screen instead of having the whole thing dismissed. #20166
- [x] Show the terms & conditions page via the in-app browser when the link is tapped. #20166

**Comment by dvdchr** [comment]
Moved these two tasks to #20153:

- Show the Jetpack plugin install flow when the Continue button is tapped.
- Implement the presentation logic.
