### ISSUE TITLE
Update domain empty view UI

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#20075]
The empty view of the domain screen in site creation flow will be updated.
The view is displayed after the `Choose a theme` screen, when the search input is empty.

#### Subtasks

- [ ] Update title and subtitle text and left align it
- [ ] Update search input
- [ ] Change illustration view

### Design

| Before | After |
| - | - |
| <img width="300" src="https://user-images.githubusercontent.com/4588074/217229274-09f4f8ef-ceca-47b4-88bb-198853499d8f.png"> | <img width="300" src="https://user-images.githubusercontent.com/4588074/220167937-ce10d18b-0c6d-4a6c-befb-7acf54dd33ef.png"> |

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)
