### ISSUE TITLE
Suggest paid domains

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#20077]
The list of domain suggestions should include both free and paid domains.
For the API integration details see internal ref: pc8HXX-ZF-p2.

#### Subtasks

- [ ] Fetch free and paid domains
- [ ] Implement UI for paid domains
- [ ] Apply discounts to domains on sale
- [ ] Add 'Recommended' label to 1st item and 'Best alternative' to 2nd one

### Design

<img width="250" src="https://user-images.githubusercontent.com/4588074/220165887-3df8822e-439e-4446-a945-933a070f0942.png">

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)

**Comment by salimbraksa** [comment]
@ovitrif Just want to double check whether the following changes are out of scope:
- The 1st row in the screenshot. "This domain is already registred" + "Own this domain?"
- "SSL Required" label.

**Comment by ovitrif** [comment]
@salimbraksa Thanks for the ping!

> The 1st row in the screenshot. "This domain is already registred" + "Own this domain?"

- "Own this domain?" button is out of scope.
- "This domain is already registered" text and styling is in scope of the draft task in the `No Status` lane of the board: `Add availability check for FQDNs`.
  I'll add more details to the task when I move it to the `Todo` lane. For now you can park (un)availability checks since it's to be tackled separately.

> "SSL Required" label.

This is out of scope 👍🏻
