### ISSUE TITLE
Update blogging prompts dashboard card and FAB header display logic

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20084]
## Tasks

- [x] Make the display logic for the dashboard card and FAB the same with the following conditions:
  - [x] Blogging prompts feature flag enabled
  - [x] "Show prompts" option is enabled
  - [x] Blog is not a self-hosted site
  - [x] User has not skipped the prompt
- [x] Update the "Show prompts" option's default value to be the `is_potential_blog` value
