### ISSUE TITLE
Add site preview UI for domain purchases

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#20080]
The flow for paid domains should end with a slightly different UI on the site preview screen.
This task is to update the preview screen, i.e. the final screen of the site creation flow, shown after the user completes the domain purchase in the previous step: Domain Checkout.

### Subtasks

- [ ] Update title typeface, left-align it and change text to `Domain Purchase Complete`
- [ ] Add subtitle: `We’ve emailed a receipt to your address on file.`
- [ ] Add caption to site preview: `It may take up to a day for your blog and your new domain to be fully connected.`

| Before | After |
| - | - |
| <img width="300" src="https://user-images.githubusercontent.com/4588074/217291872-55612ebf-a51f-4651-9f98-f8eb775a3e26.png"> | <img width="300" src="https://user-images.githubusercontent.com/4588074/220172648-594e45ba-7f2b-43f9-922a-ee34f3b732df.png"> |

---
> **Note**:
> - Other changes are out of scope and part of other tasks
> - All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-Android/issues/17896)
