### ISSUE TITLE
Add tracks events

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#20086]
Add analytics events for the domain purchasing during site creation flow.

#### Subtasks (events)

- [ ] `enhanced_site_creation_domains_selected`
   - Add new property: `domain_cost`: `free`/`domain.cost` 
- [ ] `domains_purchase_webview_viewed` → when the domain checkout webview is shown
   - Add a new `origin` property: `site_creation` / `menu`   
- [ ] `domains_registration_form_submitted` → when the form is submitted in the webview
- [ ] `domains_purchase_domain_success` → when the purchase was successful
- [ ] Site created with paid domain event

**Note:** All development should be behind [the feature flag](https://github.com/wordpress-mobile/WordPress-iOS/issues/20073)
