### ISSUE TITLE
Blaze Overlay Without Post Content

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-iOS#20094]
Project ref - pcdRpT-1LY-p2
Design ref - cEGtlsm6xijEswaKkrQrIj-fi-512%3A5295

## Description 
Implement an overlay for Blaze. 

## Todo 
- [x] Implement the UI for blaze (#20236)
- [x] On click navigate to select post screen (#20236)
- [x] Track events on Displayed with source (#20250) 
- [x] Track events on Continue/Closed (#20250)
