### ISSUE TITLE
Blaze Overlay With Post Content

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-iOS#20093]
Project ref - pcdRpT-1LY-p2
Design ref - cEGtlsm6xijEswaKkrQrIj-fi-512%3A5295

## Description 
Implement an overlay for Blaze with the Selected Post. 

## Todo 
- [x] Implement the UI with the thumbnail of the Post (#20246)
- [x] Track events on Displayed with source (#20250) 
- [x] Track events on Continue/Closed (#20250)
