### ISSUE TITLE
Entry Point: Menu Item

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-iOS#20091]
Project ref - pcdRpT-1LY-p2

## Description 
Add a Jetpack blaze menu item 

## Todo 
- [x] Check if the site is eligible and add a menu item (https://github.com/wordpress-mobile/WordPress-iOS/pull/20127)
- [x] Navigate to Blaze  create overlay on the click (#20194) 
- [x] Track events on Clicked (#20203)
