### ISSUE TITLE
Wire up components and add entry points

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20153]
## Tasks

- [x] Create an entry point to determine whether the overlay (and/or cards) should be shown. #20155
- [x] Wire up the fullscreen overlay from #20016 
  - [x] Show the Remote Install flow when the "Install" button is tapped. [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
  - [x] Implement the presentation logic (i.e., determine when and where to show the overlay). [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
- [x] Wire up the Remote Install flow from #20018 
  - [x] Assign a `JetpackRemoteInstallDelegate` instance for the flow. [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
  - [x] Dismiss the modal after "Cancel" button is tapped. [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
  - [x] Dismiss the modal after "Done" button is tapped. [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
  - [x] Refresh after the Jetpack plugin is successfully installed. [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
- [x] Wire up the dashboard cards from #20019 
  - [x] Show the fullscreen overlay when "Learn more" is tapped. [#20174](https://github.com/wordpress-mobile/WordPress-iOS/pull/20174)
  - [x] Hide the card indefinitely from both locations when "Hide this" is selected. #20155
  - [x] Implement presentation logic for the cards (i.e., whether the card should be shown or not). #20155
