### ISSUE TITLE
iOS - Add helpers to identify the new disabled state

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20329]
## Description
We will now have two different states:
* JP Features **Disabled**
    * This will be enabled by the `jp_removal_static_posters` remote feature flag
    * In this state the dashboard will be removed
    * The tab bar will still exist but Stats, Reader, and Notifications will be disabled and we'll display a static poster (This will be handled in separate tasks)
    * The banners and badges text will change (This will be handled in a separate task)
* JP Features **Removed** 
    *  This will be enabled by the `jp_removal_four` remote feature flag
    * This is the original experience planned for phase 4, where all JP features are completely removed.

## Tasks
- [x] Add new API(s) to help determine if JP features should be enabled, disabled, or removed
- [x] Remove dashboard when JP features are "disabled"
- [x] Disable hidden features (remote and local notifications, deep links, weekly roundup, etc.)
