### ISSUE TITLE
Show the overlay after the user switches to an individual site

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20375]
Refs pcdRpT-22m-p2, qk5s4q4mZsXknwhMWo2vIY-fi-9905-21221

This task covers presenting the overlay with an adjusted copy based on the existing overlay.

## Design

<img src="https://user-images.githubusercontent.com/1299411/226610278-348c2e47-4d7d-4c16-8f5c-42693c0714d1.png" width=250 />

## Tasks

- [x] Add a new variation or modify the existing overlay to use a different copy for WordPress.
- [x] Present the overlay after switching to an individual site.
- [x] Primary CTA switches to the Jetpack app when tapped.
- [x] Add Tracks.
