### ISSUE TITLE
Dashboard Cards: Update dashboard cards endpoint handling

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20438]
## Tasks

- [ ]  Add new card types parameters
- [ ]  Update request handling for JSON response (parsing, etc)
- [ ]  Update existing dashboard models
