### ISSUE TITLE
Dashboard Cards: Add Pages card in correct position

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20439]
## Tasks

- [ ] Add a skeleton card to the dashboard
- [ ] Implement hiding logic if Pages is not supported
- [ ] Add card in the correct position
