### ISSUE TITLE
Dashboard Cards: Add Activity Log card in correct position

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20446]
## Tasks

- [x] Add a skeleton card to the dashboard
- [x] Implement hiding logic if Activity Log is not supported
- [x] Add card in the correct position
