### ISSUE TITLE
Dashboard Cards: Implement context menu for the Pages card

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20443]
## Tasks

- [ ] Add context menu to the ellipsis
- [ ] Implement "Show all pages" action
- [ ] Implement "Hide card" action
