### ISSUE TITLE
Dashboard Cards: Implement the "Create a new page" section in the Pages card

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20444]
## Tasks

- [ ] Implement the "Create another page" section
- [ ] Handle different states (New user with 1 page/existing user with multiple pages)
- [ ] Handle tap action and open page creation flow
