### ISSUE TITLE
Dashboard Cards: Implement context menu for the Activity Log card

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20450]
## Tasks

- [ ] Add context menu to the ellipsis
- [ ] Implement "Show all logs" action
- [ ] Implement "Hide card" action
