### ISSUE TITLE
Jetpack Focus: Update migration success UI

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#20513]
## Description

Update the wording on the migration success card to make clear to users they should uninstall the app instead of deleting their site.

Slack ref: p1681290711175429-slack-C0180B5PRJ4
Design ref: qk5s4q4mZsXknwhMWo2vIY-fi-10230_21914

## Todo

- [x] Update strings on the final step of the migration
- [x] Update strings and appearance on the dashboard card
- [x] Update strings on the migration popover
