### ISSUE TITLE
Comment moderation updates

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20568]
Refs: 
- pcdRpT-2fP-p2 
- gxUGcHDCJZbsB4UFelF1bG-fi-179_5163

![comments-cover](https://user-images.githubusercontent.com/1299411/233334829-58b10740-0387-4040-962e-ffab1ad760b3.png)

## Description

This serves as an umbrella task for updates related to comments. We'll be updating the comments UI to reduce the presence of moderation actions once it's approved and bring more focus to collaborative actions.

## Todo

```[tasklist]
### Tasks
- [x] #20737
- [ ] Add a thin container view for Site Comments.
- [ ] Separate Site-specific concerns from Comment Detail.
```

```[tasklist]
### Comment Header
- [ ] #20753
- [ ] Add feature image thumbnail to comment header.
- [ ] Apply the new header view in My Sites and Notifications.
```

```[tasklist]
### Comment Content
- [x] #20579
- [ ] Toggle between "moderation mode" or "collaboration mode" depending on comment status.
- [ ] Update the Reply & Like buttons.
- [ ] Implement the moderation badges.
- [ ] Update the ellipsis menu.
- [ ] Update the content header section.
- [ ] Implement the new moderation bar.
```
