### ISSUE TITLE
iOS - Site Editor MVP

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20635]
## Tasks

- [x] Update models in WordPressKit-iOS ([POC](https://github.com/wordpress-mobile/WordPressKit-iOS/compare/update-fse-flag) can be used as starting point): https://github.com/wordpress-mobile/WordPressKit-iOS/pull/598
  - [x] Add `__unstableIsBlockBasedTheme` to `RemoteBlockEditorSettings` 
  - [x] Add `block-templates` bool to `RemoteEditorThemeSupport`
- [x] Add "Site Editor" feature flag. https://github.com/wordpress-mobile/WordPress-iOS/pull/20640

- [x] Update [this flag](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/Models/BlockEditorSettings%2BGutenbergEditorSettings.swift#L48) to check against the new `block-templates` bool added in the `RemoteEditorTheme` model. https://github.com/wordpress-mobile/WordPress-iOS/pull/20640

### "Pages" Screen Tasks

- [ ] Fetch the editor/theme settings when navigating to the screen. We can use `BlockEditorSettingsService` and call the function `fetchBlockEditorSettings`. If the editor settings call fails, it defaults back to fetching the theme settings. These theme settings get forced into the `blockEditorSettings` so we can use that object regardless of whether the user is using Gutenberg.
- [ ] Update `PageListTableViewHandler` to return an additional row when `blog.blockEditorSettings?.isFSETheme` is **`true`**.
- [ ] Update `PageListViewController` to modify the first cell of the table to be the homepage cell when `blog.blockEditorSettings?.isFSETheme` is **`true`**.
  - [ ] Do not inject the homepage cell when a homepage already exists.
- [ ] When the new homepage cell is tapped, launch an **authenticated** web view to either:
  - [ ] `https://wordpress.com/site-editor/` when it's a simple site (non-atomic).
  - [ ] `/wp-admin/site-editor.php` when it's atomic.

**Comment by wargcm** [comment]
Closing this in favor of:

- https://github.com/wordpress-mobile/WordPress-iOS/issues/20641
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20642
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20643
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20644
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20645
