### ISSUE TITLE
[Site Editor] Detect block-based themes

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20641]
## Tasks

- [x] Update models in WordPressKit-iOS ([POC](https://github.com/wordpress-mobile/WordPressKit-iOS/compare/update-fse-flag) can be used as starting point): https://github.com/wordpress-mobile/WordPressKit-iOS/pull/598
  - [x] Add `__unstableIsBlockBasedTheme` to `RemoteBlockEditorSettings` 
  - [x] Add `block-templates` bool to `RemoteEditorThemeSupport`
- [x] Update [this flag](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/Models/BlockEditorSettings%2BGutenbergEditorSettings.swift#L48) to check against the new `block-templates` bool added in the `RemoteEditorTheme` model. https://github.com/wordpress-mobile/WordPress-iOS/pull/20640

**Comment by dvdchr** [comment]
#20640 is merged to trunk, but the PR is somehow closed. 🤔 probably related to [this incident](https://www.githubstatus.com/incidents/f0mhbz9xn497) as discussed in p1683642069637929-slack-C02KLTL3MKM. Seeing as all tasks have been checked, I'll close this issue.
