### ISSUE TITLE
[Site Editor] Homepage cell UI for block-based themes

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20644]
Ref: p1683269583780939/1683217373.827519-slack-C04STEB172L

## Tasks

- [x] Update `PageListTableViewHandler` to return an additional row when: https://github.com/wordpress-mobile/WordPress-iOS/pull/20671
  - [x] `blog.blockEditorSettings?.isFSETheme` is **`true`** 
  - [x] The "Published" filter is selected.
- [x] Update `PageListViewController` to modify the first cell of the table to be the homepage cell when: https://github.com/wordpress-mobile/WordPress-iOS/pull/20671
  - [x] `blog.blockEditorSettings?.isFSETheme` is **`true`** 
  - [x] The "Published" filter is selected.
- [x] Hide the existing homepage cell if it already exists. See ref. https://github.com/wordpress-mobile/WordPress-iOS/pull/20671
