### ISSUE TITLE
iOS - Show deprecation notice in the Social screen

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20675]
Refs pctCYC-OI-p2, Th1ahHKq53k5JT1PNDMavY-fi-879_16211

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/7a11035e-8614-406f-8822-2ce4b6e93359)

### Tasks

When Twitter is in `unsupported` status:

- [x] In the connection list screen:
  - [x] Hide Twitter when the user has no existing connections [#20708](https://github.com/wordpress-mobile/WordPress-iOS/pull/20708)
  - [x] Display Twitter in a separate section if there are existing connections [#20708](https://github.com/wordpress-mobile/WordPress-iOS/pull/20708)
  - [x] Show deprecation footer when Twitter connections exist [#20709](https://github.com/wordpress-mobile/WordPress-iOS/pull/20709)
- [x] In the connection detail screen:
  - [x] Show the deprecation notice [#20714](https://github.com/wordpress-mobile/WordPress-iOS/pull/20714)
  - [x] Hide “Share post to Twitter” and “Connect another account” buttons [#20714](https://github.com/wordpress-mobile/WordPress-iOS/pull/20714)
