### ISSUE TITLE
Blaze: Manage Campaigns - Implement the Empty Campaigns logic on Dashboard

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-iOS#20757]
## Description 
If there are no campaigns then show the existing blaze card as before on dashboard

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [x] Check if there is no campaigns
- [x] If there is no campaign show the existing card
- [x] Implement the tracking logic
```
