### ISSUE TITLE
Blaze: Manage Campaigns - Implement Campaign Detail Webview

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-iOS#20765]
## Description 
Implement the UI to show Campaign detail 

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [x] Implement the webview
- [x] Implement the back press or close logic
- [x] Implement the Tracking logic
```

**Comment by AjeshRPai** [comment]
The calypso changes for hiding the Back button is implemented with this PR https://github.com/Automattic/wp-calypso/pull/79832
