### ISSUE TITLE
Blaze: Manage Campaigns - Implement the Campaign Creation Entry Points

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-iOS#20763]
## Description 
~Implement the FAB for users to create a Campaign~
Update + button to display "Create" instead (Slack ref: https://a8c.slack.com/archives/C04LJFS1G5P/p1689005387328969?thread_ts=1688729817.258079&cid=C04LJFS1G5P) 

## Links 
Design ref - 1Osrn9gb2xLaKG6lIft3WC-fi-1461_9777

```[tasklist]
### Todo
- [x] Implement the nav bar button
- [x] Implement the Click handler
- [x] Implement the Tracking logic
```
