### ISSUE TITLE
[JP Social v1] Publish Sheet and Post Settings section UI

### ISSUE THREAD

**Issue by thomashorta** [wordpress-mobile/WordPress-iOS#20778]
Create the UI for the Jetpack Social section inside the pre-publish sheet and post settings screen. Each item will be a separate component and the section itself will be a component holding the items.

```[tasklist]
### Tasks
- [ ] Create connection item
- [ ] Create message item
- [ ] Create sharing limit item (upsell)
- [ ] Create no-connections item (promote JP social)
- [ ] Create section / UI state / callbacks
```

Figma: Th1ahHKq53k5JT1PNDMavY-fi-864_15242

### Connection item
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/5091503/882ac410-1441-4324-9186-edeb15dde115)

### Message item
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/5091503/a0ae82de-cc36-495f-a4d3-70290a815a1a)

### Sharing limit item
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/5091503/a4d0075b-5449-4530-9879-32042f55e650)

### No-connection item
This item is shown by itself in the section when there are no connections
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/5091503/b27e3cd9-66b7-4bae-862a-04911ba8d14d)

### Pre-publish sheet UI
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/5091503/6712670d-f633-44db-8dca-bbf76b228adc)

### Post Settings UI
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/5091503/9b64c674-b028-4349-97a8-fdd59c13bdbb)
