### ISSUE TITLE
Jetpack Social: Update Post Settings Social UI

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20784]
Figma: Th1ahHKq53k5JT1PNDMavY-fi-849_12349
Spec: pctCYC-PK-p2#post-settings

## UI

![Image](https://user-images.githubusercontent.com/2454408/242452182-1f446604-bd83-4fcd-8bc2-60bff1ad3c74.png)

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/20808
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/20823
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/20965
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/20966
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21024
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21026
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21027
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21061
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21137
```
