### ISSUE TITLE
Jetpack Social: Add Social UI to Pre-Publishing Sheet

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20783]
Figma: Th1ahHKq53k5JT1PNDMavY-fi-833_22885
Spec: pctCYC-PK-p2#pre-publishing-sheet

## UI

![Image](https://user-images.githubusercontent.com/2454408/242449177-82c0d80b-20aa-4833-9770-84657df4af97.png)

```[tasklist]
### Tasks
- [ ] #21036
- [ ] #21037
- [ ] #21056
- [ ] #21073
- [ ] #21074
- [ ] #21113
- [ ] #21171
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21179
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21188
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21199
```
