### ISSUE TITLE
[JP Social/Core] Get sharing limit information from new API

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#20806]
```[tasklist]
### Tasks
- [x] 🔴 Blocker: p1685440505473569/1681747490.482279-slack-C02JJ910CNL
- [ ] https://github.com/wordpress-mobile/WordPressKit-iOS/pull/606
- [ ] #20946
- [ ] #20955
- [ ] https://github.com/wordpress-mobile/WordPressKit-iOS/pull/615
- [ ] #20969
```
