### ISSUE TITLE
🍎 Domains List Screen

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#21432]
## Acceptance Criteria
- A search bar is added at the top of the screen with the new search UI.
- The search bar contains a filter icon and the trailing side.
- Displays a list of domains the user has.
- Tapping on each domain card must navigate to the respective details screen in a webview.

## Screenshot Reference

![Image](https://user-images.githubusercontent.com/15968946/263347043-c005b21b-f421-40ea-a560-0999e1ba3a14.png)

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21434
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21556
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21560
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21561
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21431
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21785
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21793
```
