### ISSUE TITLE
Modernize Media screen

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21457]
Spec: [UI Modernisation: Media on iOS](https://jetpackmobile.wordpress.com/2023/08/31/ui-modernisation-media-on-ios/).

## Foundation  ✅

The existing Media screen implementation relies heavily on [MediaPicker](https://github.com/wordpress-mobile/MediaPicker-iOS) framework, which is written in Objective-C and hasn't received a lot of attention recently. The framework attempts to generalize the code that displays images from different sources: your WordPress media library, Photos, Free Photos and GIFs, and more, which makes it brittle and hard to modify. The existing implementation also has some severe performance issues with thumbnail loading and caching, which have to be addressed.

In version 23.2, we've made the first step on the road to replacing the [MediaPicker](https://github.com/wordpress-mobile/MediaPicker-iOS) framework: [integrating PHPickerViewController](https://github.com/wordpress-mobile/WordPress-iOS/issues/21190). The next step is to reimplement the Media screen in Swift while fixing the many unaddressed performance and other issues. This ticket covers it.

The first part of this ticket covers reimplementing the core Media screen functionality in Swift.

- https://github.com/wordpress-mobile/WordPress-iOS/pull/21470
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21542
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21562
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21566
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21580
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21601 
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21615
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21651
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21664
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21673
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21678

## Modernization ✅

The second part of this ticket covers the new features and design improvements.

### List

- [x] Use new [context menus](https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/fa4bd0f2-b65e-46e8-a849-fa5749d4ac0a) for media picker (done in [#21562](https://github.com/wordpress-mobile/WordPress-iOS/pull/21562))
- [x] Add GIF playback support 
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/21702
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/22013
- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/22009

### Details

- [x] Allow swiping between photos and switch to adjacent items when deleting the selected one [#22008]
- [x] Refresh the design [#22008]
- [x] Use optimistic UI for savings metadata changes [#22008]

## Fixes

- [x] Fix an issue with blank placeholders during image uploading (PR: [#21470](https://github.com/wordpress-mobile/WordPress-iOS/pull/21470))
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/9922
- [x] Fix an issue with images flashing on pull-to-refresh
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/21572
- [x] Fix an issue with incorrect background color used for audio and document view until the cell is reused

## Thumbnail Loading Improvements ✅

- [x] Add prefetching (PR: [#21470](https://github.com/wordpress-mobile/WordPress-iOS/pull/21470), fixes: [#4288](https://github.com/wordpress-mobile/WordPress-iOS/issues/4288))
- [x] Cancel the requests when cells moved offscreen (PR: [#21470](https://github.com/wordpress-mobile/WordPress-iOS/pull/21470), fixes: [#14528](https://github.com/wordpress-mobile/WordPress-iOS/issues/14528)) 
- [x] Fix main thread performance issues due image decompression happening on the main thread (PR: [#21470](https://github.com/wordpress-mobile/WordPress-iOS/pull/21470))
- [x] Remove transcoding when downloading remote thumbnails and store original thumbnail data in local cache
- [x] Use `URLSession` with no `URLCache` to avoid double-caching it: the service has its own disk cache
- [x] Use `absoluteThumbnailLocalURL` for storing thumbnails. It gets populated by `MediaImportService` when the assets are added, so we avoid duplicating the work of generating the thumbnail
- [x] Move disk I/O to background threads
- [x] Removes unnecessary `coreDataStack.mainContext.perform` hops and use `@MainActor` to enforce thread confinement

**Comment by kean** [comment]
Thumbnail loading performance comparison old vs new:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/4dec94e1-3a73-4023-a6c0-4177fa53b6b8 https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/3f27a22f-0754-46fd-8e71-5ca0cf3c05ad

**Comment by kean** [comment]
It's done.
