### ISSUE TITLE
Contact Support: Fixes for feedback from CfT (iOS)

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#21557]
```[tasklist]
### Tasks
- [x] Update first message (See p5T066-44s-p2#comment-14865)
- [ ] Limit questions to 3 instead of current 6
- [x] Fix layout issues (See p5T066-44s-p2#comment-14855)
- [ ] Pass meta data
```

**Comment by ravishanker** [comment]
**First Message**: Not sure if it is possible to set two chat bubbles!  Try if possible with a line break instead.
**Suggestions**: Need to decide which three. ( Probably don't need to do this on iOS, unless it is overlapping like on Android,  and see which suggestions get most clicks perhaps!)
**Layout fixes**: See what is possible without introducing new issues
**Meta data** See p1694530643955909-slack-C05ALSVN5K5

Contact Support text does not change when selecting a different Text Size.  Try https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

**Comment by staskus** [comment]
@ravishanker, thanks for creating a task! 

I was also investigating scrolling issues yesterday https://github.com/wordpress-mobile/WordPress-iOS/issues/21549 but couldn't find a solution that works reliably yet.

**Comment by staskus** [comment]
Involving @guarani if you want to take a look at some of them.

**Comment by guarani** [comment]
> Pass meta data

I think this relates to [this Slack thread](p1694610794259359/1694530643.955909-slack-C05ALSVN5K5), would you agree @staskus?

> Fix layout issues (See p5T066-44s-p2#comment-14855)

I'll try to fix these today

**Comment by guarani** [comment]
Ah, I see this was answered above in https://github.com/wordpress-mobile/WordPress-iOS/issues/21557#issuecomment-1716808137.

**Comment by mokagio** [comment]
Look like not all tasks for this issue have been completed. Bumping from [23.3](https://github.com/wordpress-mobile/WordPress-iOS/milestone/257) to [23.4](https://github.com/wordpress-mobile/WordPress-iOS/milestone/258) because I'm about to start the code freeze.

**Comment by mokagio** [comment]
Bumping from [23.5](https://github.com/wordpress-mobile/WordPress-iOS/milestone/259) to [23.6](https://github.com/wordpress-mobile/WordPress-iOS/milestone/260) because I'm about to start the code freeze and this is still in progress.
