### ISSUE TITLE
Reader Improvements: Update Reader tag and sites header

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21643]
Refs pcdRpT-3Eb-p2, zQnohyMpLzBzQ5jzMMKni3-fi-867%3A9115

This covers design updates for the Tag and Site stream headers in the Reader.

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/a2d2764a-5c4f-44d7-b86e-fcf403c61138)

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21475
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21477
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21480
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21641
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21642
```
