### ISSUE TITLE
Widgets: Provide mandatory iOS 17 SDK Support

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21672]
## Tasks

- [x] https://github.com/wordpress-mobile/WordPress-iOS/pull/21705
- [x] Update small Home screen widget layout to support removable background and appear on iPadOS
- [x] Consider updating Lock Screen Widget layout to appear without background as most Lock Screen Widgets do
- [ ] Support margins and allow at least some of the widgets to appear in StandBy mode
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21816

## Description

After building the app with Xcode 15, Home and Lock screen widgets are no longer working and show `please adopt containerBackground API` message:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/f23b6392-1284-43b8-875d-f4b90e887646" width="250">

This is related to a new [Removable background](https://developer.apple.com/videos/play/wwdc2023/10027/?time=180) introduced at WWDC2023. More context:
- https://developer.apple.com/documentation/widgetkit/preparing-widgets-for-additional-contexts-and-appearances
- https://www.optimistic-closures.com/adjusting-your-widgets-containerbackground/
- https://nemecek.be/blog/192/hotfixing-widgets-for-ios-17-containerbackground-padding

### Expected behavior

Widgets should support new APIs and this message should not be shown

### Steps to reproduce the behavior

1. Build Jetpack app with Xcode 15
2. Try to add a widget

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

**Comment by staskus** [comment]
In order to remove this message we need to support [containerBackground](https://developer.apple.com/documentation/SwiftUI/View/containerBackground(_:for:)) API. The best way is to create an extension so both iOS17 and <=iOS16 would be supported:

```swift
extension View {
    func widgetBackground(_ backgroundView: some View) -> some View {
        if #available(iOSApplicationExtension 17.0, *) {
            return containerBackground(for: .widget) {
                backgroundView
            }
        } else {
            return background(backgroundView)
        }
    }
}
```

and attach it to the end of the view. This makes the background removable. Most notably, on iPadOS Lock Screen. 

### Issue

We use `AccessoryWidgetBackground` for our background. I couldn't find a way to integrate to `containerBackground` API, [since SwiftUI requires to present it within ZStack](https://developer.apple.com/documentation/widgetkit/accessorywidgetbackground?changes=_5). There were questions [related to this on Apple forums](https://developer.apple.com/forums/thread/733200). Likely that there's a solution I couldn't identify.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
