### ISSUE TITLE
Reader Improvements: Show stats in the Tag stream header

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21679]
This is optional.

```[tasklist]
### Tasks
- [ ] Add an endpoint to get the number of posts and sites for a tag.
- [ ] Parse the tag stats and store them locally.
- [ ] Show the stats in the tag stream header.
```
