### ISSUE TITLE
🍎 Add a new Domain

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#21781]
```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21778
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21779
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21780
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21775
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21782
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/21978
```
