### ISSUE TITLE
Docs: Refresh README

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#21824]
Refresh the [README](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/README.md) for the project.

```[tasklist]
### Tasks
- [x] Update cloning instructions to [include all methods](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository)
- [x] Remove mention of "M1-based Mac support is coming"
- [x] Update Xcode version to be a minimum of [`.xcode-version`](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/.xcode-version)
- [x] Remove outdated badges
- [x] Add "Website URL" field to setup instructions
```
