### ISSUE TITLE
Posts & Pages: Defects

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21900]
### Existing
- [x] The app crashes due to incorrect table view implementation in WPTableViewHandler https://github.com/wordpress-mobile/WordPress-iOS/issues/21298
- [ ] Table view deselects the selected posts on didSelect instead of on willAppear when returning from the details screen
- [x] When you add a new page, the Published list doesn't update automatically 
- [ ] When you tap on a trashed post, the cell highlights (not OK) and nothing happens (OK)
- [ ] When you open a post for editing the tapped cells changes layout and show "has local changes" before you even make any changes
- [ ] The My Site tab becomes unresponsive if you cancel search by tapping on the My Site tab (production issue)
- [ ] The title line limit for posts is unlimited in snackbars
- [x] Some actions do nothing if reachability reports "not reachable" as a false positive
- [x] Snackbar when post is deleted/trashed does not change for posts vs pages and trashed vs deleted
- [ ] When you delete and restore a post, the edited date is not restored and still matched the date the post was trashed
- [ ] When you move Published post to "Draft", it shows "Publish" action
- [x] 404 on "View" action in Trashed section https://github.com/wordpress-mobile/WordPress-iOS/issues/14428
- [x] Excerpts display empty lines resulting in visually incorrect cell line height (https://github.com/wordpress-mobile/WordPress-iOS/pull/21980)

### Web parity
- [ ] When you set a subpage as a homepage or posts page, it's not moved to the top of the screen like on wp.com
- [x] No way to restore a posts page to be a regular page like on wp.com #21963
- [ ] Notice title label has unlimited number of lines

### New / Regressions
- [x] The app crashes if you permanently delete a post from search and the main list has any tab other that "Trashed" open
- [x] The search screen shows authors of the posts even if "Me" is selected or a blog has only one author #21953 
- [x] The search screen fails to suggest tag filters unless you visit the Tags screen first to load them
- [x] Incorrect layout of the cells in the landscape mode (image sticks out)
- [x] Incorrect filter tab bar layout in landscape mode
- [x] Incorrect placement of the search bar in iPad https://github.com/wordpress-mobile/WordPress-iOS/issues/21936
- [x] Incorrect layout of the state views in the list
- [x] Post footer is displayed incorrectly (see https://github.com/wordpress-mobile/WordPress-iOS/pull/21907#pullrequestreview-1703849162 for more details)
- [ ] Posts and Pages (entities) get updated and force the update of the cell even if nothing changes on the backend, forcing the cells to reload and deactivating the selected swipe actions
- [x] Pages in the search results list are not getting updated after changing the attributes https://github.com/wordpress-mobile/WordPress-iOS/pull/21967#pullrequestreview-1714724033

### Enhancements
- [x] Consider collapsing the page action section in the context menu #21957

**Comment by kean** [comment]
> Posts and Pages (entities) get updated and force the update of the cell even if nothing changes on the backend, forcing the cells to reload and deactivating the selected swipe actions, context menus

This actually only affects the swipe actions, so I'd say it's OK to ship with this known defect. There doesn't to be appear any super quick fixes.

**Comment by kean** [comment]
I'm going to close this since there are no more regressions or known issues in the new code. Any new issues found will be tracked separately.
