### ISSUE TITLE
Reader 4.4 Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2201]
### Content
- [x] #1978 - Block/report a blog from the reader 
### Comments
- [x] #46 - Enable some sort of paging or infinite scroll to show all comments. 
- [x] #1360 - Highlight comments from the post author
### Misc
- [x] #2193 - Back button on detail view controller is inconsistent 
- [x] #2182 - Follow tap target is too large
