### ISSUE TITLE
Reader: Navigation dropdown menu

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#22204]
Refs:
- pcdRpT-4tr-p2
- zQnohyMpLzBzQ5jzMMKni3-fi-2848_17970

## Screenshots

| | |
|-|-|
| <img width="394" alt="Screenshot 2023-12-11 at 12 26 33 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/332a44cf-ac18-4d6f-960c-e28693d3e4e2"> | <img width="397" alt="Screenshot 2023-12-11 at 12 27 15 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/a9919161-e446-41d0-9f11-af9e56004328"> |
| <img width="397" alt="Screenshot 2023-12-11 at 12 26 42 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/091e4bd1-3db5-47a5-bfa3-bf95562dea3e"> | <img width="396" alt="Screenshot 2023-12-11 at 12 26 53 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/25b5377e-2b4c-48c5-949c-32b19224f917"> |

## Tasks

```[tasklist]
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/22206
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/22208
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/22224
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/22352
```
