### ISSUE TITLE
Reader: Site and tag filters

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#22205]
Refs:
- pcdRpT-4tr-p2
- zQnohyMpLzBzQ5jzMMKni3-fi-2848_17970

## Screenshots

| | | |
|-|-|-|
| <img width="397" alt="Screenshot 2023-12-11 at 12 27 15 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/46a34a26-3fae-45ec-bda0-d709093460e6"> | <img width="397" alt="Screenshot 2023-12-11 at 12 31 48 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/493d986f-0a9f-42d9-91b6-8efbc9b070dc"> | <img width="397" alt="Screenshot 2023-12-11 at 12 32 01 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/c69bf529-2869-4bb3-aba0-d16f8c538ffe"> |

| | |
|-|-|
| <img width="402" alt="Screenshot 2023-12-11 at 12 31 22 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/c60e25ef-1e6b-4d18-85d5-5c5d1ca130a1"> | <img width="399" alt="Screenshot 2023-12-11 at 12 31 32 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/67ca9b90-2415-4009-b417-ad99c642264d"> |

## Tasks

```[tasklist]
- [x] Reader: Create site and tag pill buttons
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/22211
- [ ] #22426
- [x] Reader: Filter content based off site or tag selection
- [x] Reader: Update pill display when filter is selected
```
