### ISSUE TITLE
Reader: Create site and tag menu sheet

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#22211]
Update the designs for the blog and tag filter sheets.

<img width="252" alt="Screenshot 2023-12-22 at 22 12 20" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/2d4d4dd0-c37f-40fa-bdf8-a75a4f98eda7"> | <img width="248" alt="Screenshot 2023-12-22 at 22 12 12" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/3ebbee44-eb91-4cc1-9ddd-5199b5f34319">
-|-

```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/22273
- [x] Reset and reload filter list data immediately after switching to a stream (ongoing)
- [x] Refactor Reader filter state management
- [x] Add filter buttons beside the stream switcher
- [x] Animate filter button state changes
```
