### ISSUE TITLE
WordPress Share Extension

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#2231]
Let's implement a WordPress Share Extension:

- [x] #4877: Provisioning Profiles
- [x] #4873: Shared Metadata: Token / Primary Site
- [x] #4874: The user should be allowed to pick the target blog in which the contents should be posted
- [x] #4876: MVP should only support text
- [x] #4875: Provide a sad christmas for self hosted and logged off users
- [x] #4897: Post Status Picker
- [ ] #4898: UX Look & Feel

**Comment by chantalcoolsma** [comment]
I would love to see a sharing extension to quickly post photos from you iOS device to your blog. For example:

1. Take photo
2. Open photos app
3. Retouch your photo
4. Tap sharing and choose WordPress
5. Ability to enter a title (for the post) and choose a category (and the site if more selfhosted sites are added)
6. Publish

These steps should create a post, upload the photo to the media library, insert the photo in the post, set category and publish it.

**Comment by sendhil** [comment]
Thanks for the ping @chantalcoolsma - a sharing extension is definitely on or radar. I don't have a timeline for you at the moment but hopefully at some point in the next few months.

**Comment by sealfur** [comment]
@sendhil any update on this?

**Comment by sendhil** [comment]
@sealfur - @astralbodies is going to take a stab over the next few weeks.

**Comment by astralbodies** [comment]
I will crush this. :smile:

**Comment by sendhil** [comment]
I'll take a screenshot of that comment so you can't delete it ;).

**Comment by astralbodies** [comment]
I know I'll be eating my own hair after I work on this - the share extension API still sucks even in iOS 9.

**Comment by chantalcoolsma** [comment]
Good luck :+1:

**Comment by Ipstenu** [comment]
You're doing Dog's work, son.

**Comment by rachelmcr** [comment]
We received a recent app review that also requested a sharing extension, in case there was any question about the demand for it. ;)

>Love to use the app to post photos to my blog.  Just wish there was a sharing extension so I could upload right from the photos app and save a few taps.

**Comment by m** [comment]
@astralbodies can you pair up with someone on this?

**Comment by astralbodies** [comment]
@m Definitely - it ended up getting deferred again because of shifting around of people but I really want to make it work.

**Comment by m** [comment]
It's the most handy glue on iOS.

**Comment by SergioEstevao** [comment]
@astralbodies I can help you out if you want. I've recently had experience with Share extensions.

**Comment by astralbodies** [comment]
@m Agreed - I'll consort with @jleandroperez this week and we'll see what we can do to finally knock it out!

**Comment by astralbodies** [comment]
@SergioEstevao We'll talk this week :grin:

**Comment by astralbodies** [comment]
First iteration of Share extension has been merged! This should make its way into WPiOS 6.2. 

Thanks everyone for all of the input and support! :+1:
