### ISSUE TITLE
Reader: Add or update analytic events for filter sheet and dropdown menu

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#22417]
### Update

- [x] `reader_filter_sheet_displayed` to include a `source` parameter. `source` can be `blogs|tags`. ([Android ref](https://github.com/wordpress-mobile/WordPress-Android/issues/19925))

### Add

- [x] `reader_dropdown_menu_opened` when the dropdown menu is opened ([Android ref](https://github.com/wordpress-mobile/WordPress-Android/issues/19906))
- [x] `reader_dropdown_menu_item_tapped` when a menu item is tapped with an `id` parameter. `id` can be `discover|following|saved|liked|a8c|list` ([Android ref](https://github.com/wordpress-mobile/WordPress-Android/issues/19906))
