### ISSUE TITLE
Offline Mode: Synchronous Publishing

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22579]
## Tasks
- [ ] Show spinner in "Publish" button in the pre-publishing sheet 
- [ ] Success
   - [ ] Show a success toast message
   - [ ] Dismiss editor
   - [ ] Switch to "Published" tab
- [ ] Error
   - [ ] Show an error toast message
   - [ ] Re-enable "Publish" button in the pre-publishing sheet
