### ISSUE TITLE
Offline Mode: Draft Post States

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22578]
## Tasks

Design ref: dF2idcugV3w5nNo3xtlSIL-fi-0_1

### Uploading (Updating, Deleting)

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/d42f9774-614b-4607-bf52-37b0f3db7a12" width=400>

- [x] Hide context menu, show an indicator
- [x] Disable user interaction, gray out cell
- [ ] Disable long press

### Uploading Media

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/18299bf4-455d-44f2-852c-96acbef5a545" width=400>

- [ ] Hide indicator, show a circular progress view with the ability to stop the upload
- [ ] When the media upload finishes, show the activity indicator again
- [ ] If the user cancels the upload, go into the "Upload Failed" state

### Upload Failed

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/b9e8adbe-eee5-4ee1-8452-b4e46cc6224f) | ![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/7b6d3a57-5ec0-4059-94c6-b259c37c548e)
-- | --

- [ ] Update status to "Upload failed"
- [ ] Hide indicator, show context menu
- [ ] Show failure indicator next to the context menu
- [ ] Context menu should only display actions related to resolving an error
- [ ] Enable user interaction
