### ISSUE TITLE
Offline Mode: Post Settings

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22584]
## Tasks
- [x] Send only the modified fields in the POST request
- [ ] [Stretch Task] Define a different merge policy for each field depending on the field type. For example, tags should be merged automatically and should not use “overwrite using local” policy

**Comment by kean** [comment]
Development plan:

- [] Add `PostSettingsViewModel` to make sure nothing gets changed/save in Core Data until you save
- [] Add "Cancel" and "Done" buttons to Post Editor to allow the user to safely undo the changes if they change their mind
- [] Update WordPressKit to support passing individual fields when updating a post. Make sure this API could also be used later for trashing, moving posts to draft, and other changes.
- [] Update `PostSettingsViewModel` to use the new API
- [] (Optional) Update the UI to use SwiftUI
