### ISSUE TITLE
Offline Mode: Editing Posts

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22580]
## Tasks
- [ ] If the local revision was fetched more than 20 seconds ago, fetch the latest version before opening the post
- [ ] If the app fails to refresh the post when opening the editor, show the stale version
- [ ] Make sure the deep-linking for post editing works correctly

## Notes
- When you update the post content, the only field in the POST request should be its content. If you change post settings, only changed field should be sent.
