### ISSUE TITLE
Offline Mode: Autosave

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22585]
## Tasks

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/9e4de8f5-fdb8-4ae7-85d0-bd9fa2cf8271" width=200>

- [ ] Create an autosave and upload it when
  - [ ] A user edits a published post and taps "Back" without updating the post
  - [ ] The app crashes
- [ ] Always suggest the latest version of the autosave (overwrite local autosave if remote autosave is more recent)
- [ ] Remove the “You’ve made unsaved changes to this post” label
- [ ] Remove the alert
- [ ] Show a notice indicating the autosave, and the option to apply it
- [ ] If a user taps "Apply", load the content the post of the autosave and enable the "Update" button
