### ISSUE TITLE
Navigation bar improvements

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#22770]
This issue groups multiple visual issues related to the Reader navigation bar.

```[tasklist]
### Tasks
- [x] Bug: when transitioning to "Subscriptions", the navigation button starts from a shifted position. p1708516962196869-slack-C05N140C8H5. Resolved in #22808
- [x] Animate the filter chip buttons from below the navigation button. Ref: p1708517123829739-slack-C05N140C8H5. Resolved in #22808.
- [x] Reintroduce the [scroll-to-top gesture](https://developer.apple.com/documentation/uikit/uiscrollview/1619421-scrollstotop#) of tapping the status bar for the main Reader view. Addressed via #22771
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by dcalhoun** [comment]
@dvdchr I added a task to "Reintroduce the [scroll-to-top gesture](https://developer.apple.com/documentation/uikit/uiscrollview/1619421-scrollstotop#) of tapping the status bar for the main Reader view" that is no longer available after the Reader redesign, but please let me know if you'd rather me move that to a separate issue. 🙇🏻

**Comment by dvdchr** [comment]
That's perfect @dcalhoun, thank you! 🙏

**Comment by dvdchr** [comment]
Moved the "Improve navigation bar animation" to #22816 since it's a potentially larger task. 
Closing this issue as all the tasks have been checked off.
