### ISSUE TITLE
Update outdated pods

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#22940]
These tasks are from the [Log Outdated Pods](https://buildkite.com/automattic/wordpress-ios/builds/21353#018e9ab6-f8b0-4ac2-a649-c9a417a7d47f) step of the Code Freeze for 24.6. The latest version will likely be higher by the time you start working on it.

```[tasklist]
### Tasks
- [ ] Alamofire 5.9.0 (latest version 5.9.1)
- [ ] Automattic-Tracks-iOS 3.3.0 (latest version 3.4.0)
- [ ] CropViewController 2.5.3 (latest version 2.7.2)
- [ ] Down 0.6.6 (latest version 0.11.0)
- [ ] OCMock 3.4.3 (latest version 3.9.3)
- [ ] Reachability 3.2 (latest version 3.7.6)
- [ ] Sentry 8.21.0 (latest version 8.24.0)
- [ ] SVProgressHUD 2.2.5 (latest version 2.3.1)
- [ ] ZendeskCommonUISDK 6.1.4 (latest version 9.0.0)
- [ ] ZendeskCoreSDK 2.5.1 (latest version 5.0.0)
- [ ] ZendeskMessagingAPISDK 3.8.5 (latest version 6.0.0)
- [ ] ZendeskMessagingSDK 3.8.5 (latest version 6.0.0)
- [ ] ZendeskSDKConfigurationsSDK 1.1.11 (latest version 4.0.0)
- [ ] ZendeskSupportProvidersSDK 5.3.0 (latest version 8.0.0)
- [ ] ZendeskSupportSDK 5.3.0 (latest version 8.0.0)
- [ ] ZIPFoundation 0.9.16 (latest version 0.9.19)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
