### ISSUE TITLE
Reader 4.6 Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2490]
### Comments
- [x] #2395 Reader: Move comments out of post detail and into their own controller -
- [x]  #2019 Simplify reader post detail to reduce the number of protocols it implements. -
- [x] #2489 Tapping the comment icon should take the user to the list of comments -
- [x] #1924 Enable comment likes in the Reader 
### Image/Media Improvements
- [x] #2217 Featured image discrepancies on reader if no featured image is set -
- [x] #2338 In the reader detail, tapping a featured image should open the image detail view. -
- [x] #2252 Reader: Better handling of embeded content
- [x]  #2212 Add support for displaying Cloudup video
### Housekeeping
- [x] #1967 WPContentView is deprecated. Replace it in any remaining places where its used 
### Misc Finesse
- [x] #2326 Reader: Make "Freshly Pressed" always the default feed if one is not already selected.
- [x] #2336 Action button spacing is not consistent
- [x] #2224 's' character is not consistent in the reader's body text
