### ISSUE TITLE
Reader 4.7 Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2760]
- [x] #2168 Reader doesn't show images in comments
- [x] #2699 Add mention suggestions to reader post detail -
- [x] #2657 Use UUIDs instead of Object IDs for persistant topic references -

**Comment by aerych** [comment]
List edited.
#2754 Refactor action buttons :  deferred to the forthcoming UI changes
#1982 Reader doesn't remove posts from unfollowed blogs:  deferred while we consider other enhancements for syncing.
