### ISSUE TITLE
Notifications: Detach Comment Actions from Comment Text

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3268]
#### Description:
Comment Notifications will get extra details, indicating if the user already sent a reply. Tapping over this new element will push the Comments Interface.

#### Details:
Notifications consist of a collection of **Notification Blocks**, which are grouped into **NotificationBlockGroup**, and each **BlockGroup** translates into a single **UITableViewCell** instance.

Comment-Y Notifications (at this moment) consist of two blockGroups: a **Header** and the **Comment** itself.

The purpose of this issue is to ensure that the *Comment Actions* are always rendered at the bottom of the view, always.

#### Subtasks:
- [x] Add a new NoteBlockGroup type, called 'Actions', and append it at the end of the **body blocks**.
- [x] Split **NoteBlockCommentTableViewCell** in two. Now the Actions will be rendered in a different cell.
- [x] Update **CommentsViewController** accordingly, since it's subclassing Notifications UI.
- [x] Implement a mechanism to grant us granular control over which cell gets a bottom separator.
- [x] Make sure that the new block pushes the native comments interface.

#### Web Mockup.

![shot](https://cloud.githubusercontent.com/assets/1195260/6196588/680b4eaa-b3b8-11e4-9c7f-b5e3513df85d.jpg)
