### ISSUE TITLE
Enable Jetpack REST for all users

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3627]
On debug/internal builds this is already enabled. When you log in to WordPress.com, all of your Jetpack sites appear on the 'My sites' list.

**Done**
- [x] #3635 One list for all sites
- [x] #3141 Sites from two different wpcom accounts can appear in the site list.
- [x] Review tests at #2605
- [x] #3731 Add more debugging tools and support options
- [x] #3700 `isWPcom` is `YES` for Jetpack sites
- [x] #3838 Fall back to local previews if we don't have credentials
- [x] #3741 Add an option to disable Jetpack REST.
- [x] #3873 Make new Jetpack sites appear on the list (it only reloads on launch so far).
- [x] #2287 Check if it works or we need to add an update warning for older versions of Jetpack
- [x] Fix error saying that the API is disabled

**In Review**

**Must have**

**Nice to have/Maybe**
- [ ] Make preview work without a password
- [ ] ~~"Migrate users": if the blog list is going to change when upgraded, let the users know why~~

**Comment by koke** [comment]
> Check if it works or we need to add an update warning for older versions of Jetpack

In #3681 we require 3.4.3 to connect, but we still need to check the version for existing sites when we switch them from XML-RPC to REST

**Comment by koke** [comment]
> "Migrate users": if the blog list is going to change when upgraded, let the users know why

We've already changed the list in #3647. There should be no difference in the UI whether Jetpack is using REST or XML-RPC

**Comment by koke** [comment]
I've tried disabling JSON API on a site, then adding it to the app. The moment you go to stats and log into WordPress.com, the site switches to using REST, stats work, but everything else returns an error.

Enabling the API by default is in the checklist, but I'm worried that there might be other REST-related errors that would make the app stop working just because it's connected to Jetpack. I'm considering adding an option in Settings to disable REST. We should try to figure out what's broken through Support, but at least users won't be stuck with a non-functioning app while we work on a fix
