### ISSUE TITLE
Skip Jetpack setup on NUX

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3628]
Let's make a site work without needing a second login. With #3627, if users log in with the wordpress.com credentials, all of their sites will be there. But we still need to handle what happens if they add a self hosted site.
- [x] #3671 Skip setup after login
- [x] #3788 Remove Jetpack from site settings
- [ ] Implement per-site OAuth2 token generation in Jetpack
- [ ] #3761 Fallback for older Jetpack installs: use a single Login screen
- [ ] #3761 Update prompts to log in to wp.com in Notifications
- [ ] Review #1468: installing Jetpack from the app doesn't show stats

**Comment by frosty** [comment]
Closing as most of this work is complete and #3761 seems to cover remaining improvements to Jetpack login.
