### ISSUE TITLE
Reader: UI Refresh Punch List

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4035]
Master issue for wrangling various tasks related to the Reader UI refresh. New tasks will be added as they are defined. 
- [x] Refresh reader cards UI #4032
- [x] Refresh post list UI #4093 
- [x] Refresh reader detail UI #4033
- [x] Refresh reader menu #4094 
- [x] Refresh reader comments UI #4034

Closes or references:
#### Cards
- Reader: Move follow toggle to stop inadvertent unfollowing https://github.com/wordpress-mobile/WordPress-iOS/issues/3462
- Tweak appearance of logged out like button https://github.com/wordpress-mobile/WordPress-iOS/issues/3410
- Refactor Action Buttons https://github.com/wordpress-mobile/WordPress-iOS/issues/2754
- Show primary tag in Reader posts https://github.com/wordpress-mobile/WordPress-iOS/issues/1563
- Add author information to reader for multi author blog https://github.com/wordpress-mobile/WordPress-iOS/issues/1104
- Better browse site tap target https://github.com/wordpress-mobile/WordPress-iOS/issues/3935
#### List
- Improve “You’re not following any blogs” message https://github.com/wordpress-mobile/WordPress-iOS/issues/34
#### Details
- Full screen reader detail #139  
#### Menu
- Manage lists from within app #2728
- Sunset popular tags / recommended blogs #3851
#### Other
- Migrate Reader Layout to Storyboards https://github.com/wordpress-mobile/WordPress-iOS/issues/2492
- Change reblogged posts to match how they are displayed by the desktop reader https://github.com/wordpress-mobile/WordPress-iOS/issues/2199
- Native reader seems to ignore the amount of content a post author wants to show in the reader https://github.com/wordpress-mobile/WordPress-iOS/issues/1113
- Migrate Table Views #2491

**Comment by aerych** [comment]
Comps:
https://cloudup.com/iUs35k4xJxi
