### ISSUE TITLE
Calypsoification - Delete Site

### ISSUE THREAD

**Issue by alexcurylo** [wordpress-mobile/WordPress-iOS#4570]
Task list for implementing the Calypso Delete Site features:

- [x] Add API service to delete site where available (#4723)
- [x] Add 'Advanced' UI section with Delete Site to Settings controller (#4751)
- [x] Add Export Content functionality as available (#4951)
- [x] Add Start Over guidance as available (#4751)
- [x] Add guidance for sites with purchases (#4841)
- [x] Implement analytics (#4950, wordpress-mobile/WordPressCom-Analytics-iOS#53)
