### ISSUE TITLE
Plans m1: Show plans list

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4744]
First milestone towards Plans:

- [x] #4747 Add a top-level Plan menu item (under Stats, to match Calypso) (@koke)
- [x] #4758 Retrieve the user’s current plan to determine what we show to them (@frosty)
- [x] #4772 Display a top-level list of Plans (@koke)

## Mockups

Menu item:

![screen shot 2016-02-01 at 18 28 46](https://cloud.githubusercontent.com/assets/8739/12725206/be60ae7a-c911-11e5-939f-659d5afb125a.png)

Plans list:

![screen shot 2016-02-01 at 18 28 52](https://cloud.githubusercontent.com/assets/8739/12725210/c39215d2-c911-11e5-8881-24a979269ebb.png)

**Comment by koke** [comment]
Uploaded updated mockups
