### ISSUE TITLE
People Management iOS - Master Issue

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5030]
This is a master issue to track the individual pieces of adding full people management to the application. This issue will be updated with links to subordinate issues.

- [x] List all users of a site #4384
- [x] Ability to update users (#5175)
- [x] Ability to delete users (#5288)
- [x] List all Readers of a site (#5174)
- [x] Ability to create invites for WordPress.com sites (#5381)
- [x] Users / Followers Infinite Scroll (#5502)

Android: https://github.com/wordpress-mobile/WordPress-Android/issues/3901

**Comment by jleandroperez** [comment]
Update: As discussed in the weekly hangout, removing, for now at least, Bulk Management + Accept Invites tasks.

cc @astralbodies @hypest @oguzkocer

**Comment by astralbodies** [comment]
Closing this master task.
