### ISSUE TITLE
Plans v1 Checklist

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#5167]
The first released version of plans should allow a user to:
- view the active plan of any WordPress.com blog
- view a list of available WordPress.com plans
- purchase one plan for one blog which is currently in the Free plan 

Questions:
- do we allow renewing an existing plan? only if it was purchased with IAP?
- we only allow purchasing for one blog to simplify the process. If a user signs out and signs in with a different wp.com account, the app will still have a receipt with a valid transaction. How do we handle this?
- we don't have a way to test refunds, but we can try testing them as soon as v1 is released in the app store, and verify our assumptions.

I'm using this as a checklist for the remaining tasks and as a final testing plan:
- [ ] Update IAP products with screenshots and final copy and submit them for review
- [x] Disallow purchases if a user can't make payments (`SKPaymentQueue.canMakePayments`)  #5183 
- [x] Deferred payments should work ([Ask to Buy](https://support.apple.com/en-us/HT201089)) #5033
- [x] Disallow purchases for other blogs if we have already purchased a plan for one blog #5033
- [x] Handle other non-successful states of transactions #5033
- [ ] Verify receipts in WordPress.com and make the actual purchase #5035 
- [ ] Unit test all the transaction and purchasing logic
- [x] Plan/Feature text coming from the API is translated #5280
- [x] Make sure view controller restoration is working #5346
- [ ] Add analytics (#5370)

**Comment by rachelmcr** [comment]
@koke Do we need to keep this and https://github.com/wordpress-mobile/WordPress-iOS/issues/5035 open, or is it ok to close them until we have in-app purchases on our roadmap again?

**Comment by koke** [comment]
Fine to close, I don't think IAP is anywhere near the roadmap at this point 😬
