### ISSUE TITLE
Add new property showing "where" a user is attempting sign in to Helpshift/logs

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#5308]
Per @rachelmcr
> Sometimes it can take a little back and forth before we realize that a user is having trouble on the Jetpack login screen, rather than the WordPress.com/self-hosted login screens. If we could quickly/easily distinguish between them, it could help speed up the support process.

## Todo:

 Add the following tags:
- [x] `origin:wpcom-login-screen` for the WordPress.com login screen
- [x] `origin:wporg-login-screen` for the self-hosted login screen
- [x] `origin:jetpack-login-screen` for the Jetpack login screen (on the stats and notifications screens in the app)
- [x] `origin:signup-screen` from #6361
- [x] `origin:login-screen` for screens that don't have a known login type (such as the very first screen of NUX)

_Edited by @nheagy on Jan 23_

**Comment by rachelmcr** [comment]
Let's expand/define this issue a bit more. Currently, we add metadata to Helpshift issues to show that an issue came from a failed login (`Source: Failed login`). However, there are a couple drawbacks:

- We can't differentiate between failed WP.com, self-hosted, and Jetpack logins
- We can't build any automations in Helpshift based on metadata

I propose the following changes:

- Use tags instead of metadata to identify the source of the failed login (this also makes iOS consistent with how Android does it)
- Use different tags depending on where the user tried to log in:
  - `origin:wpcom-login-screen-error` for the WordPress.com login screen
  - `origin:wporg-login-screen-error` for the self-hosted login screen
  - `origin:jetpack-login-screen-error` for the Jetpack login screen (on the stats and notifications screens in the app)

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/4912

**Comment by bummytime** [comment]
@rachelmcr Seems like a plan. Source: 

https://github.com/wordpress-mobile/WordPress-iOS/blob/89882dd2d751068961c0a74bc4b6c387ae40d9bb/WordPress/Classes/ViewRelated/NUX/NUXAbstractViewController.swift#L231
