### ISSUE TITLE
iPad Refresh Master Issue

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5576]
This issue will serve as a high-level overview of the iPad Refresh. The goal of the fresh is for the iOS app to feel like it utilizes the larger screen in a way that improves the usability of the app, but also stays with the Calypso feel.

**General Issues**
- [x] iPad Refresh: Consistent Header/Footer views on iPad (and iPhone) (#5536, #4128) @kurzee
- [x] Normalize modal presentation styles across iPad (sheet vs fullscreen) (#5599) @frosty
- [x] Remove use of `WPTableViewSectionHeaderFooterView` in Plans. (#5643) @frosty 
- [x] Search bars as `UISearchController` (#4343) @frosty
- [x] Editor: Blog selector modal should be searchable (#5677) @frosty
- [x] Post/Pages: Change top bar color for iPad filter popover (#3748)
- [x] iPad Reader width bug: (#5082)
- [x] Fix layout of Manage Share Button: (#5428)
- [x] Sometimes footer view animates over non animated cells. (#3844) @frosty
- [x] iPad Pro Full Sized Keyboard Support (#5870) @kurzee
- [x] Resolve unsatisfiable constraint with `CircularImageView` (#5638) @jleandroperez 
- [x] A few strange iPad Pro screenshots to investigate (#5842)
- [x] Stats: Refactor the Jetpack connection screen to use stackviews and autolayout (#6389) @bummytime

~~- [ ] Allow inline editing of single-field settings (such as First Name, Last Name)~~

 
**Readability Issues** 

We need to ensure and enable the best readable guideline practices for iPad. This allows for smooth support of all view sizes and form factors, full-screen, split-view, multi-tasking, etc. The current work is on  [feature/readability](https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/readability) and requires the updated WordPress-iOS-Shared pod branch on [feature/shared-readability](https://github.com/wordpress-mobile/WordPress-Shared-iOS/tree/feature/shared-readability).

Tasks (pending merges):
- [x] Drop `WPTableViewCell` and its margins hack @kurzee
- [x] Drop `WPTableViewSectionHeaderFooterView` (#4128) @kurzee
- [x] Refactor `BlogDetailHeaderView` for better constraints along readable content guide. @kurzee
- [x] Refactor `WPTextFieldTableViewCell` to use auto-layout and readable margins @kurzee
- [x] Horizontal padding and view widths on iPad (#5589, #2491) @kurzee

Remaining Readability tasks:
- [x] Posts (https://github.com/wordpress-mobile/WordPress-iOS/pull/5830, https://github.com/wordpress-mobile/WordPress-iOS/issues/2491)
- [x] Pages (https://github.com/wordpress-mobile/WordPress-iOS/pull/5830, https://github.com/wordpress-mobile/WordPress-iOS/issues/2491)
- [x] Reader
- [x] Reader Detail
- [x] Reader Comments
- [x] Menus
- [x] NUX
- [x] Notifications (https://github.com/wordpress-mobile/WordPress-iOS/issues/5782)
- [ ] Deprecate `WPTableViewFixedWidth` in WPiOS-Shared @kurzee
- [ ] Post Settings > Publish Date
- [x] Search bars in blog list, selector, themes and posts.
- [x] Comments
- [x] Settings > Related Posts
- [x] Reader > Followed Sites (https://github.com/wordpress-mobile/WordPress-iOS/pull/5792#issuecomment-235706730)
- [x] People
- [x] Sharing readability.
- [x] Post Settings readability, feature image and location preview.
- [x] ~~Domains.~~ (Domains removed #5622 )

**Comment by kurzee** [comment]
Added: https://github.com/wordpress-mobile/WordPress-iOS/issues/5082

**Comment by kurzee** [comment]
Added: https://github.com/wordpress-mobile/WordPress-iOS/issues/4343

**Comment by kurzee** [comment]
Added #5589

**Comment by kurzee** [comment]
@frosty I've added several remaining readability tasks you're free to dive into on the `feature/readability` branch, if you want. Some of those we might end up getting by without touching, depending on our split-view approach. I'll pick that work up again after I'm back from AFK, unless something changes.
