### ISSUE TITLE
Notifications: iOS 10 Master

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#5895]
### Networking Layer:
- [x] #6086: Simperium Sunset
- [ ] #6164: PingHub
- [ ] #6174: Improve Sync

### iOS 10 Punch List!
- [ ] #5892: UserNotifications.framework Support
- [ ] #5893: Notifications System Extension
- [ ] #2036: Interactive Replies
- [ ] #5894: InApp Presentation
- [ ] #4452: Peek + Pop
### Improvements
- [ ] #6140: Up / Down Arrows
- [ ] #6177: Pull to Refresh Delay
- [ ] #5782: Readability
- [ ] #6004: Adaptivity
- [ ] #6003: Remember Reply Text
- [ ] #6005: Unit Tests
- [ ] #6025: User Cell
### Pendings
- [x] #6155: Review State Restoration
- [ ] #5638: CircularView Constraint Errors
- [ ] #5781: Fix Badges on the 4s
- [ ] #6006: iPad Top Padding
- [ ] #6013: Review / Fix iPad UX, if needed
- [ ] #5572: Spacing Inconsistencies
- [ ] #5025: Swipe to mark as read

**Comment by jleandroperez** [comment]
Closing this ticket in favor of [Notifications's GitHub Project](https://github.com/wordpress-mobile/WordPress-iOS/projects/1).
