### ISSUE TITLE
Second pass tab bar fixes/improvements

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#603]
This issue is for the inevitable list of miscellaneous changes we still need in order to make the tab bar shippable:
- [x] Add noticons for the table view you see when you browse to a blog (Posts, Comments, etc).
- [x] Finalize tab bar icons, copy, and localization.
- [x] Finalize iPad margin width.
- [x] Review all potentially clashing bottom bars.
- [x] Remember state of view controllers (#459).
- [x] Improve what you see while waiting for initial sync (#376).
- [x] Display something in the Reader and Notifications tabs for non-wpcom users. (Notifications #720)
- [x] Finalize tab order.
- [x] Ensure all AppDelegate navigationController dependencies are dealt with (#620).
- [x] Find a home for Settings.
