### ISSUE TITLE
Media Library - Master Issue

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6817]
This issue serves as the master issue for adding standalone Media Library functionality to the app. The goal is feature parity with the Android app, allowing users to view and manage their media libraries independently of the editor.

#### Features

- [x] Add Media Library item to blog details list, feature flagged
- [x] Display simple collection view layout of user's media library (using existing functionality in Media Picker project)
- [x] View items fullscreen, including title, caption, description, filename, file type and size, and upload date.
- [x] Edit item details and update remote
- [x] Copy item URL to clipboard
- [x] Delete item
- [x] Select multiple to delete in grid view
- [x] Search items by filename
- [x] Upload images. Initial upload is incremented with a blocking UI. Async will come later.

Filtering is currently on hold as we decide the best way to surface it to users.
