### ISSUE TITLE
Accessibility: Improve dynamic type support across the app

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7236]
We have added support for Dynamic Type partially in https://github.com/wordpress-mobile/WordPress-iOS/issues/7068

We still need to work on:

- [x] Me->App Settings -> Media Upload Cell
- [x] Notifications #8700
- [x] Blog -> People (Dynamic type implemented but cells doesn't resize) #8723
- [x] Blog -> People -> Detail #8744
- [x] Blog -> People -> Invite #8756 
- [x] Blog -> Menus #8886
- [x] No Results View #8902
- [ ] Stats
- [ ] Notification details

**Comment by elibud** [comment]
Updating with some comments from @mattmiklic 

I think we'd want to use body sized text, in the system font, for both Notifications and Comments in the apps.
In notifications, we might use body for the top line of a comment notification, and subhead for the excerpted text below (and caption) for anything smaller, like dates.

**Comment by mattmiklic** [comment]
I thought about this a bit more today and I'm thinking that Headline might make more sense than Body for items in the notifications screen -- in this context it's a list of notifications, not the full content of a post. Using Headline would make it easier to scan the list at the largest sizes. We'd want to use the Body size when you are viewing the full text of a comment notification.

**Comment by etoledom** [comment]
We will start working on this as part of the [Awesome Accessibility](https://github.com/wordpress-mobile/WordPress-iOS/projects/12#column-2228194) project

**Comment by etoledom** [comment]
We fixed most of these issues in the  [Awesome Accessibility](https://github.com/wordpress-mobile/WordPress-iOS/projects/12#column-2228194) project.

What was left, the `Stats` and the `Notification detail` sections were too complex to be fixed as part of a bigger project.

I will mark this issue as solved and create a new one with each of those sections still to be fixed.
