### ISSUE TITLE
Login rework - Master issue

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#7272]
We are reworking the login flows in the app and this ticket serves as the Master ticket. It will progressively get broken down into more details tasks with links to issues or PRs.

### Feature development
- [x] Implement the epilogue screen. (#7066, #7127)
- [x] First pass at new visual design (#7253)
- [x] Add self-hosted support to epilogue (#7149, #7150)
- [x] Add prologue screen (#7397)
  - [x] Test lottie animations (tested locally)
- [x] New screens:
  - [x] Magic link screens & illustrations (#7423)
  - [x] Safari/keychain passwords working well (#7520)
  - [x] Move password to own screen for wpcom logins (#7465)
  - [x] Break up self-hosted login screen into screens for each step (#7418)
  - [x] Add new error/help style for site entry screen (#7523)
  - [x] Update design for 2fa screen (#7461)
  - [x] "Connect another site" button (https://github.com/wordpress-mobile/WordPress-iOS/pull/7536)

### Design Feedback & Issues
- [x] Changes based on feedback from @mattmiklic (#7547, #7554)
- [x] elipses in long text on secondary text buttons (https://github.com/wordpress-mobile/WordPress-iOS/pull/7535)

### Issues, Regressions, and Cleanup
- [x] Done button on epilogue not always functional (#7270)
- [x] 1password not submitting form automatically anymore
- [x] Epilogue should only lists sites associated with just-added account
- [x] Fix epilogue transition jumps/flicker
- [ ] Change storyboard identifiers to consts/enum
- [x] Stop "flicker" of app screen when presenting login at launch (#3120)
- [x] Remove `Login*` classes's interitance from `Signin*` classes (#7465)
- [ ] Show modal error messages in new screen. #7564
- [x] Ensure all analytics are being bumped correctly (#7541)
- [x] Fix content width on epilogue / iPad (https://github.com/wordpress-mobile/WordPress-iOS/pull/7549)

/cc @aerych

**Comment by nheagy** [comment]
## Design mocks:

Overview of every screen:
![ios-overview](https://cloud.githubusercontent.com/assets/517257/26738048/ec787b1a-4789-11e7-9c4f-f8e859143bb8.png)

Prologue screen with device versions:
![device-gallery5](https://cloud.githubusercontent.com/assets/517257/26738081/01848436-478a-11e7-8659-a670cbbccaec.png)

Detail for magic link screens:
_Note: the gravatar img is 100x100_
<img width="773" alt="screen-shot-2017-05-17-at-3-44-22-pm" src="https://cloud.githubusercontent.com/assets/517257/26738095/172d76c6-478a-11e7-9c79-7ae1c7f7fb74.png">

Detail for alert modal:
![site-address-modal1](https://cloud.githubusercontent.com/assets/517257/26738181/652e264a-478a-11e7-8c1f-01ca5282cdd6.png)

## Design Specs
Specs are found here: https://cloudup.com/ceTcuXrpACq
