### ISSUE TITLE
Jetpack Themes Browsing

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7468]
### Expected behavior
To be able to browse themes on a self hosted site with Jetpack.

### Actual behavior
The theme browser does not work for Jetpack sites. 

### Steps to reproduce the behavior
Go to the Themes browser

**Comment by elibud** [comment]
Check how all the actions on the theme browser screen work for uploaded themes and WP.com themes:
 
- [ ] Try & Customize uploaded theme https://github.com/wordpress-mobile/WordPress-iOS/issues/7650
- [ ] Try & Customize WP.com theme https://github.com/wordpress-mobile/WordPress-iOS/issues/7650
- [ ] Activate uploaded theme https://github.com/wordpress-mobile/WordPress-iOS/issues/7469
- [ ] Activate WP.com theme https://github.com/wordpress-mobile/WordPress-iOS/issues/7469
- [ ] Disable View for uploaded themes
- [ ] Disable Details for uploaded themes
- [ ] Disable Support for uploaded themes

@tonyr59h anything else you can think of?

**Comment by tonyr59h** [comment]
Great list! I've got a couple things:
1. We might have to make some changes for searching since we've got multiple sections.
2. We could keep uploaded theme's View/Details/Support enabled for themes that map to a .com theme.

**Comment by elibud** [comment]
> We could keep uploaded theme's View/Details/Support enabled for themes that map to a .com theme.
Absolutely, we just need to disable View/Details/Support for the Themes we don't have a valid URL for.

**Comment by elibud** [comment]
Moving the checklists items to https://github.com/wordpress-mobile/WordPress-iOS/issues/7469 and https://github.com/wordpress-mobile/WordPress-iOS/issues/7650
