### ISSUE TITLE
Login: Google Master Thread

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#7675]
Add Google account login to the existing login flow.

### Features
- [x] Email screen
  - [x] add Google button
- [x] Google auth flow
  - [ ] third party auth backup screen
- [x] Email found
  - [x] first use password screen (#7918)
- [x] Email not found
  - [ ] prepopulate email on signup tap (#8021)
  - [ ] preserve Google token for account link, if possible
- [x] Error (#7887)
  - _Same subtasks as above_
- [x] Support 2FA (#8010)
- [ ] New analytics specific to Google login

### Other issues
- [ ] Touch state handling for Google button (#8017)
- [x] Crash when dismissing Google VC with `Done` (#8012)
- [x] Google button placement overtop error label (#7902)
- [ ] Spinner: should start immediately when Google tapped, stop by the time error option returns (#8022)
- [ ] Limit 2FA code to numbers
- [ ] Improve/review error shown when no matching wpcom account is found (#8022)

## Mockup

[![social-auth-google-login-i2-cropped-thumb](https://user-images.githubusercontent.com/517257/29223408-af7728e8-7e83-11e7-951f-1838634f436f.png)](https://user-images.githubusercontent.com/517257/29625427-e53f8984-87e8-11e7-988c-e7913d575e63.png)

**Comment by aerych** [comment]
Did a bit of testing this morning with the feature. Most everything works as expected.  :) Just a few nitpicks:  

- [ ] First time google button is tapped it takes a moment before the new UIAlertView appears. Maybe call `configureViewLoading(true)` right away to start the spinner and disable things to prevent extra taps.

- [ ] 2fa if I enter invalid numeric input I see the desired error but if I enter letters a 400 response comes back and we show the error view with a cryptic message.  Maybe sanitize input so it only accepts numerics?  Otoh, the keyboard is numeric so maybe that's enough?  Thoughts?

- [ ] if I tap back to the email screen from the password screen or the 2fa screen the next button is still showing a spinner and the form is disabled.  Probably should call `configureViewLoading(false)` from needsMultifactorCode and existingUserNeedsConnection.
Should also disconnect google but not exactly sure where is best to do so.

- [ ] Trying to sign in with a google account not matching a wpcom account shows the error modal but the error message is the "This operation couldn't be completed. (WordPressComOAuthError error 0.)" message.   Tapping the google button again seems to try the same login attempt (same google account).  Need to disconnect google.

**Comment by nheagy** [comment]
> Maybe sanitize input so it only accepts numerics? Otoh, the keyboard is numeric so maybe that's enough?

You're right, we should limit to numbers. iirc on iPad numeric keyboard will still allow letters, and so will pasting. 👍 

I agree with the others. Thanks for the testing @aerych!
