### ISSUE TITLE
Activity Log and Rewind

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7832]
We want to implement the Activity Log with the rewind feature on the mobile apps. 

- [x] Support WordPress REST API https://github.com/wordpress-mobile/WordPress-iOS/pull/7995
- [x] Feed endpoint (with tests) https://github.com/wordpress-mobile/WordPress-iOS/pull/8051
- [x] Restore and restore status endpoints https://github.com/wordpress-mobile/WordPress-iOS/pull/8100
- [x] Dummy feed UI https://github.com/wordpress-mobile/WordPress-iOS/pull/8079
- [x] Mark rewindable activities in feed https://github.com/wordpress-mobile/WordPress-iOS/pull/8079
- [x] Mark discarded activities in feed, client side https://github.com/wordpress-mobile/WordPress-iOS/pull/8203
- [x] Add missing gridicons to the project https://github.com/wordpress-mobile/WordPress-iOS/issues/8185
- [x] Add actors to the feed https://github.com/wordpress-mobile/WordPress-iOS/pull/8079
- [x] Add Jetpack actor to the feed https://github.com/wordpress-mobile/WordPress-iOS/pull/8203
- [x] Add activity icons to the feed https://github.com/wordpress-mobile/WordPress-iOS/pull/8225
- [x] Color icons according to activity status   https://github.com/wordpress-mobile/WordPress-iOS/pull/8225
- [x] Rewind simple implementation https://github.com/wordpress-mobile/WordPress-iOS/pull/8229 
- [x] Add summary and text fields https://github.com/wordpress-mobile/WordPress-iOS/pull/8387
- [x] Mark discarded activities in feed, server side https://github.com/wordpress-mobile/WordPress-iOS/pull/8358
- [x] Integrate status endpoint https://github.com/wordpress-mobile/WordPress-iOS/pull/8524
- [x] Deprecated old status endpoint and check rewind progress from the new one https://github.com/wordpress-mobile/WordPress-iOS/pull/8524
- [x] Update remote to new `published` format https://github.com/wordpress-mobile/WordPress-iOS/pull/8729
- [x] Add `last_updated` field now that the format is correct https://github.com/wordpress-mobile/WordPress-iOS/pull/8732
- [x] Check that the icons don't become ovals on iPad landscape mode
- [x] Make the activity log is available for admin users on all Jetpack sites #9040
- [x] Make the activity log is available for admin users on all WordPress.com sites (check when it's done server side) #9040
- [x] Take into account site timezone on the feed #9666
- [x] Integrate output from status endpoint to display info about whether a restore is in progress #9666
- [x] Migrate to FluxC architecture #9656 
- [ ] Add client side storage
- [ ] After a rewind is completed, invalidate all site data
- [ ] Figure out pagination and refresh
- [ ] Add text formatting
- [ ] Add navigation to appropriate objects like posts, comments, plugins, etc. (big question mark here)
- [ ] Integrate output from status endpoint to display info about config
- [ ] Final design https://github.com/wordpress-mobile/WordPress-iOS/pull/8455 https://github.com/wordpress-mobile/WordPress-iOS/pull/8480 https://github.com/wordpress-mobile/WordPress-iOS/pull/8511 https://github.com/wordpress-mobile/WordPress-iOS/pull/8765 #9036

**Comment by designsimply** [comment]
I spot checked the PRs listed in the "Final design" item in the list, and everything there looks completed to me.

@elibud is there anything remaining in this list you'd like to continue tracking or can we close this issue?

**Comment by elibud** [comment]
Let's close this one, but ping @yaelirub as some things here you might want to pick up in your upcoming project. Thanks for the ping @designsimply!
