### ISSUE TITLE
Sign up: Master Issue Thread

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8109]
This is the Master Issue for the work around the new sign up flow. We are updating the sign up UX to better match the new Login flows.

- [x] Add feature flag for social signup (#8150)
- [x] Login prologue
  - Change 'Create a WordPress site' button text to 'Sign up to WordPress.com'
  - When click sign up, present email & google options
  - Tap dimmed space to return to previous screen
  - Move TOS here
- [x] Email entry screen (#8359 )
- [x] Magic link screen (#8405 )
- [x] Implement send email endpoint. (#8632)
- [x] Google flow for signup (#8639)
  - if account already exists, login
- [x] Signup Epilogue (#8637)
  - show password for email signups
- [x] Username changing screen
- [x] Direct `promptForLoginOrSignup` in Me tab to use new flows. (#8694)
- [x] Change `retryAsSignup` to use new flow (#8698 )
- [x] Google signup: Replace illustration with correct one from mockup 
- [x] Check that user creation endpoints are using the `locale` parameter
- [x] Add `locale` parameter to `/auth/send-signup-email` (#9014)
- [x] Check that all the stats are being sent at the right time, for example `signup_social_success` seems to be missing, please sync with @theck13 as we need to keep Android an iOS in sync and ideally a single funnel to track sign up (the one linked in the Auth Dashboard) (ref #8883 )

### External dependencies
 - New signup email
 - New endpoints
 - Avatar-with-plus asset

### After release
- [x] Epilogue: allow gravatar to be set
- [x] Rename `SiteCreationDomainSearchTableViewCell` since it's no longer just for Domains. https://github.com/wordpress-mobile/WordPress-iOS/pull/9066
- [x] Remove feature flag `socialSignup` https://github.com/wordpress-mobile/WordPress-iOS/pull/9109
- [x] Remove feature flag `usernameChanging`.
- [x] Nix `SignupViewController` class & associated view in Login.storyboard https://github.com/wordpress-mobile/WordPress-iOS/pull/9109 
- [ ] Make SiteCreationParams.theme non optional

**Comment by aerych** [comment]
When we wire up the TOS link(s) in the new sign up flow it might be nice if we could pass the user's locale (if we know it) as part of the query string.  See https://github.com/wordpress-mobile/WordPress-Android/pull/6266 for the Android implementation.
@nheagy , @ScoutHarris
