### ISSUE TITLE
Site Creation: Master Issue Thread

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8110]
This is the Master Issue for the work around the new site creation flow. We are updating site-creation UX to better match the new Login flows.

### Project setup
- [x] Add feature flag for site creation (#8169)
- [x] New create site storyboard (#8169)

### New create site flow
- [x] New design for empty My Sites ( #8306)
- [x] New design for all hidden My Sites (#8486)
- [x] Select site type screen (#8172)
- [x] Theme select screen (#8213)
- [x] Update Theme Selections to use new endpoint. (#8377) 
- [x] Site details screen (#8277)
- [x] Domain screen (#8181)
- [x] Add 'Create site' button to Domain screen (#8415)
- [x] Fix: app crashes when attempting to 'Switch Site' with only one site (#8441)
- [x] Site Creation: class for storing user options (#8533)
- [x] Creating… screen (#8431)
- [x] Congratulations epilogue (#8504)
  - Show Congratulations message
  - Fade in site once loaded
- [x] Error view (#8555)

### Project-wide
- [x] Helpshift origin tags (#8314)
- [x] New analytics (#8883)

### After release
- [x] Suggested Domains: handle no suggestions failure. (#8429)
- [x] Remove feature flag (https://github.com/wordpress-mobile/WordPress-iOS/pull/9013)
- [x] Nix `CreateNewBlogViewController` class (https://github.com/wordpress-mobile/WordPress-iOS/pull/9013)
- [x] Nix `WPAsyncBlockOperation` class (it's only used by `CreateNewBlogViewController`) (https://github.com/wordpress-mobile/WordPress-iOS/pull/9013)

### External dependencies
Assets:
- Window with W illustration for empty my sites
- Red titlebar version of the error window illustration
- Congratulations epilogue graphic/animation

![mobile-create-site-i41](https://user-images.githubusercontent.com/517257/32860882-9697489a-ca18-11e7-9c15-c921fe901154.png)
