### ISSUE TITLE
Login Wrapup: Master issue

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8136]
This is a master issue for a few login related tasks we're prioritizing while we work on sign up and site creation. 

- [x]  #8098 App crashes when keychain data is lost
- [x]  #8106 Login: 2FA accept SMS code without last digit
- [x] #8056 Login: allow two factor SMS codes to be re-requested with social login
- [x] #8036 Remove Google Login Feature Flag
- [x] #7633 Login: Update the stats screen's Jetpack login to use the wpcom login flow
- [x] #8335 NUX: too much padding on iPhone X

cc @nheagy @ScoutHarris

**Comment by nheagy** [comment]
All done!
