### ISSUE TITLE
Jetpack Plugins v1

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8318]
We're shipping a first version of plugin management. This issue is to keep track of all the remaining bits.

- [x] Enable plugins on production builds #8332
- [x] Make plugins available only for site with Jetpack 5.6 or higher #8319
- [x] Add analytics #8338
- [x] Test on iPad
- [x] Test simultaneous updates
- [x] Test if leaving the plugins section while updating a plugin works well
- [x] Test toggling autoupdates/active quickly
- [x] Don't allow removing akismet/vaultpress on AT sites #8334
- [x] Decide what to do about pagination, sites with many plugins
- [x] Show a notice/alert when an update completes/fails #8340
- [x] Add pull to refresh #8320

**Comment by koke** [comment]
I found an issue while toggling autoupdates on and off quickly where the 1.1 and 1.2 endpoints would return different states, and the app is not able to change the value. Miguel is investigating

**Comment by koke** [comment]
> Decide what to do about pagination, sites with many plugins

Looking at the API code, it seems it will return all the plugins unless you specify the offset/limit arguments. I think that's good enough for v1

**Comment by koke** [comment]
Forgot to close this one 😬
