### ISSUE TITLE
Support for Stock Photos / Free Photo Library

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#8954]
Grabbing media from websites to insert into posts is still kind of a clunky thing to have to do on mobile, so it’d be great if users could access a library of stock photography directly in the apps.

WordPress.com recently [added stock photography to the media library](https://href.li/?https://teamtinker.wordpress.com/2018/01/03/weve-soft-launched-the-free-photo-library/), and there’s an [API](https://href.li/?https://hogwartsp2.wordpress.com/2017/09/14/hiring-trial-projects/#comment-7467) we can use to add this to the app.

From Post Editor:
![stock-photos-ios-i2](https://user-images.githubusercontent.com/2722505/37941996-994ad1ea-31a3-11e8-9660-19badea57e28.jpg)

From Media Library:
![stock-photos-media-library-ios-i11](https://user-images.githubusercontent.com/2722505/37942004-9ce5361a-31a3-11e8-96ed-3954657f13a1.jpg)

# Tasks

- [x] Insert `Action sheet` in the ellipse button #8959
- [x] Show media picker from the `Action sheet` #8973
- [x] Populate media picker with mocked data source #8985
- [x] Use the real Stock Photos API to populate the media picker #8988
- [x] Add the selected images to the Editor (and Media library) #9019
- [x] Implement Stock Photos from Media Library `+` button  #9037 
- [x] Add image to empty view #9060
- [x] Implement the images carousel preview [#281 (MediaPicker-iOS)](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/281)
- [x] Implement bottom action bar for media picker [#282 (MediaPicker-iOS)](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/282)
- [x] Implement the Media Picker changes into the main WPiOS App #9067
- [x] Pagination #9115
- [x] Tracks events #9116
- [x] Pexels tappable link #9136
- [x] Search UX improvements: 
- - [x] Waiting for typing before calling the API #9059
- - [x] Open Stock Photos picker with the keyboard present #9043
- - [x] Dismiss the keyboard when start selecting images #9043
- - [x] Clear last search when dismissing the picker #9043
- - [x] When dismissing the Stock Photos picker, it shouldn't lose the first responder (currently it goes back to the title) #9054

**Comment by etoledom** [comment]
Updated with a list of tasks.
