### ISSUE TITLE
Zendesk Mobile: Master Issue Thread

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9020]
### Project
- [x] Add Zendesk pod to project. (#9026)
- [x] Update Zendesk SDK pod to v1.11.2.1 (#9141)
- [x] Add feature flag. (#9032)
- [x] Instantiate Zendesk using Zendesk app creds. (#9032)
- [x] Create new controller to display the Support view. (#9044)
- [x] New controller: make Version, Extra Debug, Activity Log functional. (#9049)
- [x] Launch new controller instead of `SupportViewController` in all applicable areas. (#9143)
- [x] Replace direct instantiation of `HelpshiftPresenter` with Zendesk:
  - [x]  `NotificationsViewController:gatherFeedback`  (App Feedback Prompt) (#9213)
  - [x] `WordPressAppDelegate` > App opened from FAQ URL - nothing to do. This is HS specific.
  - [x] `WordPressAuthenticationManager:presentLivechat` (#9222)
- [x] Add support for Jetpack & self-hosted users. (#9170)
- [x] Add support for users not logged in (i.e. sign up and log in). ([P2](https://wp.me/p9xubY-aS)) (#9374)
- [x] Fix issue where Zendesk identity is not always created. (#9220)
- [x] Replicate source tags from `SupportViewController`. (#9290)
- [x] Push notification set up:
   - [x] Get Webhook server integration set up. ([ZD documentation](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/handle_push_notifications_wh#server-integration))
   - [x] Get Webhook set up in Zendesk. ([ZD documentation](https://developer.zendesk.com/embeddables/docs/ios_support_sdk/handle_push_notifications_wh#account-configuration))
- [x] Implement Push notifications.
  - [x] Register devices. (#9242)
  - [x] Unregister devices. (#9242)
  - [x] Handle notifications. (indicator [ref](https://wp.me/p7cLQ7-rm/#comment-608))
    - [x] Show Zendesk notification alert. (#9310)
    - [x] Show Me tab indicator (#9325)
    - [x] Replace Me tab icon indicator image (#9373)
    - [x] Show Help & Support indicator (#9328)
    - [x] Show Support > My Tickets indicator (#9328)
    - [x] Show navigation bar > Help indicator (#9338)
    - [x] Make app aware of ZD notifications vs WP notifications.(#9368)
  - [x] Ticket deep-linking ([ref](https://developer.zendesk.com/embeddables/docs/ios/handle_push_notifications_wh#ticket-deep-linking)). - nothing to do. this just works since `zendesk_sdk_request_id` is part of the PN payload.
- [x] Add WPAnalytics tracks. (#9394)
- [x] Customize Zendesk UI colors. ([P2](https://wp.me/p9xubY-cC-p2)) (#9446)
- [x] Change identity behavior based on [this](https://wp.me/p9xubY-cO-p2) discussion. (#9486)
- [x] Allow user to change their Support email address (based on [this](https://wp.me/p9xubY-cO-p2) discussion). (#9492)
- [x] Check that error handling is sufficient.
- [x] Enable Feature Flag for internal testing. (10.1 release) (#9405)
- [x] Enable Feature Flag for everyone! (10.2 release) (#9501)

### Tickets
- [x] Show new ticket form from 'Contact Us'. (#9053)
- [x] Add 'My Tickets' option and show ticket list. (#9053)
- [x] Create and submit basic ticket. (#9053)
- [x] Add custom fields to tickets. (#9065)
- [x] Add 'origin' tag to ticket. (#9290)
- [x] Add 'Current Site' information to ticket. ([P2](https://wp.me/p9xubY-cn-p2)) (#9456)
- [x] Modify site information per [this](https://wp.me/p9xubY-cn-p2) discussion. (#9456)

### Guide
- [x] Launch Guide from 'WordPress Help Center'. (#9053)
- [x] Show Guide filtered by Mobile category and ‘iOS’ label. (#9053)
- [x] Import FAQs from Helpshift. ([ZD documentation](https://support.zendesk.com/hc/en-us/articles/115014608608-Migrating-existing-content-to-Help-Center))

### After Release
- [x] Add a Zendesk version of  `PushNotificationsManagerTests:testHelpshiftNotificationIsProperlyHandled`. (#9562)
- [x] Remove feature flag (#9576)
- [x] Remove Helpshift code from NUX View Controllers (#9575)
- [x] Remove Helpshift code. (#9576)
  - [x] SupportViewController
  - [x] HelpshiftPresenter
  - [x] HelpshiftUtils
  - [x] Vendor > Helpshift directory & contents.
  - [x] HelpshiftCustomConfig.plist
- [x] Remove WordPressSupportSourceTag+Helpers > toSupportSourceTag (#9568)
- [x] Remove BadgeNavigationItemRow (#9568)
- [x] Remove HS specific WPAnalytics. (#9571)
- [x] Remove Helpshift credentials. (#9577)

**Comment by ScoutHarris** [comment]
It's done baby!!!
