### ISSUE TITLE
Prime for Push Master Issue

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#9185]
## Goals
- Inform the user why they should enable notifications before we show them the system permission
- Don’t interrupt the user with permission
- Try to win-back existing users who declined notifications

## Tasks
- [x] Hide existing OS alert behind feature flag
- [ ] Add notification primer in settings (#9403)
- [x] Add notification primer after login epilogue (#9215)
  - [x] Ensure that the alert primer only appears once (#9215)
  - [x] Ensure the alert primer only appears for wpcom accounts (#9390)
- [x] Add inline notification primer to top of notifications (#9332)
- [ ] Add auth winback to top of notifications (#9469)

## Post-release Tasks
- [ ] Remove feature flag

## Analytics
Analytics will be considered as part of every task.
- [ ] `notifications_primer_seen` with parameter `location` and possible values `alert, inline, settings`. Occurs anytime one of the three primers appears: after one of the flows as an alert; in the notifications tab; when the screen is shown in settings.
  - [x] alert (#9215)
  - [x] inline (#9332)
  - [ ] settings
- [ ] `notifications_primer_allow_tapped` also with `location` parameter. Occurs when the *Allow* button is tapped on the primer
  - [x] alert (#9215)
  - [x] inline (#9332)
  - [ ] settings
- [ ] `notifications_primer_no_tapped` also with `location` parameter. Occurs when the *Not Now* button is tapped on the primer
  - [x] alert (#9215)
  - [x] inline (#9332)
- [ ] `notifications_winback_shown` with parameter `location` and value `inline`. Occurs when inline winback view is shown. (#9469)
- [ ] `notifications_winback_settings_tapped` Occurs when the *Go to iOS Settings* button is tapped on the winback (#9469)
- [ ] `notifications_winback_no_tapped` Occurs when the *No thanks* button is tapped on the winback (#9469)

![prime_for_push_i21](https://user-images.githubusercontent.com/517257/39207547-7a67df54-47bd-11e8-9002-76cd34a6fa5b.jpg)

**Comment by SylvesterWilmott** [comment]
Spot on but as we discussed:

> Add notification primer after login epilogue and after first post
Add notification dialog primer after login epilogue only

Events look good but can we differentiate between where `notifications_primer_allow_tapped` and `notifications_primer_no_tapped` were triggered, I guess by using the `location` parameter too?

**Comment by nheagy** [comment]
@SylvesterWilmott Ok, I've removed the reference to first post and I've clarified that those two events will use the `location` parameter too. Thanks!
