### ISSUE TITLE
Share Extension Improvements

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9335]
Lets go through the feedback we've received about the share extension and choose a couple of improvements and bug fixes to work on during Hack Week.

**Comment by bummytime** [comment]
Here is a handful of issues that we could work on:
* [ ] Extensions: Modular Site Picker - Featured Image Module #8143
* [ ] Extensions: Change the order of the sites #8645
* [ ] Draft extension: Fix notification text for draft posts #8672
* [ ] Extensions: Contributor role appears to successfully upload media #8621
* [ ] Extensions: not associating uploaded photo Media items with the post #9070
