### ISSUE TITLE
What's Next Master Issue

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#9447]
## Goals
- Help new users find their way around the interface
- Help users understand why they should take certain actions
- Help users have success when they create new web sites

## Tasks
- [x] Fancy Alert to turn on What's Next (#10163)
  - [x] `Never` button (#10181)
  - [ ] Review design on SE
- [ ] Step-by-step tutorials
  - [x] New NoticeView style (#9970)
    - [x] colored text w/ inline icon (#9970)
    - [x] two buttons for suggestions (#10198)
    - [ ] wide buttons stack vertically
  
  - [ ] Activation methods:
    - [ ] If this is users first site, show first unfinished step as soon as they visit the site details view (#10198)
    - [ ] Otherwise, show first unfinished task 3 seconds after visiting site details view
      - [ ] If they tap "not now" skip that tutorial for the next two suggestions
    - [ ] Only do this max 3 times. After that, they have to manually click "What's Next" menu item (#10198)
  - [ ] The seven tutorials:
    - [ ] Continue site setup
    - [x] View Site (#10238)
    - [x] Choose a theme (#10238)
    - [x] Customize (#10238)
    - [ ] Share your site
    - [ ] Publish a post
    - [ ] Follow Other Sites
- [x] Checklist screen (#9838)
  - [ ] Skip All button
- [ ] Notification/Award
- [ ] Suppress web tours with `?hide_tours=1`

## Post-release Tasks
- [ ] Remove feature flag

## Analytics
Analytics will be considered as part of every task.
- [ ] `whats_next_dialog_seen`
- [ ] `whats_next_dialog_negative_tapped`
- [ ] `whats_next_dialog_positive_tapped`
- [ ] `whats_next_list_accessed`
- [ ] `whats_next_list_create_site_tapped`
- [ ] `whats_next_list_view_site_tapped`
- [ ] `whats_next_list_browse_themes_tapped`
- [ ] `whats_next_list_customize_site_tapped`
- [ ] `whats_next_list_add_social_tapped`
- [ ] `whats_next_list_publish_post_tapped`
- [ ] `whats_next_list_follow_site_tapped`
- [ ] `whats_next_list_skip_all_tapped`
- [ ] `site_whats_next_complete`
- [ ] `whats_next_list_complete_seen`
- [ ] `notifications_whats_next_received`
- [ ] `notifications_whats_next_opened`
- [ ] `whats_next_request_seen`
- [ ] `whats_next_request_negative_tapped`
- [ ] `whats_next_request_positive_tapped`
- [ ] `whats_next_dialog_final_seen`
- [ ] `whats_next_dialog_final_negative_tapped`
- [ ] `whats_next_dialog_final_positive_tapped`

### Image:

![it_ios_i4](https://user-images.githubusercontent.com/517257/40446309-06b71a12-5e8c-11e8-8adf-080aa85957bb.jpg)

### Zeplin:
https://scene.zeplin.io/project/5a86dcb255c808f8b2c44169

## Android Counterpart
https://github.com/wordpress-mobile/WordPress-Android/issues/7707
